// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/SpacetimeDBClient.g.h"
#include "DBCache/WithBsatn.h"
#include "BSATN/UEBSATNHelpers.h"
#include "ModuleBindings/Tables/PlayerTable.g.h"
#include "ModuleBindings/Tables/PlayerAccountTable.g.h"
#include "ModuleBindings/Tables/WorldEntityTable.g.h"

static FReducer DecodeReducer(const FReducerEvent& Event)
{
    const FString& ReducerName = Event.ReducerCall.ReducerName;

    if (ReducerName == TEXT("authenticate_with_eos"))
    {
        FAuthenticateWithEosArgs Args = UE::SpacetimeDB::Deserialize<FAuthenticateWithEosArgs>(Event.ReducerCall.Args);
        return FReducer::AuthenticateWithEos(Args);
    }

    if (ReducerName == TEXT("clear_entities"))
    {
        FClearEntitiesArgs Args = UE::SpacetimeDB::Deserialize<FClearEntitiesArgs>(Event.ReducerCall.Args);
        return FReducer::ClearEntities(Args);
    }

    if (ReducerName == TEXT("create_player"))
    {
        FCreatePlayerArgs Args = UE::SpacetimeDB::Deserialize<FCreatePlayerArgs>(Event.ReducerCall.Args);
        return FReducer::CreatePlayer(Args);
    }

    if (ReducerName == TEXT("move_player"))
    {
        FMovePlayerArgs Args = UE::SpacetimeDB::Deserialize<FMovePlayerArgs>(Event.ReducerCall.Args);
        return FReducer::MovePlayer(Args);
    }

    if (ReducerName == TEXT("seed_entities"))
    {
        FSeedEntitiesArgs Args = UE::SpacetimeDB::Deserialize<FSeedEntitiesArgs>(Event.ReducerCall.Args);
        return FReducer::SeedEntities(Args);
    }

    return FReducer();
}

UDbConnection::UDbConnection(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer)
{
	SetReducerFlags = ObjectInitializer.CreateDefaultSubobject<USetReducerFlags>(this, TEXT("SetReducerFlags"));

	Db = ObjectInitializer.CreateDefaultSubobject<URemoteTables>(this, TEXT("RemoteTables"));
	Db->Initialize();
	
	Reducers = ObjectInitializer.CreateDefaultSubobject<URemoteReducers>(this, TEXT("RemoteReducers"));
	Reducers->SetCallReducerFlags = SetReducerFlags;
	Reducers->Conn = this;

	Procedures = ObjectInitializer.CreateDefaultSubobject<URemoteProcedures>(this, TEXT("RemoteProcedures"));
	Procedures->Conn = this;

	RegisterTable<FPlayerType, UPlayerTable, FEventContext>(TEXT("player"), Db->Player);
	RegisterTable<FPlayerAccountType, UPlayerAccountTable, FEventContext>(TEXT("player_account"), Db->PlayerAccount);
	RegisterTable<FWorldEntityType, UWorldEntityTable, FEventContext>(TEXT("world_entity"), Db->WorldEntity);
}

FContextBase::FContextBase(UDbConnection* InConn)
{
	Db = InConn->Db;
	Reducers = InConn->Reducers;
	SetReducerFlags = InConn->SetReducerFlags;
	Procedures = InConn->Procedures;
	Conn = InConn;
}
bool FContextBase::IsActive() const
{
	return Conn->IsActive();
}
void FContextBase::Disconnect()
{
	Conn->Disconnect();
}
USubscriptionBuilder* FContextBase::SubscriptionBuilder()
{
	return Conn->SubscriptionBuilder();
}
bool FContextBase::TryGetIdentity(FSpacetimeDBIdentity& OutIdentity) const
{
	return Conn->TryGetIdentity(OutIdentity);
}
FSpacetimeDBConnectionId FContextBase::GetConnectionId() const
{
	return Conn->GetConnectionId();
}

void URemoteTables::Initialize()
{

	/** Creating tables */
	Player = NewObject<UPlayerTable>(this);
	PlayerAccount = NewObject<UPlayerAccountTable>(this);
	WorldEntity = NewObject<UWorldEntityTable>(this);
	/**/

	/** Initialization */
	Player->PostInitialize();
	PlayerAccount->PostInitialize();
	WorldEntity->PostInitialize();
	/**/
}

void USetReducerFlags::AuthenticateWithEos(ECallReducerFlags Flag)
{
	FlagMap.Add("AuthenticateWithEos", Flag);
}
void USetReducerFlags::ClearEntities(ECallReducerFlags Flag)
{
	FlagMap.Add("ClearEntities", Flag);
}
void USetReducerFlags::CreatePlayer(ECallReducerFlags Flag)
{
	FlagMap.Add("CreatePlayer", Flag);
}
void USetReducerFlags::MovePlayer(ECallReducerFlags Flag)
{
	FlagMap.Add("MovePlayer", Flag);
}
void USetReducerFlags::SeedEntities(ECallReducerFlags Flag)
{
	FlagMap.Add("SeedEntities", Flag);
}

void URemoteReducers::AuthenticateWithEos(const FString& EosProductUserId, const FString& DisplayName, const FString& Platform)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("authenticate_with_eos"), FAuthenticateWithEosArgs(EosProductUserId, DisplayName, Platform), SetCallReducerFlags);
}

bool URemoteReducers::InvokeAuthenticateWithEos(const FReducerEventContext& Context, const UAuthenticateWithEosReducer* Args)
{
    if (!OnAuthenticateWithEos.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for AuthenticateWithEos"));
        }
        return false;
    }

    OnAuthenticateWithEos.Broadcast(Context, Args->EosProductUserId, Args->DisplayName, Args->Platform);
    return true;
}

bool URemoteReducers::InvokeAuthenticateWithEosWithArgs(const FReducerEventContext& Context, const FAuthenticateWithEosArgs& Args)
{
    if (!OnAuthenticateWithEos.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for AuthenticateWithEos"));
        }
        return false;
    }

    OnAuthenticateWithEos.Broadcast(Context, Args.EosProductUserId, Args.DisplayName, Args.Platform);
    return true;
}

void URemoteReducers::ClearEntities()
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("clear_entities"), FClearEntitiesArgs(), SetCallReducerFlags);
}

bool URemoteReducers::InvokeClearEntities(const FReducerEventContext& Context, const UClearEntitiesReducer* Args)
{
    if (!OnClearEntities.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for ClearEntities"));
        }
        return false;
    }

    OnClearEntities.Broadcast(Context);
    return true;
}

bool URemoteReducers::InvokeClearEntitiesWithArgs(const FReducerEventContext& Context, const FClearEntitiesArgs& Args)
{
    if (!OnClearEntities.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for ClearEntities"));
        }
        return false;
    }

    OnClearEntities.Broadcast(Context);
    return true;
}

void URemoteReducers::CreatePlayer(const FString& DisplayName)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("create_player"), FCreatePlayerArgs(DisplayName), SetCallReducerFlags);
}

bool URemoteReducers::InvokeCreatePlayer(const FReducerEventContext& Context, const UCreatePlayerReducer* Args)
{
    if (!OnCreatePlayer.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for CreatePlayer"));
        }
        return false;
    }

    OnCreatePlayer.Broadcast(Context, Args->DisplayName);
    return true;
}

bool URemoteReducers::InvokeCreatePlayerWithArgs(const FReducerEventContext& Context, const FCreatePlayerArgs& Args)
{
    if (!OnCreatePlayer.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for CreatePlayer"));
        }
        return false;
    }

    OnCreatePlayer.Broadcast(Context, Args.DisplayName);
    return true;
}

void URemoteReducers::MovePlayer(const double X, const double Y, const double Z, const float Yaw, const uint32 Seq)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("move_player"), FMovePlayerArgs(X, Y, Z, Yaw, Seq), SetCallReducerFlags);
}

bool URemoteReducers::InvokeMovePlayer(const FReducerEventContext& Context, const UMovePlayerReducer* Args)
{
    if (!OnMovePlayer.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for MovePlayer"));
        }
        return false;
    }

    OnMovePlayer.Broadcast(Context, Args->X, Args->Y, Args->Z, Args->Yaw, Args->Seq);
    return true;
}

bool URemoteReducers::InvokeMovePlayerWithArgs(const FReducerEventContext& Context, const FMovePlayerArgs& Args)
{
    if (!OnMovePlayer.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for MovePlayer"));
        }
        return false;
    }

    OnMovePlayer.Broadcast(Context, Args.X, Args.Y, Args.Z, Args.Yaw, Args.Seq);
    return true;
}

void URemoteReducers::SeedEntities(const uint32 Count)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("seed_entities"), FSeedEntitiesArgs(Count), SetCallReducerFlags);
}

bool URemoteReducers::InvokeSeedEntities(const FReducerEventContext& Context, const USeedEntitiesReducer* Args)
{
    if (!OnSeedEntities.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for SeedEntities"));
        }
        return false;
    }

    OnSeedEntities.Broadcast(Context, Args->Count);
    return true;
}

bool URemoteReducers::InvokeSeedEntitiesWithArgs(const FReducerEventContext& Context, const FSeedEntitiesArgs& Args)
{
    if (!OnSeedEntities.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for SeedEntities"));
        }
        return false;
    }

    OnSeedEntities.Broadcast(Context, Args.Count);
    return true;
}

void UDbConnection::PostInitProperties()
{
    Super::PostInitProperties();
    
    // Connect OnUnhandledReducerError to Reducers.InternalOnUnhandledReducerError
    if (Reducers)
    {
        Reducers->InternalOnUnhandledReducerError.AddDynamic(this, &UDbConnection::OnUnhandledReducerErrorHandler);
    }

    // Connect OnUnhandledProcedureError to Procedures.InternalOnUnhandledProcedureError
    if (Procedures)
    {
        Procedures->InternalOnUnhandledProcedureError.AddDynamic(this, &UDbConnection::OnUnhandledProcedureErrorHandler);
    }
}

UFUNCTION()
void UDbConnection::OnUnhandledReducerErrorHandler(const FReducerEventContext& Context, const FString& Error)
{
    if (OnUnhandledReducerError.IsBound())
    {
        OnUnhandledReducerError.Broadcast(Context, Error);
    }
}

UFUNCTION()
void UDbConnection::OnUnhandledProcedureErrorHandler(const FProcedureEventContext& Context, const FString& Error)
{
    if (OnUnhandledProcedureError.IsBound())
    {
        OnUnhandledProcedureError.Broadcast(Context, Error);
    }
}

void UDbConnection::ReducerEvent(const FReducerEvent& Event)
{
    if (!Reducers) { return; }

    FReducer DecodedReducer = DecodeReducer(Event);

    FNyxReducerEvent ReducerEvent;
    ReducerEvent.CallerConnectionId = Event.CallerConnectionId;
    ReducerEvent.CallerIdentity     = Event.CallerIdentity;
    ReducerEvent.EnergyConsumed     = Event.EnergyConsumed;
    ReducerEvent.Status             = Event.Status;
    ReducerEvent.Timestamp          = Event.Timestamp;
    ReducerEvent.Reducer            = DecodedReducer;

    FReducerEventContext Context(this, ReducerEvent);

    // Use hardcoded string matching for reducer dispatching
    const FString& ReducerName = Event.ReducerCall.ReducerName;

    if (ReducerName == TEXT("authenticate_with_eos"))
    {
        FAuthenticateWithEosArgs Args = ReducerEvent.Reducer.GetAsAuthenticateWithEos();
        Reducers->InvokeAuthenticateWithEosWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("clear_entities"))
    {
        FClearEntitiesArgs Args = ReducerEvent.Reducer.GetAsClearEntities();
        Reducers->InvokeClearEntitiesWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("create_player"))
    {
        FCreatePlayerArgs Args = ReducerEvent.Reducer.GetAsCreatePlayer();
        Reducers->InvokeCreatePlayerWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("move_player"))
    {
        FMovePlayerArgs Args = ReducerEvent.Reducer.GetAsMovePlayer();
        Reducers->InvokeMovePlayerWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("seed_entities"))
    {
        FSeedEntitiesArgs Args = ReducerEvent.Reducer.GetAsSeedEntities();
        Reducers->InvokeSeedEntitiesWithArgs(Context, Args);
        return;
    }

    UE_LOG(LogTemp, Warning, TEXT("Unknown reducer: %s"), *ReducerName);
}

void UDbConnection::ReducerEventFailed(const FReducerEvent& Event, const FString ErrorMessage)
{
    if (!Reducers) { return; }

    FNyxReducerEvent ReducerEvent;
    ReducerEvent.CallerConnectionId = Event.CallerConnectionId;
    ReducerEvent.CallerIdentity     = Event.CallerIdentity;
    ReducerEvent.EnergyConsumed     = Event.EnergyConsumed;
    ReducerEvent.Status             = Event.Status;
    ReducerEvent.Timestamp          = Event.Timestamp;

    FReducerEventContext Context(this, ReducerEvent);

    if (Reducers->InternalOnUnhandledReducerError.IsBound())
    {
        Reducers->InternalOnUnhandledReducerError.Broadcast(Context, ErrorMessage);
    }
}

void UDbConnection::ProcedureEventFailed(const FProcedureEvent& Event, const FString ErrorMessage)
{
    if (!Procedures) { return; }

    FNyxProcedureEvent ProcedureEvent;
    ProcedureEvent.Status             = FSpacetimeDBProcedureStatus::FromStatus(Event.Status);
    ProcedureEvent.Timestamp          = Event.Timestamp;

    FProcedureEventContext Context(this, ProcedureEvent);

    if (Procedures->InternalOnUnhandledProcedureError.IsBound())
    {
        Procedures->InternalOnUnhandledProcedureError.Broadcast(Context, ErrorMessage);
    }
}

UDbConnectionBuilder* UDbConnection::Builder()
{
	return NewObject<UDbConnectionBuilder>();
}
// Added for creating subscriptions
USubscriptionBuilder* UDbConnection::SubscriptionBuilder()
{
	USubscriptionBuilder* Builder = NewObject<USubscriptionBuilder>(this);
	Builder->Conn = this;
	return Builder;
}
USubscriptionBuilder* USubscriptionBuilder::OnApplied(FOnSubscriptionApplied Callback)
{
	OnAppliedDelegateInternal = Callback;
	return this;
}
USubscriptionBuilder* USubscriptionBuilder::OnError(FOnSubscriptionError Callback)
{
	OnErrorDelegateInternal = Callback;
	return this;
}
USubscriptionHandle* USubscriptionBuilder::Subscribe(const TArray<FString>& SQL)
{
	USubscriptionHandle* Handle = NewObject<USubscriptionHandle>();

	// Store user callbacks on the handle
	Handle->Conn = Conn;
	Handle->OnAppliedDelegate = OnAppliedDelegateInternal;
	Handle->OnErrorDelegate = OnErrorDelegateInternal;

	// Bind forwarding functions that will convert base contexts
	FSubscriptionEventDelegate BaseApplied;
	BaseApplied.BindUFunction(Handle, TEXT("ForwardOnApplied"));
	OnAppliedBase(BaseApplied);

	FSubscriptionErrorDelegate BaseError;
	BaseError.BindUFunction(Handle, TEXT("ForwardOnError"));
	OnErrorBase(BaseError);

	SubscribeBase(SQL, Handle);
	if (Conn)
	{
		Conn->StartSubscription(Handle);
	}
	return Handle;
}
USubscriptionHandle* USubscriptionBuilder::SubscribeToAllTables()
{
	return Subscribe({ "SELECT * FROM * " });
}

USubscriptionHandle::USubscriptionHandle(UDbConnection* InConn)
{
	Conn = InConn;
}

void USubscriptionHandle::ForwardOnApplied(const FSubscriptionEventContextBase& BaseCtx)
{
	if (OnAppliedDelegate.IsBound())
	{
		FSubscriptionEventContext Ctx(Conn);
		OnAppliedDelegate.Execute(Ctx);
	}
}

void USubscriptionHandle::ForwardOnError(const FErrorContextBase& BaseCtx)
{
	if (OnErrorDelegate.IsBound())
	{
		FErrorContext Ctx(Conn, BaseCtx.Error);
		OnErrorDelegate.Execute(Ctx);
	}
}


// Cast from parent to child class
UDbConnectionBuilder* UDbConnectionBuilder::WithUri(const FString& InUri)
{
	return Cast<UDbConnectionBuilder>(WithUriBase(InUri));
}
UDbConnectionBuilder* UDbConnectionBuilder::WithDatabaseName(const FString& InName)
{
	return Cast<UDbConnectionBuilder>(WithDatabaseNameBase(InName));
}
UDbConnectionBuilder* UDbConnectionBuilder::WithToken(const FString& InToken)
{
	return Cast<UDbConnectionBuilder>(WithTokenBase(InToken));
}
UDbConnectionBuilder* UDbConnectionBuilder::WithCompression(const ESpacetimeDBCompression& InCompression)
{
	return Cast<UDbConnectionBuilder>(WithCompressionBase(InCompression));
}
UDbConnectionBuilder* UDbConnectionBuilder::OnConnect(FOnConnectDelegate Callback)
{
	OnConnectDelegateInternal = Callback;
	return this;
}
UDbConnectionBuilder* UDbConnectionBuilder::OnConnectError(FOnConnectErrorDelegate Callback)
{
	return Cast<UDbConnectionBuilder>(OnConnectErrorBase(Callback));
}
UDbConnectionBuilder* UDbConnectionBuilder::OnDisconnect(FOnDisconnectDelegate Callback)
{
	OnDisconnectDelegateInternal = Callback;
	return this;
}
UDbConnection* UDbConnectionBuilder::Build()
{
	UDbConnection* Connection = NewObject<UDbConnection>();

	// Store delegates on the connection for later use
	Connection->OnConnectDelegate = OnConnectDelegateInternal;
	Connection->OnDisconnectDelegate = OnDisconnectDelegateInternal;

	// Wrap delegates so the base builder can bind them
	FOnConnectBaseDelegate BaseConnect;
	BaseConnect.BindUFunction(Connection, TEXT("ForwardOnConnect"));
	Connection->SetOnConnectDelegate(BaseConnect);
	OnConnectBase(BaseConnect);

	FOnDisconnectBaseDelegate BaseDisconnect;
	BaseDisconnect.BindUFunction(Connection, TEXT("ForwardOnDisconnect"));
	Connection->SetOnDisconnectDelegate(BaseDisconnect);
	OnDisconnectBase(BaseDisconnect);

	return Cast<UDbConnection>(BuildConnection(Connection));
}
void UDbConnection::ForwardOnConnect(UDbConnectionBase* BaseConnection, FSpacetimeDBIdentity InIdentity, const FString& InToken)
{
	if (OnConnectDelegate.IsBound())
	{
		OnConnectDelegate.Execute(this, Identity, Token);
	}
}
void UDbConnection::ForwardOnDisconnect(UDbConnectionBase* BaseConnection, const FString& Error)
{
	if (OnDisconnectDelegate.IsBound())
	{
		OnDisconnectDelegate.Execute(this, Error);
	}
}


void UDbConnection::DbUpdate(const FDatabaseUpdateType& Update, const FSpacetimeDBEvent& Event)
{
    FNyxEvent BaseEvent;
    BaseEvent.Tag = Event.Tag;

    switch (Event.Tag)
    {
    case ESpacetimeDBEventTag::Reducer:
    {
        FReducerEvent ReducerEvent = Event.GetAsReducer();
        FReducer Reducer = DecodeReducer(ReducerEvent);
        BaseEvent = FNyxEvent::Reducer(Reducer);
        break;
    }

    case ESpacetimeDBEventTag::SubscribeApplied:
        BaseEvent = FNyxEvent::SubscribeApplied(Event.GetAsSubscribeApplied());
        break;

    case ESpacetimeDBEventTag::UnsubscribeApplied:
        BaseEvent = FNyxEvent::UnsubscribeApplied(Event.GetAsUnsubscribeApplied());
        break;

    case ESpacetimeDBEventTag::Disconnected:
        BaseEvent = FNyxEvent::Disconnected(Event.GetAsDisconnected());
        break;

    case ESpacetimeDBEventTag::SubscribeError:
        BaseEvent = FNyxEvent::SubscribeError(Event.GetAsSubscribeError());
        break;

    case ESpacetimeDBEventTag::UnknownTransaction:
        BaseEvent = FNyxEvent::UnknownTransaction(Event.GetAsUnknownTransaction());
        break;

    default:
        break;
    }

    FEventContext Context(this, BaseEvent);
    // Populate typed reducer args for convenience in table handlers

    ApplyRegisteredTableUpdates(Update, &Context);
}

