// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/SpacetimeDBClient.g.h"
#include "DBCache/WithBsatn.h"
#include "BSATN/UEBSATNHelpers.h"
#include "ModuleBindings/Tables/BenchCounterTable.g.h"
#include "ModuleBindings/Tables/BenchEntityTable.g.h"
#include "ModuleBindings/Tables/BenchTickLogTable.g.h"
#include "ModuleBindings/Tables/PhysicsBodyTable.g.h"
#include "ModuleBindings/Tables/PlayerTable.g.h"
#include "ModuleBindings/Tables/PlayerAccountTable.g.h"
#include "ModuleBindings/Tables/WorldEntityTable.g.h"

static FReducer DecodeReducer(const FReducerEvent& Event)
{
    const FString& ReducerName = Event.ReducerCall.ReducerName;

    if (ReducerName == TEXT("authenticate_with_eos"))
    {
        FAuthenticateWithEosArgs Args = UE::SpacetimeDB::Deserialize<FAuthenticateWithEosArgs>(Event.ReducerCall.Args);
        return FReducer::AuthenticateWithEos(Args);
    }

    if (ReducerName == TEXT("bench_burst"))
    {
        FBenchBurstArgs Args = UE::SpacetimeDB::Deserialize<FBenchBurstArgs>(Event.ReducerCall.Args);
        return FReducer::BenchBurst(Args);
    }

    if (ReducerName == TEXT("bench_burst_update"))
    {
        FBenchBurstUpdateArgs Args = UE::SpacetimeDB::Deserialize<FBenchBurstUpdateArgs>(Event.ReducerCall.Args);
        return FReducer::BenchBurstUpdate(Args);
    }

    if (ReducerName == TEXT("bench_complex"))
    {
        FBenchComplexArgs Args = UE::SpacetimeDB::Deserialize<FBenchComplexArgs>(Event.ReducerCall.Args);
        return FReducer::BenchComplex(Args);
    }

    if (ReducerName == TEXT("bench_medium"))
    {
        FBenchMediumArgs Args = UE::SpacetimeDB::Deserialize<FBenchMediumArgs>(Event.ReducerCall.Args);
        return FReducer::BenchMedium(Args);
    }

    if (ReducerName == TEXT("bench_memory"))
    {
        FBenchMemoryArgs Args = UE::SpacetimeDB::Deserialize<FBenchMemoryArgs>(Event.ReducerCall.Args);
        return FReducer::BenchMemory(Args);
    }

    if (ReducerName == TEXT("bench_reset"))
    {
        FBenchResetArgs Args = UE::SpacetimeDB::Deserialize<FBenchResetArgs>(Event.ReducerCall.Args);
        return FReducer::BenchReset(Args);
    }

    if (ReducerName == TEXT("bench_seed"))
    {
        FBenchSeedArgs Args = UE::SpacetimeDB::Deserialize<FBenchSeedArgs>(Event.ReducerCall.Args);
        return FReducer::BenchSeed(Args);
    }

    if (ReducerName == TEXT("bench_simple"))
    {
        FBenchSimpleArgs Args = UE::SpacetimeDB::Deserialize<FBenchSimpleArgs>(Event.ReducerCall.Args);
        return FReducer::BenchSimple(Args);
    }

    if (ReducerName == TEXT("bench_start_tick"))
    {
        FBenchStartTickArgs Args = UE::SpacetimeDB::Deserialize<FBenchStartTickArgs>(Event.ReducerCall.Args);
        return FReducer::BenchStartTick(Args);
    }

    if (ReducerName == TEXT("bench_stop_tick"))
    {
        FBenchStopTickArgs Args = UE::SpacetimeDB::Deserialize<FBenchStopTickArgs>(Event.ReducerCall.Args);
        return FReducer::BenchStopTick(Args);
    }

    if (ReducerName == TEXT("clear_entities"))
    {
        FClearEntitiesArgs Args = UE::SpacetimeDB::Deserialize<FClearEntitiesArgs>(Event.ReducerCall.Args);
        return FReducer::ClearEntities(Args);
    }

    if (ReducerName == TEXT("create_player"))
    {
        FCreatePlayerArgs Args = UE::SpacetimeDB::Deserialize<FCreatePlayerArgs>(Event.ReducerCall.Args);
        return FReducer::CreatePlayer(Args);
    }

    if (ReducerName == TEXT("move_player"))
    {
        FMovePlayerArgs Args = UE::SpacetimeDB::Deserialize<FMovePlayerArgs>(Event.ReducerCall.Args);
        return FReducer::MovePlayer(Args);
    }

    if (ReducerName == TEXT("physics_cleanup"))
    {
        FPhysicsCleanupArgs Args = UE::SpacetimeDB::Deserialize<FPhysicsCleanupArgs>(Event.ReducerCall.Args);
        return FReducer::PhysicsCleanup(Args);
    }

    if (ReducerName == TEXT("physics_reset"))
    {
        FPhysicsResetArgs Args = UE::SpacetimeDB::Deserialize<FPhysicsResetArgs>(Event.ReducerCall.Args);
        return FReducer::PhysicsReset(Args);
    }

    if (ReducerName == TEXT("physics_update"))
    {
        FPhysicsUpdateArgs Args = UE::SpacetimeDB::Deserialize<FPhysicsUpdateArgs>(Event.ReducerCall.Args);
        return FReducer::PhysicsUpdate(Args);
    }

    if (ReducerName == TEXT("seed_entities"))
    {
        FSeedEntitiesArgs Args = UE::SpacetimeDB::Deserialize<FSeedEntitiesArgs>(Event.ReducerCall.Args);
        return FReducer::SeedEntities(Args);
    }

    if (ReducerName == TEXT("spawn_projectile"))
    {
        FSpawnProjectileArgs Args = UE::SpacetimeDB::Deserialize<FSpawnProjectileArgs>(Event.ReducerCall.Args);
        return FReducer::SpawnProjectile(Args);
    }

    return FReducer();
}

UDbConnection::UDbConnection(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer)
{
	SetReducerFlags = ObjectInitializer.CreateDefaultSubobject<USetReducerFlags>(this, TEXT("SetReducerFlags"));

	Db = ObjectInitializer.CreateDefaultSubobject<URemoteTables>(this, TEXT("RemoteTables"));
	Db->Initialize();
	
	Reducers = ObjectInitializer.CreateDefaultSubobject<URemoteReducers>(this, TEXT("RemoteReducers"));
	Reducers->SetCallReducerFlags = SetReducerFlags;
	Reducers->Conn = this;

	Procedures = ObjectInitializer.CreateDefaultSubobject<URemoteProcedures>(this, TEXT("RemoteProcedures"));
	Procedures->Conn = this;

	RegisterTable<FBenchCounterType, UBenchCounterTable, FEventContext>(TEXT("bench_counter"), Db->BenchCounter);
	RegisterTable<FBenchEntityType, UBenchEntityTable, FEventContext>(TEXT("bench_entity"), Db->BenchEntity);
	RegisterTable<FBenchTickLogType, UBenchTickLogTable, FEventContext>(TEXT("bench_tick_log"), Db->BenchTickLog);
	RegisterTable<FPhysicsBodyType, UPhysicsBodyTable, FEventContext>(TEXT("physics_body"), Db->PhysicsBody);
	RegisterTable<FPlayerType, UPlayerTable, FEventContext>(TEXT("player"), Db->Player);
	RegisterTable<FPlayerAccountType, UPlayerAccountTable, FEventContext>(TEXT("player_account"), Db->PlayerAccount);
	RegisterTable<FWorldEntityType, UWorldEntityTable, FEventContext>(TEXT("world_entity"), Db->WorldEntity);
}

FContextBase::FContextBase(UDbConnection* InConn)
{
	Db = InConn->Db;
	Reducers = InConn->Reducers;
	SetReducerFlags = InConn->SetReducerFlags;
	Procedures = InConn->Procedures;
	Conn = InConn;
}
bool FContextBase::IsActive() const
{
	return Conn->IsActive();
}
void FContextBase::Disconnect()
{
	Conn->Disconnect();
}
USubscriptionBuilder* FContextBase::SubscriptionBuilder()
{
	return Conn->SubscriptionBuilder();
}
bool FContextBase::TryGetIdentity(FSpacetimeDBIdentity& OutIdentity) const
{
	return Conn->TryGetIdentity(OutIdentity);
}
FSpacetimeDBConnectionId FContextBase::GetConnectionId() const
{
	return Conn->GetConnectionId();
}

void URemoteTables::Initialize()
{

	/** Creating tables */
	BenchCounter = NewObject<UBenchCounterTable>(this);
	BenchEntity = NewObject<UBenchEntityTable>(this);
	BenchTickLog = NewObject<UBenchTickLogTable>(this);
	PhysicsBody = NewObject<UPhysicsBodyTable>(this);
	Player = NewObject<UPlayerTable>(this);
	PlayerAccount = NewObject<UPlayerAccountTable>(this);
	WorldEntity = NewObject<UWorldEntityTable>(this);
	/**/

	/** Initialization */
	BenchCounter->PostInitialize();
	BenchEntity->PostInitialize();
	BenchTickLog->PostInitialize();
	PhysicsBody->PostInitialize();
	Player->PostInitialize();
	PlayerAccount->PostInitialize();
	WorldEntity->PostInitialize();
	/**/
}

void USetReducerFlags::AuthenticateWithEos(ECallReducerFlags Flag)
{
	FlagMap.Add("AuthenticateWithEos", Flag);
}
void USetReducerFlags::BenchBurst(ECallReducerFlags Flag)
{
	FlagMap.Add("BenchBurst", Flag);
}
void USetReducerFlags::BenchBurstUpdate(ECallReducerFlags Flag)
{
	FlagMap.Add("BenchBurstUpdate", Flag);
}
void USetReducerFlags::BenchComplex(ECallReducerFlags Flag)
{
	FlagMap.Add("BenchComplex", Flag);
}
void USetReducerFlags::BenchMedium(ECallReducerFlags Flag)
{
	FlagMap.Add("BenchMedium", Flag);
}
void USetReducerFlags::BenchMemory(ECallReducerFlags Flag)
{
	FlagMap.Add("BenchMemory", Flag);
}
void USetReducerFlags::BenchReset(ECallReducerFlags Flag)
{
	FlagMap.Add("BenchReset", Flag);
}
void USetReducerFlags::BenchSeed(ECallReducerFlags Flag)
{
	FlagMap.Add("BenchSeed", Flag);
}
void USetReducerFlags::BenchSimple(ECallReducerFlags Flag)
{
	FlagMap.Add("BenchSimple", Flag);
}
void USetReducerFlags::BenchStartTick(ECallReducerFlags Flag)
{
	FlagMap.Add("BenchStartTick", Flag);
}
void USetReducerFlags::BenchStopTick(ECallReducerFlags Flag)
{
	FlagMap.Add("BenchStopTick", Flag);
}
void USetReducerFlags::ClearEntities(ECallReducerFlags Flag)
{
	FlagMap.Add("ClearEntities", Flag);
}
void USetReducerFlags::CreatePlayer(ECallReducerFlags Flag)
{
	FlagMap.Add("CreatePlayer", Flag);
}
void USetReducerFlags::MovePlayer(ECallReducerFlags Flag)
{
	FlagMap.Add("MovePlayer", Flag);
}
void USetReducerFlags::PhysicsCleanup(ECallReducerFlags Flag)
{
	FlagMap.Add("PhysicsCleanup", Flag);
}
void USetReducerFlags::PhysicsReset(ECallReducerFlags Flag)
{
	FlagMap.Add("PhysicsReset", Flag);
}
void USetReducerFlags::PhysicsUpdate(ECallReducerFlags Flag)
{
	FlagMap.Add("PhysicsUpdate", Flag);
}
void USetReducerFlags::SeedEntities(ECallReducerFlags Flag)
{
	FlagMap.Add("SeedEntities", Flag);
}
void USetReducerFlags::SpawnProjectile(ECallReducerFlags Flag)
{
	FlagMap.Add("SpawnProjectile", Flag);
}

void URemoteReducers::AuthenticateWithEos(const FString& EosProductUserId, const FString& DisplayName, const FString& Platform)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("authenticate_with_eos"), FAuthenticateWithEosArgs(EosProductUserId, DisplayName, Platform), SetCallReducerFlags);
}

bool URemoteReducers::InvokeAuthenticateWithEos(const FReducerEventContext& Context, const UAuthenticateWithEosReducer* Args)
{
    if (!OnAuthenticateWithEos.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for AuthenticateWithEos"));
        }
        return false;
    }

    OnAuthenticateWithEos.Broadcast(Context, Args->EosProductUserId, Args->DisplayName, Args->Platform);
    return true;
}

bool URemoteReducers::InvokeAuthenticateWithEosWithArgs(const FReducerEventContext& Context, const FAuthenticateWithEosArgs& Args)
{
    if (!OnAuthenticateWithEos.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for AuthenticateWithEos"));
        }
        return false;
    }

    OnAuthenticateWithEos.Broadcast(Context, Args.EosProductUserId, Args.DisplayName, Args.Platform);
    return true;
}

void URemoteReducers::BenchBurst(const uint32 Count)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("bench_burst"), FBenchBurstArgs(Count), SetCallReducerFlags);
}

bool URemoteReducers::InvokeBenchBurst(const FReducerEventContext& Context, const UBenchBurstReducer* Args)
{
    if (!OnBenchBurst.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for BenchBurst"));
        }
        return false;
    }

    OnBenchBurst.Broadcast(Context, Args->Count);
    return true;
}

bool URemoteReducers::InvokeBenchBurstWithArgs(const FReducerEventContext& Context, const FBenchBurstArgs& Args)
{
    if (!OnBenchBurst.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for BenchBurst"));
        }
        return false;
    }

    OnBenchBurst.Broadcast(Context, Args.Count);
    return true;
}

void URemoteReducers::BenchBurstUpdate(const uint32 Count)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("bench_burst_update"), FBenchBurstUpdateArgs(Count), SetCallReducerFlags);
}

bool URemoteReducers::InvokeBenchBurstUpdate(const FReducerEventContext& Context, const UBenchBurstUpdateReducer* Args)
{
    if (!OnBenchBurstUpdate.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for BenchBurstUpdate"));
        }
        return false;
    }

    OnBenchBurstUpdate.Broadcast(Context, Args->Count);
    return true;
}

bool URemoteReducers::InvokeBenchBurstUpdateWithArgs(const FReducerEventContext& Context, const FBenchBurstUpdateArgs& Args)
{
    if (!OnBenchBurstUpdate.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for BenchBurstUpdate"));
        }
        return false;
    }

    OnBenchBurstUpdate.Broadcast(Context, Args.Count);
    return true;
}

void URemoteReducers::BenchComplex()
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("bench_complex"), FBenchComplexArgs(), SetCallReducerFlags);
}

bool URemoteReducers::InvokeBenchComplex(const FReducerEventContext& Context, const UBenchComplexReducer* Args)
{
    if (!OnBenchComplex.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for BenchComplex"));
        }
        return false;
    }

    OnBenchComplex.Broadcast(Context);
    return true;
}

bool URemoteReducers::InvokeBenchComplexWithArgs(const FReducerEventContext& Context, const FBenchComplexArgs& Args)
{
    if (!OnBenchComplex.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for BenchComplex"));
        }
        return false;
    }

    OnBenchComplex.Broadcast(Context);
    return true;
}

void URemoteReducers::BenchMedium()
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("bench_medium"), FBenchMediumArgs(), SetCallReducerFlags);
}

bool URemoteReducers::InvokeBenchMedium(const FReducerEventContext& Context, const UBenchMediumReducer* Args)
{
    if (!OnBenchMedium.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for BenchMedium"));
        }
        return false;
    }

    OnBenchMedium.Broadcast(Context);
    return true;
}

bool URemoteReducers::InvokeBenchMediumWithArgs(const FReducerEventContext& Context, const FBenchMediumArgs& Args)
{
    if (!OnBenchMedium.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for BenchMedium"));
        }
        return false;
    }

    OnBenchMedium.Broadcast(Context);
    return true;
}

void URemoteReducers::BenchMemory(const uint32 Megabytes)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("bench_memory"), FBenchMemoryArgs(Megabytes), SetCallReducerFlags);
}

bool URemoteReducers::InvokeBenchMemory(const FReducerEventContext& Context, const UBenchMemoryReducer* Args)
{
    if (!OnBenchMemory.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for BenchMemory"));
        }
        return false;
    }

    OnBenchMemory.Broadcast(Context, Args->Megabytes);
    return true;
}

bool URemoteReducers::InvokeBenchMemoryWithArgs(const FReducerEventContext& Context, const FBenchMemoryArgs& Args)
{
    if (!OnBenchMemory.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for BenchMemory"));
        }
        return false;
    }

    OnBenchMemory.Broadcast(Context, Args.Megabytes);
    return true;
}

void URemoteReducers::BenchReset()
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("bench_reset"), FBenchResetArgs(), SetCallReducerFlags);
}

bool URemoteReducers::InvokeBenchReset(const FReducerEventContext& Context, const UBenchResetReducer* Args)
{
    if (!OnBenchReset.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for BenchReset"));
        }
        return false;
    }

    OnBenchReset.Broadcast(Context);
    return true;
}

bool URemoteReducers::InvokeBenchResetWithArgs(const FReducerEventContext& Context, const FBenchResetArgs& Args)
{
    if (!OnBenchReset.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for BenchReset"));
        }
        return false;
    }

    OnBenchReset.Broadcast(Context);
    return true;
}

void URemoteReducers::BenchSeed(const uint32 Count)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("bench_seed"), FBenchSeedArgs(Count), SetCallReducerFlags);
}

bool URemoteReducers::InvokeBenchSeed(const FReducerEventContext& Context, const UBenchSeedReducer* Args)
{
    if (!OnBenchSeed.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for BenchSeed"));
        }
        return false;
    }

    OnBenchSeed.Broadcast(Context, Args->Count);
    return true;
}

bool URemoteReducers::InvokeBenchSeedWithArgs(const FReducerEventContext& Context, const FBenchSeedArgs& Args)
{
    if (!OnBenchSeed.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for BenchSeed"));
        }
        return false;
    }

    OnBenchSeed.Broadcast(Context, Args.Count);
    return true;
}

void URemoteReducers::BenchSimple()
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("bench_simple"), FBenchSimpleArgs(), SetCallReducerFlags);
}

bool URemoteReducers::InvokeBenchSimple(const FReducerEventContext& Context, const UBenchSimpleReducer* Args)
{
    if (!OnBenchSimple.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for BenchSimple"));
        }
        return false;
    }

    OnBenchSimple.Broadcast(Context);
    return true;
}

bool URemoteReducers::InvokeBenchSimpleWithArgs(const FReducerEventContext& Context, const FBenchSimpleArgs& Args)
{
    if (!OnBenchSimple.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for BenchSimple"));
        }
        return false;
    }

    OnBenchSimple.Broadcast(Context);
    return true;
}

void URemoteReducers::BenchStartTick(const uint64 IntervalMs)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("bench_start_tick"), FBenchStartTickArgs(IntervalMs), SetCallReducerFlags);
}

bool URemoteReducers::InvokeBenchStartTick(const FReducerEventContext& Context, const UBenchStartTickReducer* Args)
{
    if (!OnBenchStartTick.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for BenchStartTick"));
        }
        return false;
    }

    OnBenchStartTick.Broadcast(Context, Args->IntervalMs);
    return true;
}

bool URemoteReducers::InvokeBenchStartTickWithArgs(const FReducerEventContext& Context, const FBenchStartTickArgs& Args)
{
    if (!OnBenchStartTick.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for BenchStartTick"));
        }
        return false;
    }

    OnBenchStartTick.Broadcast(Context, Args.IntervalMs);
    return true;
}

void URemoteReducers::BenchStopTick()
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("bench_stop_tick"), FBenchStopTickArgs(), SetCallReducerFlags);
}

bool URemoteReducers::InvokeBenchStopTick(const FReducerEventContext& Context, const UBenchStopTickReducer* Args)
{
    if (!OnBenchStopTick.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for BenchStopTick"));
        }
        return false;
    }

    OnBenchStopTick.Broadcast(Context);
    return true;
}

bool URemoteReducers::InvokeBenchStopTickWithArgs(const FReducerEventContext& Context, const FBenchStopTickArgs& Args)
{
    if (!OnBenchStopTick.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for BenchStopTick"));
        }
        return false;
    }

    OnBenchStopTick.Broadcast(Context);
    return true;
}

void URemoteReducers::ClearEntities()
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("clear_entities"), FClearEntitiesArgs(), SetCallReducerFlags);
}

bool URemoteReducers::InvokeClearEntities(const FReducerEventContext& Context, const UClearEntitiesReducer* Args)
{
    if (!OnClearEntities.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for ClearEntities"));
        }
        return false;
    }

    OnClearEntities.Broadcast(Context);
    return true;
}

bool URemoteReducers::InvokeClearEntitiesWithArgs(const FReducerEventContext& Context, const FClearEntitiesArgs& Args)
{
    if (!OnClearEntities.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for ClearEntities"));
        }
        return false;
    }

    OnClearEntities.Broadcast(Context);
    return true;
}

void URemoteReducers::CreatePlayer(const FString& DisplayName)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("create_player"), FCreatePlayerArgs(DisplayName), SetCallReducerFlags);
}

bool URemoteReducers::InvokeCreatePlayer(const FReducerEventContext& Context, const UCreatePlayerReducer* Args)
{
    if (!OnCreatePlayer.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for CreatePlayer"));
        }
        return false;
    }

    OnCreatePlayer.Broadcast(Context, Args->DisplayName);
    return true;
}

bool URemoteReducers::InvokeCreatePlayerWithArgs(const FReducerEventContext& Context, const FCreatePlayerArgs& Args)
{
    if (!OnCreatePlayer.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for CreatePlayer"));
        }
        return false;
    }

    OnCreatePlayer.Broadcast(Context, Args.DisplayName);
    return true;
}

void URemoteReducers::MovePlayer(const double X, const double Y, const double Z, const float Yaw, const uint32 Seq)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("move_player"), FMovePlayerArgs(X, Y, Z, Yaw, Seq), SetCallReducerFlags);
}

bool URemoteReducers::InvokeMovePlayer(const FReducerEventContext& Context, const UMovePlayerReducer* Args)
{
    if (!OnMovePlayer.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for MovePlayer"));
        }
        return false;
    }

    OnMovePlayer.Broadcast(Context, Args->X, Args->Y, Args->Z, Args->Yaw, Args->Seq);
    return true;
}

bool URemoteReducers::InvokeMovePlayerWithArgs(const FReducerEventContext& Context, const FMovePlayerArgs& Args)
{
    if (!OnMovePlayer.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for MovePlayer"));
        }
        return false;
    }

    OnMovePlayer.Broadcast(Context, Args.X, Args.Y, Args.Z, Args.Yaw, Args.Seq);
    return true;
}

void URemoteReducers::PhysicsCleanup()
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("physics_cleanup"), FPhysicsCleanupArgs(), SetCallReducerFlags);
}

bool URemoteReducers::InvokePhysicsCleanup(const FReducerEventContext& Context, const UPhysicsCleanupReducer* Args)
{
    if (!OnPhysicsCleanup.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for PhysicsCleanup"));
        }
        return false;
    }

    OnPhysicsCleanup.Broadcast(Context);
    return true;
}

bool URemoteReducers::InvokePhysicsCleanupWithArgs(const FReducerEventContext& Context, const FPhysicsCleanupArgs& Args)
{
    if (!OnPhysicsCleanup.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for PhysicsCleanup"));
        }
        return false;
    }

    OnPhysicsCleanup.Broadcast(Context);
    return true;
}

void URemoteReducers::PhysicsReset()
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("physics_reset"), FPhysicsResetArgs(), SetCallReducerFlags);
}

bool URemoteReducers::InvokePhysicsReset(const FReducerEventContext& Context, const UPhysicsResetReducer* Args)
{
    if (!OnPhysicsReset.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for PhysicsReset"));
        }
        return false;
    }

    OnPhysicsReset.Broadcast(Context);
    return true;
}

bool URemoteReducers::InvokePhysicsResetWithArgs(const FReducerEventContext& Context, const FPhysicsResetArgs& Args)
{
    if (!OnPhysicsReset.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for PhysicsReset"));
        }
        return false;
    }

    OnPhysicsReset.Broadcast(Context);
    return true;
}

void URemoteReducers::PhysicsUpdate(const uint64 EntityId, const double PosX, const double PosY, const double PosZ, const double VelX, const double VelY, const double VelZ, const bool Active)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("physics_update"), FPhysicsUpdateArgs(EntityId, PosX, PosY, PosZ, VelX, VelY, VelZ, Active), SetCallReducerFlags);
}

bool URemoteReducers::InvokePhysicsUpdate(const FReducerEventContext& Context, const UPhysicsUpdateReducer* Args)
{
    if (!OnPhysicsUpdate.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for PhysicsUpdate"));
        }
        return false;
    }

    OnPhysicsUpdate.Broadcast(Context, Args->EntityId, Args->PosX, Args->PosY, Args->PosZ, Args->VelX, Args->VelY, Args->VelZ, Args->Active);
    return true;
}

bool URemoteReducers::InvokePhysicsUpdateWithArgs(const FReducerEventContext& Context, const FPhysicsUpdateArgs& Args)
{
    if (!OnPhysicsUpdate.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for PhysicsUpdate"));
        }
        return false;
    }

    OnPhysicsUpdate.Broadcast(Context, Args.EntityId, Args.PosX, Args.PosY, Args.PosZ, Args.VelX, Args.VelY, Args.VelZ, Args.Active);
    return true;
}

void URemoteReducers::SeedEntities(const uint32 Count)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("seed_entities"), FSeedEntitiesArgs(Count), SetCallReducerFlags);
}

bool URemoteReducers::InvokeSeedEntities(const FReducerEventContext& Context, const USeedEntitiesReducer* Args)
{
    if (!OnSeedEntities.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for SeedEntities"));
        }
        return false;
    }

    OnSeedEntities.Broadcast(Context, Args->Count);
    return true;
}

bool URemoteReducers::InvokeSeedEntitiesWithArgs(const FReducerEventContext& Context, const FSeedEntitiesArgs& Args)
{
    if (!OnSeedEntities.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for SeedEntities"));
        }
        return false;
    }

    OnSeedEntities.Broadcast(Context, Args.Count);
    return true;
}

void URemoteReducers::SpawnProjectile(const double PosX, const double PosY, const double PosZ, const double VelX, const double VelY, const double VelZ)
{
    if (!Conn)
    {
        UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null"));
        return;
    }

	Conn->CallReducerTyped(TEXT("spawn_projectile"), FSpawnProjectileArgs(PosX, PosY, PosZ, VelX, VelY, VelZ), SetCallReducerFlags);
}

bool URemoteReducers::InvokeSpawnProjectile(const FReducerEventContext& Context, const USpawnProjectileReducer* Args)
{
    if (!OnSpawnProjectile.IsBound())
    {
        // Handle unhandled reducer error
        if (InternalOnUnhandledReducerError.IsBound())
        {
            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases
            // For now, just broadcast any error
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for SpawnProjectile"));
        }
        return false;
    }

    OnSpawnProjectile.Broadcast(Context, Args->PosX, Args->PosY, Args->PosZ, Args->VelX, Args->VelY, Args->VelZ);
    return true;
}

bool URemoteReducers::InvokeSpawnProjectileWithArgs(const FReducerEventContext& Context, const FSpawnProjectileArgs& Args)
{
    if (!OnSpawnProjectile.IsBound())
    {
        if (InternalOnUnhandledReducerError.IsBound())
        {
            InternalOnUnhandledReducerError.Broadcast(Context, TEXT("No handler registered for SpawnProjectile"));
        }
        return false;
    }

    OnSpawnProjectile.Broadcast(Context, Args.PosX, Args.PosY, Args.PosZ, Args.VelX, Args.VelY, Args.VelZ);
    return true;
}

void UDbConnection::PostInitProperties()
{
    Super::PostInitProperties();
    
    // Connect OnUnhandledReducerError to Reducers.InternalOnUnhandledReducerError
    if (Reducers)
    {
        Reducers->InternalOnUnhandledReducerError.AddDynamic(this, &UDbConnection::OnUnhandledReducerErrorHandler);
    }

    // Connect OnUnhandledProcedureError to Procedures.InternalOnUnhandledProcedureError
    if (Procedures)
    {
        Procedures->InternalOnUnhandledProcedureError.AddDynamic(this, &UDbConnection::OnUnhandledProcedureErrorHandler);
    }
}

UFUNCTION()
void UDbConnection::OnUnhandledReducerErrorHandler(const FReducerEventContext& Context, const FString& Error)
{
    if (OnUnhandledReducerError.IsBound())
    {
        OnUnhandledReducerError.Broadcast(Context, Error);
    }
}

UFUNCTION()
void UDbConnection::OnUnhandledProcedureErrorHandler(const FProcedureEventContext& Context, const FString& Error)
{
    if (OnUnhandledProcedureError.IsBound())
    {
        OnUnhandledProcedureError.Broadcast(Context, Error);
    }
}

void UDbConnection::ReducerEvent(const FReducerEvent& Event)
{
    if (!Reducers) { return; }

    FReducer DecodedReducer = DecodeReducer(Event);

    FNyxReducerEvent ReducerEvent;
    ReducerEvent.CallerConnectionId = Event.CallerConnectionId;
    ReducerEvent.CallerIdentity     = Event.CallerIdentity;
    ReducerEvent.EnergyConsumed     = Event.EnergyConsumed;
    ReducerEvent.Status             = Event.Status;
    ReducerEvent.Timestamp          = Event.Timestamp;
    ReducerEvent.Reducer            = DecodedReducer;

    FReducerEventContext Context(this, ReducerEvent);

    // Use hardcoded string matching for reducer dispatching
    const FString& ReducerName = Event.ReducerCall.ReducerName;

    if (ReducerName == TEXT("authenticate_with_eos"))
    {
        FAuthenticateWithEosArgs Args = ReducerEvent.Reducer.GetAsAuthenticateWithEos();
        Reducers->InvokeAuthenticateWithEosWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("bench_burst"))
    {
        FBenchBurstArgs Args = ReducerEvent.Reducer.GetAsBenchBurst();
        Reducers->InvokeBenchBurstWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("bench_burst_update"))
    {
        FBenchBurstUpdateArgs Args = ReducerEvent.Reducer.GetAsBenchBurstUpdate();
        Reducers->InvokeBenchBurstUpdateWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("bench_complex"))
    {
        FBenchComplexArgs Args = ReducerEvent.Reducer.GetAsBenchComplex();
        Reducers->InvokeBenchComplexWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("bench_medium"))
    {
        FBenchMediumArgs Args = ReducerEvent.Reducer.GetAsBenchMedium();
        Reducers->InvokeBenchMediumWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("bench_memory"))
    {
        FBenchMemoryArgs Args = ReducerEvent.Reducer.GetAsBenchMemory();
        Reducers->InvokeBenchMemoryWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("bench_reset"))
    {
        FBenchResetArgs Args = ReducerEvent.Reducer.GetAsBenchReset();
        Reducers->InvokeBenchResetWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("bench_seed"))
    {
        FBenchSeedArgs Args = ReducerEvent.Reducer.GetAsBenchSeed();
        Reducers->InvokeBenchSeedWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("bench_simple"))
    {
        FBenchSimpleArgs Args = ReducerEvent.Reducer.GetAsBenchSimple();
        Reducers->InvokeBenchSimpleWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("bench_start_tick"))
    {
        FBenchStartTickArgs Args = ReducerEvent.Reducer.GetAsBenchStartTick();
        Reducers->InvokeBenchStartTickWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("bench_stop_tick"))
    {
        FBenchStopTickArgs Args = ReducerEvent.Reducer.GetAsBenchStopTick();
        Reducers->InvokeBenchStopTickWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("clear_entities"))
    {
        FClearEntitiesArgs Args = ReducerEvent.Reducer.GetAsClearEntities();
        Reducers->InvokeClearEntitiesWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("create_player"))
    {
        FCreatePlayerArgs Args = ReducerEvent.Reducer.GetAsCreatePlayer();
        Reducers->InvokeCreatePlayerWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("move_player"))
    {
        FMovePlayerArgs Args = ReducerEvent.Reducer.GetAsMovePlayer();
        Reducers->InvokeMovePlayerWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("physics_cleanup"))
    {
        FPhysicsCleanupArgs Args = ReducerEvent.Reducer.GetAsPhysicsCleanup();
        Reducers->InvokePhysicsCleanupWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("physics_reset"))
    {
        FPhysicsResetArgs Args = ReducerEvent.Reducer.GetAsPhysicsReset();
        Reducers->InvokePhysicsResetWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("physics_update"))
    {
        FPhysicsUpdateArgs Args = ReducerEvent.Reducer.GetAsPhysicsUpdate();
        Reducers->InvokePhysicsUpdateWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("seed_entities"))
    {
        FSeedEntitiesArgs Args = ReducerEvent.Reducer.GetAsSeedEntities();
        Reducers->InvokeSeedEntitiesWithArgs(Context, Args);
        return;
    }
    if (ReducerName == TEXT("spawn_projectile"))
    {
        FSpawnProjectileArgs Args = ReducerEvent.Reducer.GetAsSpawnProjectile();
        Reducers->InvokeSpawnProjectileWithArgs(Context, Args);
        return;
    }

    UE_LOG(LogTemp, Warning, TEXT("Unknown reducer: %s"), *ReducerName);
}

void UDbConnection::ReducerEventFailed(const FReducerEvent& Event, const FString ErrorMessage)
{
    if (!Reducers) { return; }

    FNyxReducerEvent ReducerEvent;
    ReducerEvent.CallerConnectionId = Event.CallerConnectionId;
    ReducerEvent.CallerIdentity     = Event.CallerIdentity;
    ReducerEvent.EnergyConsumed     = Event.EnergyConsumed;
    ReducerEvent.Status             = Event.Status;
    ReducerEvent.Timestamp          = Event.Timestamp;

    FReducerEventContext Context(this, ReducerEvent);

    if (Reducers->InternalOnUnhandledReducerError.IsBound())
    {
        Reducers->InternalOnUnhandledReducerError.Broadcast(Context, ErrorMessage);
    }
}

void UDbConnection::ProcedureEventFailed(const FProcedureEvent& Event, const FString ErrorMessage)
{
    if (!Procedures) { return; }

    FNyxProcedureEvent ProcedureEvent;
    ProcedureEvent.Status             = FSpacetimeDBProcedureStatus::FromStatus(Event.Status);
    ProcedureEvent.Timestamp          = Event.Timestamp;

    FProcedureEventContext Context(this, ProcedureEvent);

    if (Procedures->InternalOnUnhandledProcedureError.IsBound())
    {
        Procedures->InternalOnUnhandledProcedureError.Broadcast(Context, ErrorMessage);
    }
}

UDbConnectionBuilder* UDbConnection::Builder()
{
	return NewObject<UDbConnectionBuilder>();
}
// Added for creating subscriptions
USubscriptionBuilder* UDbConnection::SubscriptionBuilder()
{
	USubscriptionBuilder* Builder = NewObject<USubscriptionBuilder>(this);
	Builder->Conn = this;
	return Builder;
}
USubscriptionBuilder* USubscriptionBuilder::OnApplied(FOnSubscriptionApplied Callback)
{
	OnAppliedDelegateInternal = Callback;
	return this;
}
USubscriptionBuilder* USubscriptionBuilder::OnError(FOnSubscriptionError Callback)
{
	OnErrorDelegateInternal = Callback;
	return this;
}
USubscriptionHandle* USubscriptionBuilder::Subscribe(const TArray<FString>& SQL)
{
	USubscriptionHandle* Handle = NewObject<USubscriptionHandle>();

	// Store user callbacks on the handle
	Handle->Conn = Conn;
	Handle->OnAppliedDelegate = OnAppliedDelegateInternal;
	Handle->OnErrorDelegate = OnErrorDelegateInternal;

	// Bind forwarding functions that will convert base contexts
	FSubscriptionEventDelegate BaseApplied;
	BaseApplied.BindUFunction(Handle, TEXT("ForwardOnApplied"));
	OnAppliedBase(BaseApplied);

	FSubscriptionErrorDelegate BaseError;
	BaseError.BindUFunction(Handle, TEXT("ForwardOnError"));
	OnErrorBase(BaseError);

	SubscribeBase(SQL, Handle);
	if (Conn)
	{
		Conn->StartSubscription(Handle);
	}
	return Handle;
}
USubscriptionHandle* USubscriptionBuilder::SubscribeToAllTables()
{
	return Subscribe({ "SELECT * FROM * " });
}

USubscriptionHandle::USubscriptionHandle(UDbConnection* InConn)
{
	Conn = InConn;
}

void USubscriptionHandle::ForwardOnApplied(const FSubscriptionEventContextBase& BaseCtx)
{
	if (OnAppliedDelegate.IsBound())
	{
		FSubscriptionEventContext Ctx(Conn);
		OnAppliedDelegate.Execute(Ctx);
	}
}

void USubscriptionHandle::ForwardOnError(const FErrorContextBase& BaseCtx)
{
	if (OnErrorDelegate.IsBound())
	{
		FErrorContext Ctx(Conn, BaseCtx.Error);
		OnErrorDelegate.Execute(Ctx);
	}
}


// Cast from parent to child class
UDbConnectionBuilder* UDbConnectionBuilder::WithUri(const FString& InUri)
{
	return Cast<UDbConnectionBuilder>(WithUriBase(InUri));
}
UDbConnectionBuilder* UDbConnectionBuilder::WithDatabaseName(const FString& InName)
{
	return Cast<UDbConnectionBuilder>(WithDatabaseNameBase(InName));
}
UDbConnectionBuilder* UDbConnectionBuilder::WithToken(const FString& InToken)
{
	return Cast<UDbConnectionBuilder>(WithTokenBase(InToken));
}
UDbConnectionBuilder* UDbConnectionBuilder::WithCompression(const ESpacetimeDBCompression& InCompression)
{
	return Cast<UDbConnectionBuilder>(WithCompressionBase(InCompression));
}
UDbConnectionBuilder* UDbConnectionBuilder::OnConnect(FOnConnectDelegate Callback)
{
	OnConnectDelegateInternal = Callback;
	return this;
}
UDbConnectionBuilder* UDbConnectionBuilder::OnConnectError(FOnConnectErrorDelegate Callback)
{
	return Cast<UDbConnectionBuilder>(OnConnectErrorBase(Callback));
}
UDbConnectionBuilder* UDbConnectionBuilder::OnDisconnect(FOnDisconnectDelegate Callback)
{
	OnDisconnectDelegateInternal = Callback;
	return this;
}
UDbConnection* UDbConnectionBuilder::Build()
{
	UDbConnection* Connection = NewObject<UDbConnection>();

	// Store delegates on the connection for later use
	Connection->OnConnectDelegate = OnConnectDelegateInternal;
	Connection->OnDisconnectDelegate = OnDisconnectDelegateInternal;

	// Wrap delegates so the base builder can bind them
	FOnConnectBaseDelegate BaseConnect;
	BaseConnect.BindUFunction(Connection, TEXT("ForwardOnConnect"));
	Connection->SetOnConnectDelegate(BaseConnect);
	OnConnectBase(BaseConnect);

	FOnDisconnectBaseDelegate BaseDisconnect;
	BaseDisconnect.BindUFunction(Connection, TEXT("ForwardOnDisconnect"));
	Connection->SetOnDisconnectDelegate(BaseDisconnect);
	OnDisconnectBase(BaseDisconnect);

	return Cast<UDbConnection>(BuildConnection(Connection));
}
void UDbConnection::ForwardOnConnect(UDbConnectionBase* BaseConnection, FSpacetimeDBIdentity InIdentity, const FString& InToken)
{
	if (OnConnectDelegate.IsBound())
	{
		OnConnectDelegate.Execute(this, Identity, Token);
	}
}
void UDbConnection::ForwardOnDisconnect(UDbConnectionBase* BaseConnection, const FString& Error)
{
	if (OnDisconnectDelegate.IsBound())
	{
		OnDisconnectDelegate.Execute(this, Error);
	}
}


void UDbConnection::DbUpdate(const FDatabaseUpdateType& Update, const FSpacetimeDBEvent& Event)
{
    FNyxEvent BaseEvent;
    BaseEvent.Tag = Event.Tag;

    switch (Event.Tag)
    {
    case ESpacetimeDBEventTag::Reducer:
    {
        FReducerEvent ReducerEvent = Event.GetAsReducer();
        FReducer Reducer = DecodeReducer(ReducerEvent);
        BaseEvent = FNyxEvent::Reducer(Reducer);
        break;
    }

    case ESpacetimeDBEventTag::SubscribeApplied:
        BaseEvent = FNyxEvent::SubscribeApplied(Event.GetAsSubscribeApplied());
        break;

    case ESpacetimeDBEventTag::UnsubscribeApplied:
        BaseEvent = FNyxEvent::UnsubscribeApplied(Event.GetAsUnsubscribeApplied());
        break;

    case ESpacetimeDBEventTag::Disconnected:
        BaseEvent = FNyxEvent::Disconnected(Event.GetAsDisconnected());
        break;

    case ESpacetimeDBEventTag::SubscribeError:
        BaseEvent = FNyxEvent::SubscribeError(Event.GetAsSubscribeError());
        break;

    case ESpacetimeDBEventTag::UnknownTransaction:
        BaseEvent = FNyxEvent::UnknownTransaction(Event.GetAsUnknownTransaction());
        break;

    default:
        break;
    }

    FEventContext Context(this, BaseEvent);
    // Populate typed reducer args for convenience in table handlers

    ApplyRegisteredTableUpdates(Update, &Context);
}

