// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/CharacterStatsTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UCharacterStatsTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FCharacterStatsType>>();

    TSharedPtr<FTableCache<FCharacterStatsType>> CharacterStatsTable = Data->GetOrAdd(TableName);
    CharacterStatsTable->AddUniqueConstraint<FSpacetimeDBIdentity>("identity", [](const FCharacterStatsType& Row) -> const FSpacetimeDBIdentity& {
        return Row.Identity; });

    Identity = NewObject<UCharacterStatsIdentityUniqueIndex>(this);
    Identity->SetCache(CharacterStatsTable);

    /***/
}

FTableAppliedDiff<FCharacterStatsType> UCharacterStatsTable::Update(TArray<FWithBsatn<FCharacterStatsType>> InsertsRef, TArray<FWithBsatn<FCharacterStatsType>> DeletesRef)
{
    FTableAppliedDiff<FCharacterStatsType> Diff = BaseUpdate<FCharacterStatsType>(InsertsRef, DeletesRef, Data, TableName);

    Diff.DeriveUpdatesByPrimaryKey<FSpacetimeDBIdentity>(
        [](const FCharacterStatsType& Row) 
        {
            return Row.Identity; 
        }
    );

    return Diff;
}

int32 UCharacterStatsTable::Count() const
{
    return GetRowCountFromTable<FCharacterStatsType>(Data, TableName);
}

TArray<FCharacterStatsType> UCharacterStatsTable::Iter() const
{
    return GetAllRowsFromTable<FCharacterStatsType>(Data, TableName);
}
