// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/CombatEventTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UCombatEventTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FCombatEventType>>();

    TSharedPtr<FTableCache<FCombatEventType>> CombatEventTable = Data->GetOrAdd(TableName);
    CombatEventTable->AddUniqueConstraint<uint64>("id", [](const FCombatEventType& Row) -> const uint64& {
        return Row.Id; });

    Id = NewObject<UCombatEventIdUniqueIndex>(this);
    Id->SetCache(CombatEventTable);

    /***/
}

FTableAppliedDiff<FCombatEventType> UCombatEventTable::Update(TArray<FWithBsatn<FCombatEventType>> InsertsRef, TArray<FWithBsatn<FCombatEventType>> DeletesRef)
{
    FTableAppliedDiff<FCombatEventType> Diff = BaseUpdate<FCombatEventType>(InsertsRef, DeletesRef, Data, TableName);

    Diff.DeriveUpdatesByPrimaryKey<uint64>(
        [](const FCombatEventType& Row) 
        {
            return Row.Id; 
        }
    );

    return Diff;
}

int32 UCombatEventTable::Count() const
{
    return GetRowCountFromTable<FCombatEventType>(Data, TableName);
}

TArray<FCombatEventType> UCombatEventTable::Iter() const
{
    return GetAllRowsFromTable<FCombatEventType>(Data, TableName);
}
