// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/FanoutEntityTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UFanoutEntityTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FFanoutEntityType>>();

    TSharedPtr<FTableCache<FFanoutEntityType>> FanoutEntityTable = Data->GetOrAdd(TableName);
    FanoutEntityTable->AddUniqueConstraint<uint64>("id", [](const FFanoutEntityType& Row) -> const uint64& {
        return Row.Id; });

    Id = NewObject<UFanoutEntityIdUniqueIndex>(this);
    Id->SetCache(FanoutEntityTable);

    /***/
}

FTableAppliedDiff<FFanoutEntityType> UFanoutEntityTable::Update(TArray<FWithBsatn<FFanoutEntityType>> InsertsRef, TArray<FWithBsatn<FFanoutEntityType>> DeletesRef)
{
    FTableAppliedDiff<FFanoutEntityType> Diff = BaseUpdate<FFanoutEntityType>(InsertsRef, DeletesRef, Data, TableName);

    Diff.DeriveUpdatesByPrimaryKey<uint64>(
        [](const FFanoutEntityType& Row) 
        {
            return Row.Id; 
        }
    );

    return Diff;
}

int32 UFanoutEntityTable::Count() const
{
    return GetRowCountFromTable<FFanoutEntityType>(Data, TableName);
}

TArray<FFanoutEntityType> UFanoutEntityTable::Iter() const
{
    return GetAllRowsFromTable<FFanoutEntityType>(Data, TableName);
}
