// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/FanoutTickLogTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UFanoutTickLogTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FFanoutTickLogType>>();

    TSharedPtr<FTableCache<FFanoutTickLogType>> FanoutTickLogTable = Data->GetOrAdd(TableName);
    FanoutTickLogTable->AddUniqueConstraint<uint64>("id", [](const FFanoutTickLogType& Row) -> const uint64& {
        return Row.Id; });

    Id = NewObject<UFanoutTickLogIdUniqueIndex>(this);
    Id->SetCache(FanoutTickLogTable);

    /***/
}

FTableAppliedDiff<FFanoutTickLogType> UFanoutTickLogTable::Update(TArray<FWithBsatn<FFanoutTickLogType>> InsertsRef, TArray<FWithBsatn<FFanoutTickLogType>> DeletesRef)
{
    FTableAppliedDiff<FFanoutTickLogType> Diff = BaseUpdate<FFanoutTickLogType>(InsertsRef, DeletesRef, Data, TableName);

    Diff.DeriveUpdatesByPrimaryKey<uint64>(
        [](const FFanoutTickLogType& Row) 
        {
            return Row.Id; 
        }
    );

    return Diff;
}

int32 UFanoutTickLogTable::Count() const
{
    return GetRowCountFromTable<FFanoutTickLogType>(Data, TableName);
}

TArray<FFanoutTickLogType> UFanoutTickLogTable::Iter() const
{
    return GetAllRowsFromTable<FFanoutTickLogType>(Data, TableName);
}
