// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/PhysicsBodyTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UPhysicsBodyTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FPhysicsBodyType>>();

    TSharedPtr<FTableCache<FPhysicsBodyType>> PhysicsBodyTable = Data->GetOrAdd(TableName);
    PhysicsBodyTable->AddUniqueConstraint<uint64>("entity_id", [](const FPhysicsBodyType& Row) -> const uint64& {
        return Row.EntityId; });

    EntityId = NewObject<UPhysicsBodyEntityIdUniqueIndex>(this);
    EntityId->SetCache(PhysicsBodyTable);

    /***/
}

FTableAppliedDiff<FPhysicsBodyType> UPhysicsBodyTable::Update(TArray<FWithBsatn<FPhysicsBodyType>> InsertsRef, TArray<FWithBsatn<FPhysicsBodyType>> DeletesRef)
{
    FTableAppliedDiff<FPhysicsBodyType> Diff = BaseUpdate<FPhysicsBodyType>(InsertsRef, DeletesRef, Data, TableName);

    Diff.DeriveUpdatesByPrimaryKey<uint64>(
        [](const FPhysicsBodyType& Row) 
        {
            return Row.EntityId; 
        }
    );

    return Diff;
}

int32 UPhysicsBodyTable::Count() const
{
    return GetRowCountFromTable<FPhysicsBodyType>(Data, TableName);
}

TArray<FPhysicsBodyType> UPhysicsBodyTable::Iter() const
{
    return GetAllRowsFromTable<FPhysicsBodyType>(Data, TableName);
}
