// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/PlayerAccountTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UPlayerAccountTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FPlayerAccountType>>();

    TSharedPtr<FTableCache<FPlayerAccountType>> PlayerAccountTable = Data->GetOrAdd(TableName);
    PlayerAccountTable->AddUniqueConstraint<FSpacetimeDBIdentity>("identity", [](const FPlayerAccountType& Row) -> const FSpacetimeDBIdentity& {
        return Row.Identity; });

    Identity = NewObject<UPlayerAccountIdentityUniqueIndex>(this);
    Identity->SetCache(PlayerAccountTable);

    /***/
}

FTableAppliedDiff<FPlayerAccountType> UPlayerAccountTable::Update(TArray<FWithBsatn<FPlayerAccountType>> InsertsRef, TArray<FWithBsatn<FPlayerAccountType>> DeletesRef)
{
    FTableAppliedDiff<FPlayerAccountType> Diff = BaseUpdate<FPlayerAccountType>(InsertsRef, DeletesRef, Data, TableName);

    Diff.DeriveUpdatesByPrimaryKey<FSpacetimeDBIdentity>(
        [](const FPlayerAccountType& Row) 
        {
            return Row.Identity; 
        }
    );

    return Diff;
}

int32 UPlayerAccountTable::Count() const
{
    return GetRowCountFromTable<FPlayerAccountType>(Data, TableName);
}

TArray<FPlayerAccountType> UPlayerAccountTable::Iter() const
{
    return GetAllRowsFromTable<FPlayerAccountType>(Data, TableName);
}
