// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/StressResultTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UStressResultTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FStressResultType>>();

    TSharedPtr<FTableCache<FStressResultType>> StressResultTable = Data->GetOrAdd(TableName);
    StressResultTable->AddUniqueConstraint<uint64>("id", [](const FStressResultType& Row) -> const uint64& {
        return Row.Id; });

    Id = NewObject<UStressResultIdUniqueIndex>(this);
    Id->SetCache(StressResultTable);

    /***/
}

FTableAppliedDiff<FStressResultType> UStressResultTable::Update(TArray<FWithBsatn<FStressResultType>> InsertsRef, TArray<FWithBsatn<FStressResultType>> DeletesRef)
{
    FTableAppliedDiff<FStressResultType> Diff = BaseUpdate<FStressResultType>(InsertsRef, DeletesRef, Data, TableName);

    Diff.DeriveUpdatesByPrimaryKey<uint64>(
        [](const FStressResultType& Row) 
        {
            return Row.Id; 
        }
    );

    return Diff;
}

int32 UStressResultTable::Count() const
{
    return GetRowCountFromTable<FStressResultType>(Data, TableName);
}

TArray<FStressResultType> UStressResultTable::Iter() const
{
    return GetAllRowsFromTable<FStressResultType>(Data, TableName);
}
