// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/WorldEntityTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UWorldEntityTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FWorldEntityType>>();

    TSharedPtr<FTableCache<FWorldEntityType>> WorldEntityTable = Data->GetOrAdd(TableName);
    WorldEntityTable->AddUniqueConstraint<uint64>("id", [](const FWorldEntityType& Row) -> const uint64& {
        return Row.Id; });

    Id = NewObject<UWorldEntityIdUniqueIndex>(this);
    Id->SetCache(WorldEntityTable);

    /***/
}

FTableAppliedDiff<FWorldEntityType> UWorldEntityTable::Update(TArray<FWithBsatn<FWorldEntityType>> InsertsRef, TArray<FWithBsatn<FWorldEntityType>> DeletesRef)
{
    FTableAppliedDiff<FWorldEntityType> Diff = BaseUpdate<FWorldEntityType>(InsertsRef, DeletesRef, Data, TableName);

    Diff.DeriveUpdatesByPrimaryKey<uint64>(
        [](const FWorldEntityType& Row) 
        {
            return Row.Id; 
        }
    );

    return Diff;
}

int32 UWorldEntityTable::Count() const
{
    return GetRowCountFromTable<FWorldEntityType>(Data, TableName);
}

TArray<FWorldEntityType> UWorldEntityTable::Iter() const
{
    return GetAllRowsFromTable<FWorldEntityType>(Data, TableName);
}
