// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/ZonePopulationTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UZonePopulationTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FZonePopulationType>>();

    TSharedPtr<FTableCache<FZonePopulationType>> ZonePopulationTable = Data->GetOrAdd(TableName);
    ZonePopulationTable->AddUniqueConstraint<FString>("zone_id", [](const FZonePopulationType& Row) -> const FString& {
        return Row.ZoneId; });

    ZoneId = NewObject<UZonePopulationZoneIdUniqueIndex>(this);
    ZoneId->SetCache(ZonePopulationTable);

    /***/
}

FTableAppliedDiff<FZonePopulationType> UZonePopulationTable::Update(TArray<FWithBsatn<FZonePopulationType>> InsertsRef, TArray<FWithBsatn<FZonePopulationType>> DeletesRef)
{
    FTableAppliedDiff<FZonePopulationType> Diff = BaseUpdate<FZonePopulationType>(InsertsRef, DeletesRef, Data, TableName);

    Diff.DeriveUpdatesByPrimaryKey<FString>(
        [](const FZonePopulationType& Row) 
        {
            return Row.ZoneId; 
        }
    );

    return Diff;
}

int32 UZonePopulationTable::Count() const
{
    return GetRowCountFromTable<FZonePopulationType>(Data, TableName);
}

TArray<FZonePopulationType> UZonePopulationTable::Iter() const
{
    return GetAllRowsFromTable<FZonePopulationType>(Data, TableName);
}
