// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/ZoneServerTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UZoneServerTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FZoneServerType>>();

    TSharedPtr<FTableCache<FZoneServerType>> ZoneServerTable = Data->GetOrAdd(TableName);
    ZoneServerTable->AddUniqueConstraint<FString>("server_id", [](const FZoneServerType& Row) -> const FString& {
        return Row.ServerId; });

    ServerId = NewObject<UZoneServerServerIdUniqueIndex>(this);
    ServerId->SetCache(ZoneServerTable);

    /***/
}

FTableAppliedDiff<FZoneServerType> UZoneServerTable::Update(TArray<FWithBsatn<FZoneServerType>> InsertsRef, TArray<FWithBsatn<FZoneServerType>> DeletesRef)
{
    FTableAppliedDiff<FZoneServerType> Diff = BaseUpdate<FZoneServerType>(InsertsRef, DeletesRef, Data, TableName);

    Diff.DeriveUpdatesByPrimaryKey<FString>(
        [](const FZoneServerType& Row) 
        {
            return Row.ServerId; 
        }
    );

    return Diff;
}

int32 UZoneServerTable::Count() const
{
    return GetRowCountFromTable<FZoneServerType>(Data, TableName);
}

TArray<FZoneServerType> UZoneServerTable::Iter() const
{
    return GetAllRowsFromTable<FZoneServerType>(Data, TableName);
}
