// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AuthenticateWithEosArgs {
    pub eos_product_user_id: String,
    pub display_name: String,
    pub platform: String,
}

impl From<AuthenticateWithEosArgs> for super::Reducer {
    fn from(args: AuthenticateWithEosArgs) -> Self {
        Self::AuthenticateWithEos {
            eos_product_user_id: args.eos_product_user_id,
            display_name: args.display_name,
            platform: args.platform,
        }
    }
}

impl __sdk::InModule for AuthenticateWithEosArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `authenticate_with_eos`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait authenticate_with_eos {
    /// Request that the remote module invoke the reducer `authenticate_with_eos` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`authenticate_with_eos:authenticate_with_eos_then`] to run a callback after the reducer completes.
    fn authenticate_with_eos(
        &self,
        eos_product_user_id: String,
        display_name: String,
        platform: String,
    ) -> __sdk::Result<()> {
        self.authenticate_with_eos_then(eos_product_user_id, display_name, platform, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `authenticate_with_eos` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn authenticate_with_eos_then(
        &self,
        eos_product_user_id: String,
        display_name: String,
        platform: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl authenticate_with_eos for super::RemoteReducers {
    fn authenticate_with_eos_then(
        &self,
        eos_product_user_id: String,
        display_name: String,
        platform: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AuthenticateWithEosArgs {
                eos_product_user_id,
                display_name,
                platform,
            },
            callback,
        )
    }
}
