// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClearEntitiesArgs {}

impl From<ClearEntitiesArgs> for super::Reducer {
    fn from(args: ClearEntitiesArgs) -> Self {
        Self::ClearEntities
    }
}

impl __sdk::InModule for ClearEntitiesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `clear_entities`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait clear_entities {
    /// Request that the remote module invoke the reducer `clear_entities` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`clear_entities:clear_entities_then`] to run a callback after the reducer completes.
    fn clear_entities(&self) -> __sdk::Result<()> {
        self.clear_entities_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `clear_entities` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn clear_entities_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl clear_entities for super::RemoteReducers {
    fn clear_entities_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ClearEntitiesArgs {}, callback)
    }
}
