// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct FanoutStartArgs {
    pub interval_ms: u64,
}

impl From<FanoutStartArgs> for super::Reducer {
    fn from(args: FanoutStartArgs) -> Self {
        Self::FanoutStart {
            interval_ms: args.interval_ms,
        }
    }
}

impl __sdk::InModule for FanoutStartArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `fanout_start`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait fanout_start {
    /// Request that the remote module invoke the reducer `fanout_start` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`fanout_start:fanout_start_then`] to run a callback after the reducer completes.
    fn fanout_start(&self, interval_ms: u64) -> __sdk::Result<()> {
        self.fanout_start_then(interval_ms, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `fanout_start` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn fanout_start_then(
        &self,
        interval_ms: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl fanout_start for super::RemoteReducers {
    fn fanout_start_then(
        &self,
        interval_ms: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(FanoutStartArgs { interval_ms }, callback)
    }
}
