// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::fanout_entity_type::FanoutEntity;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `fanout_entity`.
///
/// Obtain a handle from the [`FanoutEntityTableAccess::fanout_entity`] method on [`super::RemoteTables`],
/// like `ctx.db.fanout_entity()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.fanout_entity().on_insert(...)`.
pub struct FanoutEntityTableHandle<'ctx> {
    imp: __sdk::TableHandle<FanoutEntity>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `fanout_entity`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FanoutEntityTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FanoutEntityTableHandle`], which mediates access to the table `fanout_entity`.
    fn fanout_entity(&self) -> FanoutEntityTableHandle<'_>;
}

impl FanoutEntityTableAccess for super::RemoteTables {
    fn fanout_entity(&self) -> FanoutEntityTableHandle<'_> {
        FanoutEntityTableHandle {
            imp: self.imp.get_table::<FanoutEntity>("fanout_entity"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FanoutEntityInsertCallbackId(__sdk::CallbackId);
pub struct FanoutEntityDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for FanoutEntityTableHandle<'ctx> {
    type Row = FanoutEntity;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FanoutEntity> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = FanoutEntityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FanoutEntityInsertCallbackId {
        FanoutEntityInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FanoutEntityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FanoutEntityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FanoutEntityDeleteCallbackId {
        FanoutEntityDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FanoutEntityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct FanoutEntityUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FanoutEntityTableHandle<'ctx> {
    type UpdateCallbackId = FanoutEntityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FanoutEntityUpdateCallbackId {
        FanoutEntityUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FanoutEntityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `fanout_entity`,
/// which allows point queries on the field of the same name
/// via the [`FanoutEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.fanout_entity().id().find(...)`.
pub struct FanoutEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<FanoutEntity, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> FanoutEntityTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `fanout_entity`.
    pub fn id(&self) -> FanoutEntityIdUnique<'ctx> {
        FanoutEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> FanoutEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<FanoutEntity> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<FanoutEntity>("fanout_entity");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<FanoutEntity>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<FanoutEntity>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `FanoutEntity`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait fanout_entityQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `FanoutEntity`.
    fn fanout_entity(&self) -> __sdk::__query_builder::Table<FanoutEntity>;
}

impl fanout_entityQueryTableAccess for __sdk::QueryTableAccessor {
    fn fanout_entity(&self) -> __sdk::__query_builder::Table<FanoutEntity> {
        __sdk::__query_builder::Table::new("fanout_entity")
    }
}
