// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct FanoutEntity {
    pub id: u64,
    pub pos_x: f64,
    pub pos_y: f64,
    pub pos_z: f64,
    pub vel_x: f64,
    pub vel_y: f64,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for FanoutEntity {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `FanoutEntity`.
///
/// Provides typed access to columns for query building.
pub struct FanoutEntityCols {
    pub id: __sdk::__query_builder::Col<FanoutEntity, u64>,
    pub pos_x: __sdk::__query_builder::Col<FanoutEntity, f64>,
    pub pos_y: __sdk::__query_builder::Col<FanoutEntity, f64>,
    pub pos_z: __sdk::__query_builder::Col<FanoutEntity, f64>,
    pub vel_x: __sdk::__query_builder::Col<FanoutEntity, f64>,
    pub vel_y: __sdk::__query_builder::Col<FanoutEntity, f64>,
    pub updated_at: __sdk::__query_builder::Col<FanoutEntity, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for FanoutEntity {
    type Cols = FanoutEntityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        FanoutEntityCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            pos_x: __sdk::__query_builder::Col::new(table_name, "pos_x"),
            pos_y: __sdk::__query_builder::Col::new(table_name, "pos_y"),
            pos_z: __sdk::__query_builder::Col::new(table_name, "pos_z"),
            vel_x: __sdk::__query_builder::Col::new(table_name, "vel_x"),
            vel_y: __sdk::__query_builder::Col::new(table_name, "vel_y"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `FanoutEntity`.
///
/// Provides typed access to indexed columns for query building.
pub struct FanoutEntityIxCols {
    pub id: __sdk::__query_builder::IxCol<FanoutEntity, u64>,
}

impl __sdk::__query_builder::HasIxCols for FanoutEntity {
    type IxCols = FanoutEntityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        FanoutEntityIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for FanoutEntity {}
