// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct FanoutStopArgs {}

impl From<FanoutStopArgs> for super::Reducer {
    fn from(args: FanoutStopArgs) -> Self {
        Self::FanoutStop
    }
}

impl __sdk::InModule for FanoutStopArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `fanout_stop`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait fanout_stop {
    /// Request that the remote module invoke the reducer `fanout_stop` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`fanout_stop:fanout_stop_then`] to run a callback after the reducer completes.
    fn fanout_stop(&self) -> __sdk::Result<()> {
        self.fanout_stop_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `fanout_stop` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn fanout_stop_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl fanout_stop for super::RemoteReducers {
    fn fanout_stop_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(FanoutStopArgs {}, callback)
    }
}
