// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.2 (commit bc4fcec6f33f607fb46f61ae66c479eecf5a6e74).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod authenticate_with_eos_reducer;
pub mod bench_batch_physics_reducer;
pub mod bench_burst_reducer;
pub mod bench_burst_update_reducer;
pub mod bench_complex_reducer;
pub mod bench_counter_table;
pub mod bench_counter_type;
pub mod bench_entity_table;
pub mod bench_entity_type;
pub mod bench_medium_reducer;
pub mod bench_memory_reducer;
pub mod bench_reset_reducer;
pub mod bench_seed_reducer;
pub mod bench_simple_reducer;
pub mod bench_start_tick_reducer;
pub mod bench_stop_tick_reducer;
pub mod bench_tick_log_table;
pub mod bench_tick_log_type;
pub mod body_update_type;
pub mod clear_entities_reducer;
pub mod create_player_reducer;
pub mod fanout_entity_table;
pub mod fanout_entity_type;
pub mod fanout_reset_reducer;
pub mod fanout_schedule_type;
pub mod fanout_seed_reducer;
pub mod fanout_start_reducer;
pub mod fanout_stop_reducer;
pub mod fanout_tick_log_table;
pub mod fanout_tick_log_type;
pub mod move_player_reducer;
pub mod physics_body_table;
pub mod physics_body_type;
pub mod physics_cleanup_reducer;
pub mod physics_reset_reducer;
pub mod physics_update_batch_reducer;
pub mod physics_update_reducer;
pub mod player_account_table;
pub mod player_account_type;
pub mod player_table;
pub mod player_type;
pub mod seed_entities_reducer;
pub mod spawn_projectile_reducer;
pub mod spawn_projectiles_batch_reducer;
pub mod stress_move_reducer;
pub mod stress_record_reducer;
pub mod stress_reset_reducer;
pub mod stress_result_table;
pub mod stress_result_type;
pub mod tick_schedule_type;
pub mod world_entity_table;
pub mod world_entity_type;

pub use authenticate_with_eos_reducer::authenticate_with_eos;
pub use bench_batch_physics_reducer::bench_batch_physics;
pub use bench_burst_reducer::bench_burst;
pub use bench_burst_update_reducer::bench_burst_update;
pub use bench_complex_reducer::bench_complex;
pub use bench_counter_table::*;
pub use bench_counter_type::BenchCounter;
pub use bench_entity_table::*;
pub use bench_entity_type::BenchEntity;
pub use bench_medium_reducer::bench_medium;
pub use bench_memory_reducer::bench_memory;
pub use bench_reset_reducer::bench_reset;
pub use bench_seed_reducer::bench_seed;
pub use bench_simple_reducer::bench_simple;
pub use bench_start_tick_reducer::bench_start_tick;
pub use bench_stop_tick_reducer::bench_stop_tick;
pub use bench_tick_log_table::*;
pub use bench_tick_log_type::BenchTickLog;
pub use body_update_type::BodyUpdate;
pub use clear_entities_reducer::clear_entities;
pub use create_player_reducer::create_player;
pub use fanout_entity_table::*;
pub use fanout_entity_type::FanoutEntity;
pub use fanout_reset_reducer::fanout_reset;
pub use fanout_schedule_type::FanoutSchedule;
pub use fanout_seed_reducer::fanout_seed;
pub use fanout_start_reducer::fanout_start;
pub use fanout_stop_reducer::fanout_stop;
pub use fanout_tick_log_table::*;
pub use fanout_tick_log_type::FanoutTickLog;
pub use move_player_reducer::move_player;
pub use physics_body_table::*;
pub use physics_body_type::PhysicsBody;
pub use physics_cleanup_reducer::physics_cleanup;
pub use physics_reset_reducer::physics_reset;
pub use physics_update_batch_reducer::physics_update_batch;
pub use physics_update_reducer::physics_update;
pub use player_account_table::*;
pub use player_account_type::PlayerAccount;
pub use player_table::*;
pub use player_type::Player;
pub use seed_entities_reducer::seed_entities;
pub use spawn_projectile_reducer::spawn_projectile;
pub use spawn_projectiles_batch_reducer::spawn_projectiles_batch;
pub use stress_move_reducer::stress_move;
pub use stress_record_reducer::stress_record;
pub use stress_reset_reducer::stress_reset;
pub use stress_result_table::*;
pub use stress_result_type::StressResult;
pub use tick_schedule_type::TickSchedule;
pub use world_entity_table::*;
pub use world_entity_type::WorldEntity;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    AuthenticateWithEos {
        eos_product_user_id: String,
        display_name: String,
        platform: String,
    },
    BenchBatchPhysics {
        body_count: u32,
        iterations: u32,
    },
    BenchBurst {
        count: u32,
    },
    BenchBurstUpdate {
        count: u32,
    },
    BenchComplex,
    BenchMedium,
    BenchMemory {
        megabytes: u32,
    },
    BenchReset,
    BenchSeed {
        count: u32,
    },
    BenchSimple,
    BenchStartTick {
        interval_ms: u64,
    },
    BenchStopTick,
    ClearEntities,
    CreatePlayer {
        display_name: String,
    },
    FanoutReset,
    FanoutSeed {
        count: u32,
    },
    FanoutStart {
        interval_ms: u64,
    },
    FanoutStop,
    MovePlayer {
        x: f64,
        y: f64,
        z: f64,
        yaw: f32,
        seq: u32,
    },
    PhysicsCleanup,
    PhysicsReset,
    PhysicsUpdate {
        entity_id: u64,
        pos_x: f64,
        pos_y: f64,
        pos_z: f64,
        vel_x: f64,
        vel_y: f64,
        vel_z: f64,
        active: bool,
    },
    PhysicsUpdateBatch {
        updates: Vec<BodyUpdate>,
    },
    SeedEntities {
        count: u32,
    },
    SpawnProjectile {
        pos_x: f64,
        pos_y: f64,
        pos_z: f64,
        vel_x: f64,
        vel_y: f64,
        vel_z: f64,
    },
    SpawnProjectilesBatch {
        count: u32,
    },
    StressMove {
        entity_id: u64,
        dx: f64,
        dy: f64,
    },
    StressRecord {
        client_count: u32,
        window_ms: u64,
    },
    StressReset,
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::AuthenticateWithEos { .. } => "authenticate_with_eos",
            Reducer::BenchBatchPhysics { .. } => "bench_batch_physics",
            Reducer::BenchBurst { .. } => "bench_burst",
            Reducer::BenchBurstUpdate { .. } => "bench_burst_update",
            Reducer::BenchComplex => "bench_complex",
            Reducer::BenchMedium => "bench_medium",
            Reducer::BenchMemory { .. } => "bench_memory",
            Reducer::BenchReset => "bench_reset",
            Reducer::BenchSeed { .. } => "bench_seed",
            Reducer::BenchSimple => "bench_simple",
            Reducer::BenchStartTick { .. } => "bench_start_tick",
            Reducer::BenchStopTick => "bench_stop_tick",
            Reducer::ClearEntities => "clear_entities",
            Reducer::CreatePlayer { .. } => "create_player",
            Reducer::FanoutReset => "fanout_reset",
            Reducer::FanoutSeed { .. } => "fanout_seed",
            Reducer::FanoutStart { .. } => "fanout_start",
            Reducer::FanoutStop => "fanout_stop",
            Reducer::MovePlayer { .. } => "move_player",
            Reducer::PhysicsCleanup => "physics_cleanup",
            Reducer::PhysicsReset => "physics_reset",
            Reducer::PhysicsUpdate { .. } => "physics_update",
            Reducer::PhysicsUpdateBatch { .. } => "physics_update_batch",
            Reducer::SeedEntities { .. } => "seed_entities",
            Reducer::SpawnProjectile { .. } => "spawn_projectile",
            Reducer::SpawnProjectilesBatch { .. } => "spawn_projectiles_batch",
            Reducer::StressMove { .. } => "stress_move",
            Reducer::StressRecord { .. } => "stress_record",
            Reducer::StressReset => "stress_reset",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::AuthenticateWithEos {
                eos_product_user_id,
                display_name,
                platform,
            } => __sats::bsatn::to_vec(&authenticate_with_eos_reducer::AuthenticateWithEosArgs {
                eos_product_user_id: eos_product_user_id.clone(),
                display_name: display_name.clone(),
                platform: platform.clone(),
            }),
            Reducer::BenchBatchPhysics {
                body_count,
                iterations,
            } => __sats::bsatn::to_vec(&bench_batch_physics_reducer::BenchBatchPhysicsArgs {
                body_count: body_count.clone(),
                iterations: iterations.clone(),
            }),
            Reducer::BenchBurst { count } => {
                __sats::bsatn::to_vec(&bench_burst_reducer::BenchBurstArgs {
                    count: count.clone(),
                })
            }
            Reducer::BenchBurstUpdate { count } => {
                __sats::bsatn::to_vec(&bench_burst_update_reducer::BenchBurstUpdateArgs {
                    count: count.clone(),
                })
            }
            Reducer::BenchComplex => {
                __sats::bsatn::to_vec(&bench_complex_reducer::BenchComplexArgs {})
            }
            Reducer::BenchMedium => {
                __sats::bsatn::to_vec(&bench_medium_reducer::BenchMediumArgs {})
            }
            Reducer::BenchMemory { megabytes } => {
                __sats::bsatn::to_vec(&bench_memory_reducer::BenchMemoryArgs {
                    megabytes: megabytes.clone(),
                })
            }
            Reducer::BenchReset => __sats::bsatn::to_vec(&bench_reset_reducer::BenchResetArgs {}),
            Reducer::BenchSeed { count } => {
                __sats::bsatn::to_vec(&bench_seed_reducer::BenchSeedArgs {
                    count: count.clone(),
                })
            }
            Reducer::BenchSimple => {
                __sats::bsatn::to_vec(&bench_simple_reducer::BenchSimpleArgs {})
            }
            Reducer::BenchStartTick { interval_ms } => {
                __sats::bsatn::to_vec(&bench_start_tick_reducer::BenchStartTickArgs {
                    interval_ms: interval_ms.clone(),
                })
            }
            Reducer::BenchStopTick => {
                __sats::bsatn::to_vec(&bench_stop_tick_reducer::BenchStopTickArgs {})
            }
            Reducer::ClearEntities => {
                __sats::bsatn::to_vec(&clear_entities_reducer::ClearEntitiesArgs {})
            }
            Reducer::CreatePlayer { display_name } => {
                __sats::bsatn::to_vec(&create_player_reducer::CreatePlayerArgs {
                    display_name: display_name.clone(),
                })
            }
            Reducer::FanoutReset => {
                __sats::bsatn::to_vec(&fanout_reset_reducer::FanoutResetArgs {})
            }
            Reducer::FanoutSeed { count } => {
                __sats::bsatn::to_vec(&fanout_seed_reducer::FanoutSeedArgs {
                    count: count.clone(),
                })
            }
            Reducer::FanoutStart { interval_ms } => {
                __sats::bsatn::to_vec(&fanout_start_reducer::FanoutStartArgs {
                    interval_ms: interval_ms.clone(),
                })
            }
            Reducer::FanoutStop => __sats::bsatn::to_vec(&fanout_stop_reducer::FanoutStopArgs {}),
            Reducer::MovePlayer { x, y, z, yaw, seq } => {
                __sats::bsatn::to_vec(&move_player_reducer::MovePlayerArgs {
                    x: x.clone(),
                    y: y.clone(),
                    z: z.clone(),
                    yaw: yaw.clone(),
                    seq: seq.clone(),
                })
            }
            Reducer::PhysicsCleanup => {
                __sats::bsatn::to_vec(&physics_cleanup_reducer::PhysicsCleanupArgs {})
            }
            Reducer::PhysicsReset => {
                __sats::bsatn::to_vec(&physics_reset_reducer::PhysicsResetArgs {})
            }
            Reducer::PhysicsUpdate {
                entity_id,
                pos_x,
                pos_y,
                pos_z,
                vel_x,
                vel_y,
                vel_z,
                active,
            } => __sats::bsatn::to_vec(&physics_update_reducer::PhysicsUpdateArgs {
                entity_id: entity_id.clone(),
                pos_x: pos_x.clone(),
                pos_y: pos_y.clone(),
                pos_z: pos_z.clone(),
                vel_x: vel_x.clone(),
                vel_y: vel_y.clone(),
                vel_z: vel_z.clone(),
                active: active.clone(),
            }),
            Reducer::PhysicsUpdateBatch { updates } => {
                __sats::bsatn::to_vec(&physics_update_batch_reducer::PhysicsUpdateBatchArgs {
                    updates: updates.clone(),
                })
            }
            Reducer::SeedEntities { count } => {
                __sats::bsatn::to_vec(&seed_entities_reducer::SeedEntitiesArgs {
                    count: count.clone(),
                })
            }
            Reducer::SpawnProjectile {
                pos_x,
                pos_y,
                pos_z,
                vel_x,
                vel_y,
                vel_z,
            } => __sats::bsatn::to_vec(&spawn_projectile_reducer::SpawnProjectileArgs {
                pos_x: pos_x.clone(),
                pos_y: pos_y.clone(),
                pos_z: pos_z.clone(),
                vel_x: vel_x.clone(),
                vel_y: vel_y.clone(),
                vel_z: vel_z.clone(),
            }),
            Reducer::SpawnProjectilesBatch { count } => __sats::bsatn::to_vec(
                &spawn_projectiles_batch_reducer::SpawnProjectilesBatchArgs {
                    count: count.clone(),
                },
            ),
            Reducer::StressMove { entity_id, dx, dy } => {
                __sats::bsatn::to_vec(&stress_move_reducer::StressMoveArgs {
                    entity_id: entity_id.clone(),
                    dx: dx.clone(),
                    dy: dy.clone(),
                })
            }
            Reducer::StressRecord {
                client_count,
                window_ms,
            } => __sats::bsatn::to_vec(&stress_record_reducer::StressRecordArgs {
                client_count: client_count.clone(),
                window_ms: window_ms.clone(),
            }),
            Reducer::StressReset => {
                __sats::bsatn::to_vec(&stress_reset_reducer::StressResetArgs {})
            }
            _ => unreachable!(),
        }
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    bench_counter: __sdk::TableUpdate<BenchCounter>,
    bench_entity: __sdk::TableUpdate<BenchEntity>,
    bench_tick_log: __sdk::TableUpdate<BenchTickLog>,
    fanout_entity: __sdk::TableUpdate<FanoutEntity>,
    fanout_tick_log: __sdk::TableUpdate<FanoutTickLog>,
    physics_body: __sdk::TableUpdate<PhysicsBody>,
    player: __sdk::TableUpdate<Player>,
    player_account: __sdk::TableUpdate<PlayerAccount>,
    stress_result: __sdk::TableUpdate<StressResult>,
    world_entity: __sdk::TableUpdate<WorldEntity>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "bench_counter" => db_update
                    .bench_counter
                    .append(bench_counter_table::parse_table_update(table_update)?),
                "bench_entity" => db_update
                    .bench_entity
                    .append(bench_entity_table::parse_table_update(table_update)?),
                "bench_tick_log" => db_update
                    .bench_tick_log
                    .append(bench_tick_log_table::parse_table_update(table_update)?),
                "fanout_entity" => db_update
                    .fanout_entity
                    .append(fanout_entity_table::parse_table_update(table_update)?),
                "fanout_tick_log" => db_update
                    .fanout_tick_log
                    .append(fanout_tick_log_table::parse_table_update(table_update)?),
                "physics_body" => db_update
                    .physics_body
                    .append(physics_body_table::parse_table_update(table_update)?),
                "player" => db_update
                    .player
                    .append(player_table::parse_table_update(table_update)?),
                "player_account" => db_update
                    .player_account
                    .append(player_account_table::parse_table_update(table_update)?),
                "stress_result" => db_update
                    .stress_result
                    .append(stress_result_table::parse_table_update(table_update)?),
                "world_entity" => db_update
                    .world_entity
                    .append(world_entity_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.bench_counter = cache
            .apply_diff_to_table::<BenchCounter>("bench_counter", &self.bench_counter)
            .with_updates_by_pk(|row| &row.id);
        diff.bench_entity = cache
            .apply_diff_to_table::<BenchEntity>("bench_entity", &self.bench_entity)
            .with_updates_by_pk(|row| &row.id);
        diff.bench_tick_log = cache
            .apply_diff_to_table::<BenchTickLog>("bench_tick_log", &self.bench_tick_log)
            .with_updates_by_pk(|row| &row.id);
        diff.fanout_entity = cache
            .apply_diff_to_table::<FanoutEntity>("fanout_entity", &self.fanout_entity)
            .with_updates_by_pk(|row| &row.id);
        diff.fanout_tick_log = cache
            .apply_diff_to_table::<FanoutTickLog>("fanout_tick_log", &self.fanout_tick_log)
            .with_updates_by_pk(|row| &row.id);
        diff.physics_body = cache
            .apply_diff_to_table::<PhysicsBody>("physics_body", &self.physics_body)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.player = cache
            .apply_diff_to_table::<Player>("player", &self.player)
            .with_updates_by_pk(|row| &row.identity);
        diff.player_account = cache
            .apply_diff_to_table::<PlayerAccount>("player_account", &self.player_account)
            .with_updates_by_pk(|row| &row.identity);
        diff.stress_result = cache
            .apply_diff_to_table::<StressResult>("stress_result", &self.stress_result)
            .with_updates_by_pk(|row| &row.id);
        diff.world_entity = cache
            .apply_diff_to_table::<WorldEntity>("world_entity", &self.world_entity)
            .with_updates_by_pk(|row| &row.id);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "bench_counter" => db_update
                    .bench_counter
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "bench_entity" => db_update
                    .bench_entity
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "bench_tick_log" => db_update
                    .bench_tick_log
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "fanout_entity" => db_update
                    .fanout_entity
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "fanout_tick_log" => db_update
                    .fanout_tick_log
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "physics_body" => db_update
                    .physics_body
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player" => db_update
                    .player
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player_account" => db_update
                    .player_account
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "stress_result" => db_update
                    .stress_result
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "world_entity" => db_update
                    .world_entity
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "bench_counter" => db_update
                    .bench_counter
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "bench_entity" => db_update
                    .bench_entity
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "bench_tick_log" => db_update
                    .bench_tick_log
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "fanout_entity" => db_update
                    .fanout_entity
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "fanout_tick_log" => db_update
                    .fanout_tick_log
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "physics_body" => db_update
                    .physics_body
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player" => db_update
                    .player
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player_account" => db_update
                    .player_account
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "stress_result" => db_update
                    .stress_result
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "world_entity" => db_update
                    .world_entity
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    bench_counter: __sdk::TableAppliedDiff<'r, BenchCounter>,
    bench_entity: __sdk::TableAppliedDiff<'r, BenchEntity>,
    bench_tick_log: __sdk::TableAppliedDiff<'r, BenchTickLog>,
    fanout_entity: __sdk::TableAppliedDiff<'r, FanoutEntity>,
    fanout_tick_log: __sdk::TableAppliedDiff<'r, FanoutTickLog>,
    physics_body: __sdk::TableAppliedDiff<'r, PhysicsBody>,
    player: __sdk::TableAppliedDiff<'r, Player>,
    player_account: __sdk::TableAppliedDiff<'r, PlayerAccount>,
    stress_result: __sdk::TableAppliedDiff<'r, StressResult>,
    world_entity: __sdk::TableAppliedDiff<'r, WorldEntity>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<BenchCounter>(
            "bench_counter",
            &self.bench_counter,
            event,
        );
        callbacks.invoke_table_row_callbacks::<BenchEntity>(
            "bench_entity",
            &self.bench_entity,
            event,
        );
        callbacks.invoke_table_row_callbacks::<BenchTickLog>(
            "bench_tick_log",
            &self.bench_tick_log,
            event,
        );
        callbacks.invoke_table_row_callbacks::<FanoutEntity>(
            "fanout_entity",
            &self.fanout_entity,
            event,
        );
        callbacks.invoke_table_row_callbacks::<FanoutTickLog>(
            "fanout_tick_log",
            &self.fanout_tick_log,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PhysicsBody>(
            "physics_body",
            &self.physics_body,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Player>("player", &self.player, event);
        callbacks.invoke_table_row_callbacks::<PlayerAccount>(
            "player_account",
            &self.player_account,
            event,
        );
        callbacks.invoke_table_row_callbacks::<StressResult>(
            "stress_result",
            &self.stress_result,
            event,
        );
        callbacks.invoke_table_row_callbacks::<WorldEntity>(
            "world_entity",
            &self.world_entity,
            event,
        );
    }
}

#[doc(hidden)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
/// - [`DbConnection::run_threaded`].
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
/// - [`DbConnection::advance_one_message_blocking`].
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        bench_counter_table::register_table(client_cache);
        bench_entity_table::register_table(client_cache);
        bench_tick_log_table::register_table(client_cache);
        fanout_entity_table::register_table(client_cache);
        fanout_tick_log_table::register_table(client_cache);
        physics_body_table::register_table(client_cache);
        player_table::register_table(client_cache);
        player_account_table::register_table(client_cache);
        stress_result_table::register_table(client_cache);
        world_entity_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "bench_counter",
        "bench_entity",
        "bench_tick_log",
        "fanout_entity",
        "fanout_tick_log",
        "physics_body",
        "player",
        "player_account",
        "stress_result",
        "world_entity",
    ];
}
