// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MovePlayerArgs {
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub yaw: f32,
    pub seq: u32,
}

impl From<MovePlayerArgs> for super::Reducer {
    fn from(args: MovePlayerArgs) -> Self {
        Self::MovePlayer {
            x: args.x,
            y: args.y,
            z: args.z,
            yaw: args.yaw,
            seq: args.seq,
        }
    }
}

impl __sdk::InModule for MovePlayerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `move_player`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait move_player {
    /// Request that the remote module invoke the reducer `move_player` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`move_player:move_player_then`] to run a callback after the reducer completes.
    fn move_player(&self, x: f64, y: f64, z: f64, yaw: f32, seq: u32) -> __sdk::Result<()> {
        self.move_player_then(x, y, z, yaw, seq, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `move_player` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn move_player_then(
        &self,
        x: f64,
        y: f64,
        z: f64,
        yaw: f32,
        seq: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl move_player for super::RemoteReducers {
    fn move_player_then(
        &self,
        x: f64,
        y: f64,
        z: f64,
        yaw: f32,
        seq: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(MovePlayerArgs { x, y, z, yaw, seq }, callback)
    }
}
