// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PhysicsBody {
    pub entity_id: u64,
    pub body_type: String,
    pub pos_x: f64,
    pub pos_y: f64,
    pub pos_z: f64,
    pub vel_x: f64,
    pub vel_y: f64,
    pub vel_z: f64,
    pub active: bool,
    pub owner: __sdk::Identity,
    pub last_update: __sdk::Timestamp,
}

impl __sdk::InModule for PhysicsBody {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PhysicsBody`.
///
/// Provides typed access to columns for query building.
pub struct PhysicsBodyCols {
    pub entity_id: __sdk::__query_builder::Col<PhysicsBody, u64>,
    pub body_type: __sdk::__query_builder::Col<PhysicsBody, String>,
    pub pos_x: __sdk::__query_builder::Col<PhysicsBody, f64>,
    pub pos_y: __sdk::__query_builder::Col<PhysicsBody, f64>,
    pub pos_z: __sdk::__query_builder::Col<PhysicsBody, f64>,
    pub vel_x: __sdk::__query_builder::Col<PhysicsBody, f64>,
    pub vel_y: __sdk::__query_builder::Col<PhysicsBody, f64>,
    pub vel_z: __sdk::__query_builder::Col<PhysicsBody, f64>,
    pub active: __sdk::__query_builder::Col<PhysicsBody, bool>,
    pub owner: __sdk::__query_builder::Col<PhysicsBody, __sdk::Identity>,
    pub last_update: __sdk::__query_builder::Col<PhysicsBody, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for PhysicsBody {
    type Cols = PhysicsBodyCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PhysicsBodyCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            body_type: __sdk::__query_builder::Col::new(table_name, "body_type"),
            pos_x: __sdk::__query_builder::Col::new(table_name, "pos_x"),
            pos_y: __sdk::__query_builder::Col::new(table_name, "pos_y"),
            pos_z: __sdk::__query_builder::Col::new(table_name, "pos_z"),
            vel_x: __sdk::__query_builder::Col::new(table_name, "vel_x"),
            vel_y: __sdk::__query_builder::Col::new(table_name, "vel_y"),
            vel_z: __sdk::__query_builder::Col::new(table_name, "vel_z"),
            active: __sdk::__query_builder::Col::new(table_name, "active"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            last_update: __sdk::__query_builder::Col::new(table_name, "last_update"),
        }
    }
}

/// Indexed column accessor struct for the table `PhysicsBody`.
///
/// Provides typed access to indexed columns for query building.
pub struct PhysicsBodyIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<PhysicsBody, u64>,
}

impl __sdk::__query_builder::HasIxCols for PhysicsBody {
    type IxCols = PhysicsBodyIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PhysicsBodyIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PhysicsBody {}
