// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PhysicsCleanupArgs {}

impl From<PhysicsCleanupArgs> for super::Reducer {
    fn from(args: PhysicsCleanupArgs) -> Self {
        Self::PhysicsCleanup
    }
}

impl __sdk::InModule for PhysicsCleanupArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `physics_cleanup`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait physics_cleanup {
    /// Request that the remote module invoke the reducer `physics_cleanup` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`physics_cleanup:physics_cleanup_then`] to run a callback after the reducer completes.
    fn physics_cleanup(&self) -> __sdk::Result<()> {
        self.physics_cleanup_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `physics_cleanup` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn physics_cleanup_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl physics_cleanup for super::RemoteReducers {
    fn physics_cleanup_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(PhysicsCleanupArgs {}, callback)
    }
}
