// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PhysicsUpdateArgs {
    pub entity_id: u64,
    pub pos_x: f64,
    pub pos_y: f64,
    pub pos_z: f64,
    pub vel_x: f64,
    pub vel_y: f64,
    pub vel_z: f64,
    pub active: bool,
}

impl From<PhysicsUpdateArgs> for super::Reducer {
    fn from(args: PhysicsUpdateArgs) -> Self {
        Self::PhysicsUpdate {
            entity_id: args.entity_id,
            pos_x: args.pos_x,
            pos_y: args.pos_y,
            pos_z: args.pos_z,
            vel_x: args.vel_x,
            vel_y: args.vel_y,
            vel_z: args.vel_z,
            active: args.active,
        }
    }
}

impl __sdk::InModule for PhysicsUpdateArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `physics_update`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait physics_update {
    /// Request that the remote module invoke the reducer `physics_update` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`physics_update:physics_update_then`] to run a callback after the reducer completes.
    fn physics_update(
        &self,
        entity_id: u64,
        pos_x: f64,
        pos_y: f64,
        pos_z: f64,
        vel_x: f64,
        vel_y: f64,
        vel_z: f64,
        active: bool,
    ) -> __sdk::Result<()> {
        self.physics_update_then(
            entity_id,
            pos_x,
            pos_y,
            pos_z,
            vel_x,
            vel_y,
            vel_z,
            active,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `physics_update` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn physics_update_then(
        &self,
        entity_id: u64,
        pos_x: f64,
        pos_y: f64,
        pos_z: f64,
        vel_x: f64,
        vel_y: f64,
        vel_z: f64,
        active: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl physics_update for super::RemoteReducers {
    fn physics_update_then(
        &self,
        entity_id: u64,
        pos_x: f64,
        pos_y: f64,
        pos_z: f64,
        vel_x: f64,
        vel_y: f64,
        vel_z: f64,
        active: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PhysicsUpdateArgs {
                entity_id,
                pos_x,
                pos_y,
                pos_z,
                vel_x,
                vel_y,
                vel_z,
                active,
            },
            callback,
        )
    }
}
