// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_account_type::PlayerAccount;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `player_account`.
///
/// Obtain a handle from the [`PlayerAccountTableAccess::player_account`] method on [`super::RemoteTables`],
/// like `ctx.db.player_account()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_account().on_insert(...)`.
pub struct PlayerAccountTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerAccount>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_account`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerAccountTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerAccountTableHandle`], which mediates access to the table `player_account`.
    fn player_account(&self) -> PlayerAccountTableHandle<'_>;
}

impl PlayerAccountTableAccess for super::RemoteTables {
    fn player_account(&self) -> PlayerAccountTableHandle<'_> {
        PlayerAccountTableHandle {
            imp: self.imp.get_table::<PlayerAccount>("player_account"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerAccountInsertCallbackId(__sdk::CallbackId);
pub struct PlayerAccountDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayerAccountTableHandle<'ctx> {
    type Row = PlayerAccount;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerAccount> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerAccountInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerAccountInsertCallbackId {
        PlayerAccountInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerAccountInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayerAccountDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerAccountDeleteCallbackId {
        PlayerAccountDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerAccountDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PlayerAccountUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayerAccountTableHandle<'ctx> {
    type UpdateCallbackId = PlayerAccountUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerAccountUpdateCallbackId {
        PlayerAccountUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerAccountUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `identity` unique index on the table `player_account`,
/// which allows point queries on the field of the same name
/// via the [`PlayerAccountIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_account().identity().find(...)`.
pub struct PlayerAccountIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayerAccount, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayerAccountTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `player_account`.
    pub fn identity(&self) -> PlayerAccountIdentityUnique<'ctx> {
        PlayerAccountIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayerAccountIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<PlayerAccount> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerAccount>("player_account");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PlayerAccount>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerAccount>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PlayerAccount`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait player_accountQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PlayerAccount`.
    fn player_account(&self) -> __sdk::__query_builder::Table<PlayerAccount>;
}

impl player_accountQueryTableAccess for __sdk::QueryTableAccessor {
    fn player_account(&self) -> __sdk::__query_builder::Table<PlayerAccount> {
        __sdk::__query_builder::Table::new("player_account")
    }
}
