// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Player {
    pub identity: __sdk::Identity,
    pub display_name: String,
    pub pos_x: f64,
    pub pos_y: f64,
    pub pos_z: f64,
    pub rot_yaw: f32,
    pub chunk_x: i32,
    pub chunk_y: i32,
    pub seq: u32,
    pub last_update: __sdk::Timestamp,
}

impl __sdk::InModule for Player {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Player`.
///
/// Provides typed access to columns for query building.
pub struct PlayerCols {
    pub identity: __sdk::__query_builder::Col<Player, __sdk::Identity>,
    pub display_name: __sdk::__query_builder::Col<Player, String>,
    pub pos_x: __sdk::__query_builder::Col<Player, f64>,
    pub pos_y: __sdk::__query_builder::Col<Player, f64>,
    pub pos_z: __sdk::__query_builder::Col<Player, f64>,
    pub rot_yaw: __sdk::__query_builder::Col<Player, f32>,
    pub chunk_x: __sdk::__query_builder::Col<Player, i32>,
    pub chunk_y: __sdk::__query_builder::Col<Player, i32>,
    pub seq: __sdk::__query_builder::Col<Player, u32>,
    pub last_update: __sdk::__query_builder::Col<Player, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Player {
    type Cols = PlayerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            pos_x: __sdk::__query_builder::Col::new(table_name, "pos_x"),
            pos_y: __sdk::__query_builder::Col::new(table_name, "pos_y"),
            pos_z: __sdk::__query_builder::Col::new(table_name, "pos_z"),
            rot_yaw: __sdk::__query_builder::Col::new(table_name, "rot_yaw"),
            chunk_x: __sdk::__query_builder::Col::new(table_name, "chunk_x"),
            chunk_y: __sdk::__query_builder::Col::new(table_name, "chunk_y"),
            seq: __sdk::__query_builder::Col::new(table_name, "seq"),
            last_update: __sdk::__query_builder::Col::new(table_name, "last_update"),
        }
    }
}

/// Indexed column accessor struct for the table `Player`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerIxCols {
    pub identity: __sdk::__query_builder::IxCol<Player, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Player {
    type IxCols = PlayerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Player {}
