// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerAccount {
    pub identity: __sdk::Identity,
    pub eos_product_user_id: String,
    pub display_name: String,
    pub platform: String,
    pub created_at: __sdk::Timestamp,
    pub last_login: __sdk::Timestamp,
}

impl __sdk::InModule for PlayerAccount {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerAccount`.
///
/// Provides typed access to columns for query building.
pub struct PlayerAccountCols {
    pub identity: __sdk::__query_builder::Col<PlayerAccount, __sdk::Identity>,
    pub eos_product_user_id: __sdk::__query_builder::Col<PlayerAccount, String>,
    pub display_name: __sdk::__query_builder::Col<PlayerAccount, String>,
    pub platform: __sdk::__query_builder::Col<PlayerAccount, String>,
    pub created_at: __sdk::__query_builder::Col<PlayerAccount, __sdk::Timestamp>,
    pub last_login: __sdk::__query_builder::Col<PlayerAccount, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for PlayerAccount {
    type Cols = PlayerAccountCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerAccountCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            eos_product_user_id: __sdk::__query_builder::Col::new(
                table_name,
                "eos_product_user_id",
            ),
            display_name: __sdk::__query_builder::Col::new(table_name, "display_name"),
            platform: __sdk::__query_builder::Col::new(table_name, "platform"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            last_login: __sdk::__query_builder::Col::new(table_name, "last_login"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerAccount`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerAccountIxCols {
    pub identity: __sdk::__query_builder::IxCol<PlayerAccount, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for PlayerAccount {
    type IxCols = PlayerAccountIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerAccountIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerAccount {}
