// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedEntitiesArgs {
    pub count: u32,
}

impl From<SeedEntitiesArgs> for super::Reducer {
    fn from(args: SeedEntitiesArgs) -> Self {
        Self::SeedEntities { count: args.count }
    }
}

impl __sdk::InModule for SeedEntitiesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_entities`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_entities {
    /// Request that the remote module invoke the reducer `seed_entities` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_entities:seed_entities_then`] to run a callback after the reducer completes.
    fn seed_entities(&self, count: u32) -> __sdk::Result<()> {
        self.seed_entities_then(count, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `seed_entities` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_entities_then(
        &self,
        count: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_entities for super::RemoteReducers {
    fn seed_entities_then(
        &self,
        count: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SeedEntitiesArgs { count }, callback)
    }
}
