// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SpawnProjectilesBatchArgs {
    pub count: u32,
}

impl From<SpawnProjectilesBatchArgs> for super::Reducer {
    fn from(args: SpawnProjectilesBatchArgs) -> Self {
        Self::SpawnProjectilesBatch { count: args.count }
    }
}

impl __sdk::InModule for SpawnProjectilesBatchArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `spawn_projectiles_batch`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait spawn_projectiles_batch {
    /// Request that the remote module invoke the reducer `spawn_projectiles_batch` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`spawn_projectiles_batch:spawn_projectiles_batch_then`] to run a callback after the reducer completes.
    fn spawn_projectiles_batch(&self, count: u32) -> __sdk::Result<()> {
        self.spawn_projectiles_batch_then(count, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `spawn_projectiles_batch` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn spawn_projectiles_batch_then(
        &self,
        count: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl spawn_projectiles_batch for super::RemoteReducers {
    fn spawn_projectiles_batch_then(
        &self,
        count: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SpawnProjectilesBatchArgs { count }, callback)
    }
}
