// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StressResetArgs {}

impl From<StressResetArgs> for super::Reducer {
    fn from(args: StressResetArgs) -> Self {
        Self::StressReset
    }
}

impl __sdk::InModule for StressResetArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `stress_reset`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait stress_reset {
    /// Request that the remote module invoke the reducer `stress_reset` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`stress_reset:stress_reset_then`] to run a callback after the reducer completes.
    fn stress_reset(&self) -> __sdk::Result<()> {
        self.stress_reset_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `stress_reset` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn stress_reset_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl stress_reset for super::RemoteReducers {
    fn stress_reset_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(StressResetArgs {}, callback)
    }
}
