// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StressRecordArgs {
    pub client_count: u32,
    pub window_ms: u64,
}

impl From<StressRecordArgs> for super::Reducer {
    fn from(args: StressRecordArgs) -> Self {
        Self::StressRecord {
            client_count: args.client_count,
            window_ms: args.window_ms,
        }
    }
}

impl __sdk::InModule for StressRecordArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `stress_record`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait stress_record {
    /// Request that the remote module invoke the reducer `stress_record` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`stress_record:stress_record_then`] to run a callback after the reducer completes.
    fn stress_record(&self, client_count: u32, window_ms: u64) -> __sdk::Result<()> {
        self.stress_record_then(client_count, window_ms, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `stress_record` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn stress_record_then(
        &self,
        client_count: u32,
        window_ms: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl stress_record for super::RemoteReducers {
    fn stress_record_then(
        &self,
        client_count: u32,
        window_ms: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            StressRecordArgs {
                client_count,
                window_ms,
            },
            callback,
        )
    }
}
