// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StressMoveArgs {
    pub entity_id: u64,
    pub dx: f64,
    pub dy: f64,
}

impl From<StressMoveArgs> for super::Reducer {
    fn from(args: StressMoveArgs) -> Self {
        Self::StressMove {
            entity_id: args.entity_id,
            dx: args.dx,
            dy: args.dy,
        }
    }
}

impl __sdk::InModule for StressMoveArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `stress_move`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait stress_move {
    /// Request that the remote module invoke the reducer `stress_move` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`stress_move:stress_move_then`] to run a callback after the reducer completes.
    fn stress_move(&self, entity_id: u64, dx: f64, dy: f64) -> __sdk::Result<()> {
        self.stress_move_then(entity_id, dx, dy, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `stress_move` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn stress_move_then(
        &self,
        entity_id: u64,
        dx: f64,
        dy: f64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl stress_move for super::RemoteReducers {
    fn stress_move_then(
        &self,
        entity_id: u64,
        dx: f64,
        dy: f64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(StressMoveArgs { entity_id, dx, dy }, callback)
    }
}
