// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::world_entity_type::WorldEntity;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `world_entity`.
///
/// Obtain a handle from the [`WorldEntityTableAccess::world_entity`] method on [`super::RemoteTables`],
/// like `ctx.db.world_entity()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_entity().on_insert(...)`.
pub struct WorldEntityTableHandle<'ctx> {
    imp: __sdk::TableHandle<WorldEntity>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `world_entity`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WorldEntityTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WorldEntityTableHandle`], which mediates access to the table `world_entity`.
    fn world_entity(&self) -> WorldEntityTableHandle<'_>;
}

impl WorldEntityTableAccess for super::RemoteTables {
    fn world_entity(&self) -> WorldEntityTableHandle<'_> {
        WorldEntityTableHandle {
            imp: self.imp.get_table::<WorldEntity>("world_entity"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WorldEntityInsertCallbackId(__sdk::CallbackId);
pub struct WorldEntityDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WorldEntityTableHandle<'ctx> {
    type Row = WorldEntity;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorldEntity> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WorldEntityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldEntityInsertCallbackId {
        WorldEntityInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorldEntityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WorldEntityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldEntityDeleteCallbackId {
        WorldEntityDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorldEntityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct WorldEntityUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WorldEntityTableHandle<'ctx> {
    type UpdateCallbackId = WorldEntityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorldEntityUpdateCallbackId {
        WorldEntityUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorldEntityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `world_entity`,
/// which allows point queries on the field of the same name
/// via the [`WorldEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_entity().id().find(...)`.
pub struct WorldEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WorldEntity, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WorldEntityTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `world_entity`.
    pub fn id(&self) -> WorldEntityIdUnique<'ctx> {
        WorldEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WorldEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<WorldEntity> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WorldEntity>("world_entity");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<WorldEntity>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WorldEntity>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `WorldEntity`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait world_entityQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `WorldEntity`.
    fn world_entity(&self) -> __sdk::__query_builder::Table<WorldEntity>;
}

impl world_entityQueryTableAccess for __sdk::QueryTableAccessor {
    fn world_entity(&self) -> __sdk::__query_builder::Table<WorldEntity> {
        __sdk::__query_builder::Table::new("world_entity")
    }
}
