// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WorldEntity {
    pub id: u64,
    pub entity_type: String,
    pub pos_x: f64,
    pub pos_y: f64,
    pub pos_z: f64,
    pub chunk_x: i32,
    pub chunk_y: i32,
    pub data: String,
}

impl __sdk::InModule for WorldEntity {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `WorldEntity`.
///
/// Provides typed access to columns for query building.
pub struct WorldEntityCols {
    pub id: __sdk::__query_builder::Col<WorldEntity, u64>,
    pub entity_type: __sdk::__query_builder::Col<WorldEntity, String>,
    pub pos_x: __sdk::__query_builder::Col<WorldEntity, f64>,
    pub pos_y: __sdk::__query_builder::Col<WorldEntity, f64>,
    pub pos_z: __sdk::__query_builder::Col<WorldEntity, f64>,
    pub chunk_x: __sdk::__query_builder::Col<WorldEntity, i32>,
    pub chunk_y: __sdk::__query_builder::Col<WorldEntity, i32>,
    pub data: __sdk::__query_builder::Col<WorldEntity, String>,
}

impl __sdk::__query_builder::HasCols for WorldEntity {
    type Cols = WorldEntityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WorldEntityCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            entity_type: __sdk::__query_builder::Col::new(table_name, "entity_type"),
            pos_x: __sdk::__query_builder::Col::new(table_name, "pos_x"),
            pos_y: __sdk::__query_builder::Col::new(table_name, "pos_y"),
            pos_z: __sdk::__query_builder::Col::new(table_name, "pos_z"),
            chunk_x: __sdk::__query_builder::Col::new(table_name, "chunk_x"),
            chunk_y: __sdk::__query_builder::Col::new(table_name, "chunk_y"),
            data: __sdk::__query_builder::Col::new(table_name, "data"),
        }
    }
}

/// Indexed column accessor struct for the table `WorldEntity`.
///
/// Provides typed access to indexed columns for query building.
pub struct WorldEntityIxCols {
    pub id: __sdk::__query_builder::IxCol<WorldEntity, u64>,
}

impl __sdk::__query_builder::HasIxCols for WorldEntity {
    type IxCols = WorldEntityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WorldEntityIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for WorldEntity {}
