// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "BodyUpdateType.g.generated.h"

USTRUCT(BlueprintType)
struct NYX_API FBodyUpdateType
{
    GENERATED_BODY()

    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 EntityId = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double PosX = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double PosY = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double PosZ = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double VelX = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double VelY = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double VelZ = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    bool Active = false;

    FORCEINLINE bool operator==(const FBodyUpdateType& Other) const
    {
        return EntityId == Other.EntityId && PosX == Other.PosX && PosY == Other.PosY && PosZ == Other.PosZ && VelX == Other.VelX && VelY == Other.VelY && VelZ == Other.VelZ && Active == Other.Active;
    }

    FORCEINLINE bool operator!=(const FBodyUpdateType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FBodyUpdateType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param BodyUpdateType The FBodyUpdateType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FBodyUpdateType& BodyUpdateType)
{
    uint32 Hash = GetTypeHash(BodyUpdateType.EntityId);
    Hash = HashCombine(Hash, GetTypeHash(BodyUpdateType.PosX));
    Hash = HashCombine(Hash, GetTypeHash(BodyUpdateType.PosY));
    Hash = HashCombine(Hash, GetTypeHash(BodyUpdateType.PosZ));
    Hash = HashCombine(Hash, GetTypeHash(BodyUpdateType.VelX));
    Hash = HashCombine(Hash, GetTypeHash(BodyUpdateType.VelY));
    Hash = HashCombine(Hash, GetTypeHash(BodyUpdateType.VelZ));
    Hash = HashCombine(Hash, GetTypeHash(BodyUpdateType.Active));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FBodyUpdateType);

    UE_SPACETIMEDB_STRUCT(FBodyUpdateType, EntityId, PosX, PosY, PosZ, VelX, VelY, VelZ, Active);
}
