// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "CharacterStatsType.g.generated.h"

USTRUCT(BlueprintType)
struct NYX_API FCharacterStatsType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBIdentity Identity;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString DisplayName;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Level = 0;

    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 Experience = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 MaxHp = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 CurrentHp = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 MaxMp = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 CurrentMp = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Strength = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Dexterity = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Intelligence = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Constitution = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 AttackPower = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Defense = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 MagicPower = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 MagicDefense = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double SavedPosX = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double SavedPosY = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double SavedPosZ = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString SavedZoneId;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBTimestamp LastSaved;

    FORCEINLINE bool operator==(const FCharacterStatsType& Other) const
    {
        return Identity == Other.Identity && DisplayName == Other.DisplayName && Level == Other.Level && Experience == Other.Experience && MaxHp == Other.MaxHp && CurrentHp == Other.CurrentHp && MaxMp == Other.MaxMp && CurrentMp == Other.CurrentMp && Strength == Other.Strength && Dexterity == Other.Dexterity && Intelligence == Other.Intelligence && Constitution == Other.Constitution && AttackPower == Other.AttackPower && Defense == Other.Defense && MagicPower == Other.MagicPower && MagicDefense == Other.MagicDefense && SavedPosX == Other.SavedPosX && SavedPosY == Other.SavedPosY && SavedPosZ == Other.SavedPosZ && SavedZoneId == Other.SavedZoneId && LastSaved == Other.LastSaved;
    }

    FORCEINLINE bool operator!=(const FCharacterStatsType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FCharacterStatsType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param CharacterStatsType The FCharacterStatsType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FCharacterStatsType& CharacterStatsType)
{
    uint32 Hash = GetTypeHash(CharacterStatsType.Identity);
    Hash = HashCombine(Hash, GetTypeHash(CharacterStatsType.DisplayName));
    Hash = HashCombine(Hash, GetTypeHash(CharacterStatsType.Level));
    Hash = HashCombine(Hash, GetTypeHash(CharacterStatsType.Experience));
    Hash = HashCombine(Hash, GetTypeHash(CharacterStatsType.MaxHp));
    Hash = HashCombine(Hash, GetTypeHash(CharacterStatsType.CurrentHp));
    Hash = HashCombine(Hash, GetTypeHash(CharacterStatsType.MaxMp));
    Hash = HashCombine(Hash, GetTypeHash(CharacterStatsType.CurrentMp));
    Hash = HashCombine(Hash, GetTypeHash(CharacterStatsType.Strength));
    Hash = HashCombine(Hash, GetTypeHash(CharacterStatsType.Dexterity));
    Hash = HashCombine(Hash, GetTypeHash(CharacterStatsType.Intelligence));
    Hash = HashCombine(Hash, GetTypeHash(CharacterStatsType.Constitution));
    Hash = HashCombine(Hash, GetTypeHash(CharacterStatsType.AttackPower));
    Hash = HashCombine(Hash, GetTypeHash(CharacterStatsType.Defense));
    Hash = HashCombine(Hash, GetTypeHash(CharacterStatsType.MagicPower));
    Hash = HashCombine(Hash, GetTypeHash(CharacterStatsType.MagicDefense));
    Hash = HashCombine(Hash, GetTypeHash(CharacterStatsType.SavedPosX));
    Hash = HashCombine(Hash, GetTypeHash(CharacterStatsType.SavedPosY));
    Hash = HashCombine(Hash, GetTypeHash(CharacterStatsType.SavedPosZ));
    Hash = HashCombine(Hash, GetTypeHash(CharacterStatsType.SavedZoneId));
    Hash = HashCombine(Hash, GetTypeHash(CharacterStatsType.LastSaved));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FCharacterStatsType);

    UE_SPACETIMEDB_STRUCT(FCharacterStatsType, Identity, DisplayName, Level, Experience, MaxHp, CurrentHp, MaxMp, CurrentMp, Strength, Dexterity, Intelligence, Constitution, AttackPower, Defense, MagicPower, MagicDefense, SavedPosX, SavedPosY, SavedPosZ, SavedZoneId, LastSaved);
}
