// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "CombatEventType.g.generated.h"

USTRUCT(BlueprintType)
struct NYX_API FCombatEventType
{
    GENERATED_BODY()

    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 Id = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBIdentity SourceId;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBIdentity TargetId;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 SkillId = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 Damage = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 ResultHp = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    bool IsKill = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString Flags;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBTimestamp Timestamp;

    FORCEINLINE bool operator==(const FCombatEventType& Other) const
    {
        return Id == Other.Id && SourceId == Other.SourceId && TargetId == Other.TargetId && SkillId == Other.SkillId && Damage == Other.Damage && ResultHp == Other.ResultHp && IsKill == Other.IsKill && Flags == Other.Flags && Timestamp == Other.Timestamp;
    }

    FORCEINLINE bool operator!=(const FCombatEventType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FCombatEventType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param CombatEventType The FCombatEventType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FCombatEventType& CombatEventType)
{
    uint32 Hash = GetTypeHash(CombatEventType.Id);
    Hash = HashCombine(Hash, GetTypeHash(CombatEventType.SourceId));
    Hash = HashCombine(Hash, GetTypeHash(CombatEventType.TargetId));
    Hash = HashCombine(Hash, GetTypeHash(CombatEventType.SkillId));
    Hash = HashCombine(Hash, GetTypeHash(CombatEventType.Damage));
    Hash = HashCombine(Hash, GetTypeHash(CombatEventType.ResultHp));
    Hash = HashCombine(Hash, GetTypeHash(CombatEventType.IsKill));
    Hash = HashCombine(Hash, GetTypeHash(CombatEventType.Flags));
    Hash = HashCombine(Hash, GetTypeHash(CombatEventType.Timestamp));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FCombatEventType);

    UE_SPACETIMEDB_STRUCT(FCombatEventType, Id, SourceId, TargetId, SkillId, Damage, ResultHp, IsKill, Flags, Timestamp);
}
