// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "FanoutScheduleType.g.generated.h"

USTRUCT(BlueprintType)
struct NYX_API FFanoutScheduleType
{
    GENERATED_BODY()

    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 ScheduledId = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBScheduleAt ScheduledAt;

    FORCEINLINE bool operator==(const FFanoutScheduleType& Other) const
    {
        return ScheduledId == Other.ScheduledId && ScheduledAt == Other.ScheduledAt;
    }

    FORCEINLINE bool operator!=(const FFanoutScheduleType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FFanoutScheduleType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param FanoutScheduleType The FFanoutScheduleType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FFanoutScheduleType& FanoutScheduleType)
{
    uint32 Hash = GetTypeHash(FanoutScheduleType.ScheduledId);
    Hash = HashCombine(Hash, GetTypeHash(FanoutScheduleType.ScheduledAt));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FFanoutScheduleType);

    UE_SPACETIMEDB_STRUCT(FFanoutScheduleType, ScheduledId, ScheduledAt);
}
