// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "FanoutEntityType.g.generated.h"

USTRUCT(BlueprintType)
struct NYX_API FFanoutEntityType
{
    GENERATED_BODY()

    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 Id = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double PosX = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double PosY = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double PosZ = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double VelX = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double VelY = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBTimestamp UpdatedAt;

    FORCEINLINE bool operator==(const FFanoutEntityType& Other) const
    {
        return Id == Other.Id && PosX == Other.PosX && PosY == Other.PosY && PosZ == Other.PosZ && VelX == Other.VelX && VelY == Other.VelY && UpdatedAt == Other.UpdatedAt;
    }

    FORCEINLINE bool operator!=(const FFanoutEntityType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FFanoutEntityType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param FanoutEntityType The FFanoutEntityType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FFanoutEntityType& FanoutEntityType)
{
    uint32 Hash = GetTypeHash(FanoutEntityType.Id);
    Hash = HashCombine(Hash, GetTypeHash(FanoutEntityType.PosX));
    Hash = HashCombine(Hash, GetTypeHash(FanoutEntityType.PosY));
    Hash = HashCombine(Hash, GetTypeHash(FanoutEntityType.PosZ));
    Hash = HashCombine(Hash, GetTypeHash(FanoutEntityType.VelX));
    Hash = HashCombine(Hash, GetTypeHash(FanoutEntityType.VelY));
    Hash = HashCombine(Hash, GetTypeHash(FanoutEntityType.UpdatedAt));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FFanoutEntityType);

    UE_SPACETIMEDB_STRUCT(FFanoutEntityType, Id, PosX, PosY, PosZ, VelX, VelY, UpdatedAt);
}
