// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "PhysicsBodyType.g.generated.h"

USTRUCT(BlueprintType)
struct NYX_API FPhysicsBodyType
{
    GENERATED_BODY()

    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 EntityId = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString BodyType;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double PosX = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double PosY = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double PosZ = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double VelX = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double VelY = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double VelZ = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    bool Active = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBIdentity Owner;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBTimestamp LastUpdate;

    FORCEINLINE bool operator==(const FPhysicsBodyType& Other) const
    {
        return EntityId == Other.EntityId && BodyType == Other.BodyType && PosX == Other.PosX && PosY == Other.PosY && PosZ == Other.PosZ && VelX == Other.VelX && VelY == Other.VelY && VelZ == Other.VelZ && Active == Other.Active && Owner == Other.Owner && LastUpdate == Other.LastUpdate;
    }

    FORCEINLINE bool operator!=(const FPhysicsBodyType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FPhysicsBodyType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param PhysicsBodyType The FPhysicsBodyType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FPhysicsBodyType& PhysicsBodyType)
{
    uint32 Hash = GetTypeHash(PhysicsBodyType.EntityId);
    Hash = HashCombine(Hash, GetTypeHash(PhysicsBodyType.BodyType));
    Hash = HashCombine(Hash, GetTypeHash(PhysicsBodyType.PosX));
    Hash = HashCombine(Hash, GetTypeHash(PhysicsBodyType.PosY));
    Hash = HashCombine(Hash, GetTypeHash(PhysicsBodyType.PosZ));
    Hash = HashCombine(Hash, GetTypeHash(PhysicsBodyType.VelX));
    Hash = HashCombine(Hash, GetTypeHash(PhysicsBodyType.VelY));
    Hash = HashCombine(Hash, GetTypeHash(PhysicsBodyType.VelZ));
    Hash = HashCombine(Hash, GetTypeHash(PhysicsBodyType.Active));
    Hash = HashCombine(Hash, GetTypeHash(PhysicsBodyType.Owner));
    Hash = HashCombine(Hash, GetTypeHash(PhysicsBodyType.LastUpdate));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FPhysicsBodyType);

    UE_SPACETIMEDB_STRUCT(FPhysicsBodyType, EntityId, BodyType, PosX, PosY, PosZ, VelX, VelY, VelZ, Active, Owner, LastUpdate);
}
