// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "PlayerAccountType.g.generated.h"

USTRUCT(BlueprintType)
struct NYX_API FPlayerAccountType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBIdentity Identity;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString EosProductUserId;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString DisplayName;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString Platform;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBTimestamp CreatedAt;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBTimestamp LastLogin;

    FORCEINLINE bool operator==(const FPlayerAccountType& Other) const
    {
        return Identity == Other.Identity && EosProductUserId == Other.EosProductUserId && DisplayName == Other.DisplayName && Platform == Other.Platform && CreatedAt == Other.CreatedAt && LastLogin == Other.LastLogin;
    }

    FORCEINLINE bool operator!=(const FPlayerAccountType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FPlayerAccountType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param PlayerAccountType The FPlayerAccountType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FPlayerAccountType& PlayerAccountType)
{
    uint32 Hash = GetTypeHash(PlayerAccountType.Identity);
    Hash = HashCombine(Hash, GetTypeHash(PlayerAccountType.EosProductUserId));
    Hash = HashCombine(Hash, GetTypeHash(PlayerAccountType.DisplayName));
    Hash = HashCombine(Hash, GetTypeHash(PlayerAccountType.Platform));
    Hash = HashCombine(Hash, GetTypeHash(PlayerAccountType.CreatedAt));
    Hash = HashCombine(Hash, GetTypeHash(PlayerAccountType.LastLogin));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FPlayerAccountType);

    UE_SPACETIMEDB_STRUCT(FPlayerAccountType, Identity, EosProductUserId, DisplayName, Platform, CreatedAt, LastLogin);
}
