// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "PlayerType.g.generated.h"

USTRUCT(BlueprintType)
struct NYX_API FPlayerType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBIdentity Identity;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString DisplayName;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double PosX = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double PosY = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double PosZ = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    float RotYaw = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBTimestamp LastUpdate;

    FORCEINLINE bool operator==(const FPlayerType& Other) const
    {
        return Identity == Other.Identity && DisplayName == Other.DisplayName && PosX == Other.PosX && PosY == Other.PosY && PosZ == Other.PosZ && RotYaw == Other.RotYaw && LastUpdate == Other.LastUpdate;
    }

    FORCEINLINE bool operator!=(const FPlayerType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FPlayerType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param PlayerType The FPlayerType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FPlayerType& PlayerType)
{
    uint32 Hash = GetTypeHash(PlayerType.Identity);
    Hash = HashCombine(Hash, GetTypeHash(PlayerType.DisplayName));
    Hash = HashCombine(Hash, GetTypeHash(PlayerType.PosX));
    Hash = HashCombine(Hash, GetTypeHash(PlayerType.PosY));
    Hash = HashCombine(Hash, GetTypeHash(PlayerType.PosZ));
    Hash = HashCombine(Hash, GetTypeHash(PlayerType.RotYaw));
    Hash = HashCombine(Hash, GetTypeHash(PlayerType.LastUpdate));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FPlayerType);

    UE_SPACETIMEDB_STRUCT(FPlayerType, Identity, DisplayName, PosX, PosY, PosZ, RotYaw, LastUpdate);
}
