// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "StressResultType.g.generated.h"

USTRUCT(BlueprintType)
struct NYX_API FStressResultType
{
    GENERATED_BODY()

    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 Id = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 ClientCount = 0;

    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 TotalCalls = 0;

    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 WindowMs = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBTimestamp RecordedAt;

    FORCEINLINE bool operator==(const FStressResultType& Other) const
    {
        return Id == Other.Id && ClientCount == Other.ClientCount && TotalCalls == Other.TotalCalls && WindowMs == Other.WindowMs && RecordedAt == Other.RecordedAt;
    }

    FORCEINLINE bool operator!=(const FStressResultType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FStressResultType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param StressResultType The FStressResultType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FStressResultType& StressResultType)
{
    uint32 Hash = GetTypeHash(StressResultType.Id);
    Hash = HashCombine(Hash, GetTypeHash(StressResultType.ClientCount));
    Hash = HashCombine(Hash, GetTypeHash(StressResultType.TotalCalls));
    Hash = HashCombine(Hash, GetTypeHash(StressResultType.WindowMs));
    Hash = HashCombine(Hash, GetTypeHash(StressResultType.RecordedAt));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FStressResultType);

    UE_SPACETIMEDB_STRUCT(FStressResultType, Id, ClientCount, TotalCalls, WindowMs, RecordedAt);
}
