// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "WorldEntityType.g.generated.h"

USTRUCT(BlueprintType)
struct NYX_API FWorldEntityType
{
    GENERATED_BODY()

    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 Id = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString EntityType;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double PosX = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double PosY = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double PosZ = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 ChunkX = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 ChunkY = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString Data;

    FORCEINLINE bool operator==(const FWorldEntityType& Other) const
    {
        return Id == Other.Id && EntityType == Other.EntityType && PosX == Other.PosX && PosY == Other.PosY && PosZ == Other.PosZ && ChunkX == Other.ChunkX && ChunkY == Other.ChunkY && Data == Other.Data;
    }

    FORCEINLINE bool operator!=(const FWorldEntityType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FWorldEntityType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param WorldEntityType The FWorldEntityType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FWorldEntityType& WorldEntityType)
{
    uint32 Hash = GetTypeHash(WorldEntityType.Id);
    Hash = HashCombine(Hash, GetTypeHash(WorldEntityType.EntityType));
    Hash = HashCombine(Hash, GetTypeHash(WorldEntityType.PosX));
    Hash = HashCombine(Hash, GetTypeHash(WorldEntityType.PosY));
    Hash = HashCombine(Hash, GetTypeHash(WorldEntityType.PosZ));
    Hash = HashCombine(Hash, GetTypeHash(WorldEntityType.ChunkX));
    Hash = HashCombine(Hash, GetTypeHash(WorldEntityType.ChunkY));
    Hash = HashCombine(Hash, GetTypeHash(WorldEntityType.Data));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FWorldEntityType);

    UE_SPACETIMEDB_STRUCT(FWorldEntityType, Id, EntityType, PosX, PosY, PosZ, ChunkX, ChunkY, Data);
}
