// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ZonePopulationType.g.generated.h"

USTRUCT(BlueprintType)
struct NYX_API FZonePopulationType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString ZoneId;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 TotalPlayers = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 ServerCount = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    bool NeedsScaleUp = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    bool NeedsScaleDown = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBTimestamp LastUpdated;

    FORCEINLINE bool operator==(const FZonePopulationType& Other) const
    {
        return ZoneId == Other.ZoneId && TotalPlayers == Other.TotalPlayers && ServerCount == Other.ServerCount && NeedsScaleUp == Other.NeedsScaleUp && NeedsScaleDown == Other.NeedsScaleDown && LastUpdated == Other.LastUpdated;
    }

    FORCEINLINE bool operator!=(const FZonePopulationType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FZonePopulationType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param ZonePopulationType The FZonePopulationType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FZonePopulationType& ZonePopulationType)
{
    uint32 Hash = GetTypeHash(ZonePopulationType.ZoneId);
    Hash = HashCombine(Hash, GetTypeHash(ZonePopulationType.TotalPlayers));
    Hash = HashCombine(Hash, GetTypeHash(ZonePopulationType.ServerCount));
    Hash = HashCombine(Hash, GetTypeHash(ZonePopulationType.NeedsScaleUp));
    Hash = HashCombine(Hash, GetTypeHash(ZonePopulationType.NeedsScaleDown));
    Hash = HashCombine(Hash, GetTypeHash(ZonePopulationType.LastUpdated));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FZonePopulationType);

    UE_SPACETIMEDB_STRUCT(FZonePopulationType, ZoneId, TotalPlayers, ServerCount, NeedsScaleUp, NeedsScaleDown, LastUpdated);
}
