// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ZoneServerType.g.generated.h"

USTRUCT(BlueprintType)
struct NYX_API FZoneServerType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString ServerId;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString ZoneId;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString ContainerIp;

    // NOTE: uint16 field not exposed to Blueprint due to non-blueprintable elements
    uint16 Port = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 EntityCount = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 MaxEntities = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString Status;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBTimestamp JoinedAt;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBTimestamp LastHeartbeat;

    FORCEINLINE bool operator==(const FZoneServerType& Other) const
    {
        return ServerId == Other.ServerId && ZoneId == Other.ZoneId && ContainerIp == Other.ContainerIp && Port == Other.Port && EntityCount == Other.EntityCount && MaxEntities == Other.MaxEntities && Status == Other.Status && JoinedAt == Other.JoinedAt && LastHeartbeat == Other.LastHeartbeat;
    }

    FORCEINLINE bool operator!=(const FZoneServerType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FZoneServerType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param ZoneServerType The FZoneServerType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FZoneServerType& ZoneServerType)
{
    uint32 Hash = GetTypeHash(ZoneServerType.ServerId);
    Hash = HashCombine(Hash, GetTypeHash(ZoneServerType.ZoneId));
    Hash = HashCombine(Hash, GetTypeHash(ZoneServerType.ContainerIp));
    Hash = HashCombine(Hash, GetTypeHash(ZoneServerType.Port));
    Hash = HashCombine(Hash, GetTypeHash(ZoneServerType.EntityCount));
    Hash = HashCombine(Hash, GetTypeHash(ZoneServerType.MaxEntities));
    Hash = HashCombine(Hash, GetTypeHash(ZoneServerType.Status));
    Hash = HashCombine(Hash, GetTypeHash(ZoneServerType.JoinedAt));
    Hash = HashCombine(Hash, GetTypeHash(ZoneServerType.LastHeartbeat));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FZoneServerType);

    UE_SPACETIMEDB_STRUCT(FZoneServerType, ServerId, ZoneId, ContainerIp, Port, EntityCount, MaxEntities, Status, JoinedAt, LastHeartbeat);
}
