// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/CharacterStatsType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "CharacterStatsTable.g.generated.h"

UCLASS(Blueprintable)
class NYX_API UCharacterStatsIdentityUniqueIndex : public UObject
{
    GENERATED_BODY()

private:
    // Declare an instance of your templated helper.
    // It's private because the UObject wrapper will expose its functionality.
    FUniqueIndexHelper<FCharacterStatsType, FSpacetimeDBIdentity, FTableCache<FCharacterStatsType>> IdentityIndexHelper;

public:
    UCharacterStatsIdentityUniqueIndex()
        // Initialize the helper with the specific unique index name
        : IdentityIndexHelper("identity") {
    }

    /**
     * Finds a CharacterStats by their unique identity.
     * @param Key The identity to search for.
     * @return The found FCharacterStatsType, or a default-constructed FCharacterStatsType if not found.
     */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|CharacterStatsIndex")
    FCharacterStatsType Find(FSpacetimeDBIdentity Key)
    {
        // Simply delegate the call to the internal helper
        return IdentityIndexHelper.FindUniqueIndex(Key);
    }

    // A public setter to provide the cache to the helper after construction
    // This is a common pattern when the cache might be created or provided by another system.
    void SetCache(TSharedPtr<const FTableCache<FCharacterStatsType>> InCharacterStatsCache)
    {
        IdentityIndexHelper.Cache = InCharacterStatsCache;
    }
};
/***/

UCLASS(BlueprintType)
class NYX_API UCharacterStatsTable : public URemoteTable
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly)
    UCharacterStatsIdentityUniqueIndex* Identity;

    void PostInitialize();

    /** Update function for character_stats table*/
    FTableAppliedDiff<FCharacterStatsType> Update(TArray<FWithBsatn<FCharacterStatsType>> InsertsRef, TArray<FWithBsatn<FCharacterStatsType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FCharacterStatsType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnCharacterStatsInsert,
        const FEventContext&, Context,
        const FCharacterStatsType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnCharacterStatsUpdate,
        const FEventContext&, Context,
        const FCharacterStatsType&, OldRow,
        const FCharacterStatsType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnCharacterStatsDelete,
        const FEventContext&, Context,
        const FCharacterStatsType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnCharacterStatsInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnCharacterStatsUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnCharacterStatsDelete OnDelete;

private:
    const FString TableName = TEXT("character_stats");

    TSharedPtr<UClientCache<FCharacterStatsType>> Data;
};
