// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/FanoutTickLogType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "FanoutTickLogTable.g.generated.h"

UCLASS(Blueprintable)
class NYX_API UFanoutTickLogIdUniqueIndex : public UObject
{
    GENERATED_BODY()

private:
    // Declare an instance of your templated helper.
    // It's private because the UObject wrapper will expose its functionality.
    FUniqueIndexHelper<FFanoutTickLogType, uint64, FTableCache<FFanoutTickLogType>> IdIndexHelper;

public:
    UFanoutTickLogIdUniqueIndex()
        // Initialize the helper with the specific unique index name
        : IdIndexHelper("id") {
    }

    /**
     * Finds a FanoutTickLog by their unique id.
     * @param Key The id to search for.
     * @return The found FFanoutTickLogType, or a default-constructed FFanoutTickLogType if not found.
     */
    // NOTE: Not exposed to Blueprint because uint64 types are not Blueprint-compatible
    FFanoutTickLogType Find(uint64 Key)
    {
        // Simply delegate the call to the internal helper
        return IdIndexHelper.FindUniqueIndex(Key);
    }

    // A public setter to provide the cache to the helper after construction
    // This is a common pattern when the cache might be created or provided by another system.
    void SetCache(TSharedPtr<const FTableCache<FFanoutTickLogType>> InFanoutTickLogCache)
    {
        IdIndexHelper.Cache = InFanoutTickLogCache;
    }
};
/***/

UCLASS(BlueprintType)
class NYX_API UFanoutTickLogTable : public URemoteTable
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly)
    UFanoutTickLogIdUniqueIndex* Id;

    void PostInitialize();

    /** Update function for fanout_tick_log table*/
    FTableAppliedDiff<FFanoutTickLogType> Update(TArray<FWithBsatn<FFanoutTickLogType>> InsertsRef, TArray<FWithBsatn<FFanoutTickLogType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FFanoutTickLogType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnFanoutTickLogInsert,
        const FEventContext&, Context,
        const FFanoutTickLogType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnFanoutTickLogUpdate,
        const FEventContext&, Context,
        const FFanoutTickLogType&, OldRow,
        const FFanoutTickLogType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnFanoutTickLogDelete,
        const FEventContext&, Context,
        const FFanoutTickLogType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnFanoutTickLogInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnFanoutTickLogUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnFanoutTickLogDelete OnDelete;

private:
    const FString TableName = TEXT("fanout_tick_log");

    TSharedPtr<UClientCache<FFanoutTickLogType>> Data;
};
