// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/FanoutEntityType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "FanoutEntityTable.g.generated.h"

UCLASS(Blueprintable)
class NYX_API UFanoutEntityIdUniqueIndex : public UObject
{
    GENERATED_BODY()

private:
    // Declare an instance of your templated helper.
    // It's private because the UObject wrapper will expose its functionality.
    FUniqueIndexHelper<FFanoutEntityType, uint64, FTableCache<FFanoutEntityType>> IdIndexHelper;

public:
    UFanoutEntityIdUniqueIndex()
        // Initialize the helper with the specific unique index name
        : IdIndexHelper("id") {
    }

    /**
     * Finds a FanoutEntity by their unique id.
     * @param Key The id to search for.
     * @return The found FFanoutEntityType, or a default-constructed FFanoutEntityType if not found.
     */
    // NOTE: Not exposed to Blueprint because uint64 types are not Blueprint-compatible
    FFanoutEntityType Find(uint64 Key)
    {
        // Simply delegate the call to the internal helper
        return IdIndexHelper.FindUniqueIndex(Key);
    }

    // A public setter to provide the cache to the helper after construction
    // This is a common pattern when the cache might be created or provided by another system.
    void SetCache(TSharedPtr<const FTableCache<FFanoutEntityType>> InFanoutEntityCache)
    {
        IdIndexHelper.Cache = InFanoutEntityCache;
    }
};
/***/

UCLASS(BlueprintType)
class NYX_API UFanoutEntityTable : public URemoteTable
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly)
    UFanoutEntityIdUniqueIndex* Id;

    void PostInitialize();

    /** Update function for fanout_entity table*/
    FTableAppliedDiff<FFanoutEntityType> Update(TArray<FWithBsatn<FFanoutEntityType>> InsertsRef, TArray<FWithBsatn<FFanoutEntityType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FFanoutEntityType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnFanoutEntityInsert,
        const FEventContext&, Context,
        const FFanoutEntityType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnFanoutEntityUpdate,
        const FEventContext&, Context,
        const FFanoutEntityType&, OldRow,
        const FFanoutEntityType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnFanoutEntityDelete,
        const FEventContext&, Context,
        const FFanoutEntityType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnFanoutEntityInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnFanoutEntityUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnFanoutEntityDelete OnDelete;

private:
    const FString TableName = TEXT("fanout_entity");

    TSharedPtr<UClientCache<FFanoutEntityType>> Data;
};
