// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/PhysicsBodyType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "PhysicsBodyTable.g.generated.h"

UCLASS(Blueprintable)
class NYX_API UPhysicsBodyEntityIdUniqueIndex : public UObject
{
    GENERATED_BODY()

private:
    // Declare an instance of your templated helper.
    // It's private because the UObject wrapper will expose its functionality.
    FUniqueIndexHelper<FPhysicsBodyType, uint64, FTableCache<FPhysicsBodyType>> EntityIdIndexHelper;

public:
    UPhysicsBodyEntityIdUniqueIndex()
        // Initialize the helper with the specific unique index name
        : EntityIdIndexHelper("entity_id") {
    }

    /**
     * Finds a PhysicsBody by their unique entityid.
     * @param Key The entityid to search for.
     * @return The found FPhysicsBodyType, or a default-constructed FPhysicsBodyType if not found.
     */
    // NOTE: Not exposed to Blueprint because uint64 types are not Blueprint-compatible
    FPhysicsBodyType Find(uint64 Key)
    {
        // Simply delegate the call to the internal helper
        return EntityIdIndexHelper.FindUniqueIndex(Key);
    }

    // A public setter to provide the cache to the helper after construction
    // This is a common pattern when the cache might be created or provided by another system.
    void SetCache(TSharedPtr<const FTableCache<FPhysicsBodyType>> InPhysicsBodyCache)
    {
        EntityIdIndexHelper.Cache = InPhysicsBodyCache;
    }
};
/***/

UCLASS(BlueprintType)
class NYX_API UPhysicsBodyTable : public URemoteTable
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly)
    UPhysicsBodyEntityIdUniqueIndex* EntityId;

    void PostInitialize();

    /** Update function for physics_body table*/
    FTableAppliedDiff<FPhysicsBodyType> Update(TArray<FWithBsatn<FPhysicsBodyType>> InsertsRef, TArray<FWithBsatn<FPhysicsBodyType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FPhysicsBodyType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnPhysicsBodyInsert,
        const FEventContext&, Context,
        const FPhysicsBodyType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnPhysicsBodyUpdate,
        const FEventContext&, Context,
        const FPhysicsBodyType&, OldRow,
        const FPhysicsBodyType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnPhysicsBodyDelete,
        const FEventContext&, Context,
        const FPhysicsBodyType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnPhysicsBodyInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnPhysicsBodyUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnPhysicsBodyDelete OnDelete;

private:
    const FString TableName = TEXT("physics_body");

    TSharedPtr<UClientCache<FPhysicsBodyType>> Data;
};
