// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/PlayerAccountType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "PlayerAccountTable.g.generated.h"

UCLASS(Blueprintable)
class NYX_API UPlayerAccountIdentityUniqueIndex : public UObject
{
    GENERATED_BODY()

private:
    // Declare an instance of your templated helper.
    // It's private because the UObject wrapper will expose its functionality.
    FUniqueIndexHelper<FPlayerAccountType, FSpacetimeDBIdentity, FTableCache<FPlayerAccountType>> IdentityIndexHelper;

public:
    UPlayerAccountIdentityUniqueIndex()
        // Initialize the helper with the specific unique index name
        : IdentityIndexHelper("identity") {
    }

    /**
     * Finds a PlayerAccount by their unique identity.
     * @param Key The identity to search for.
     * @return The found FPlayerAccountType, or a default-constructed FPlayerAccountType if not found.
     */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|PlayerAccountIndex")
    FPlayerAccountType Find(FSpacetimeDBIdentity Key)
    {
        // Simply delegate the call to the internal helper
        return IdentityIndexHelper.FindUniqueIndex(Key);
    }

    // A public setter to provide the cache to the helper after construction
    // This is a common pattern when the cache might be created or provided by another system.
    void SetCache(TSharedPtr<const FTableCache<FPlayerAccountType>> InPlayerAccountCache)
    {
        IdentityIndexHelper.Cache = InPlayerAccountCache;
    }
};
/***/

UCLASS(BlueprintType)
class NYX_API UPlayerAccountTable : public URemoteTable
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly)
    UPlayerAccountIdentityUniqueIndex* Identity;

    void PostInitialize();

    /** Update function for player_account table*/
    FTableAppliedDiff<FPlayerAccountType> Update(TArray<FWithBsatn<FPlayerAccountType>> InsertsRef, TArray<FWithBsatn<FPlayerAccountType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FPlayerAccountType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnPlayerAccountInsert,
        const FEventContext&, Context,
        const FPlayerAccountType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnPlayerAccountUpdate,
        const FEventContext&, Context,
        const FPlayerAccountType&, OldRow,
        const FPlayerAccountType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnPlayerAccountDelete,
        const FEventContext&, Context,
        const FPlayerAccountType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnPlayerAccountInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnPlayerAccountUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnPlayerAccountDelete OnDelete;

private:
    const FString TableName = TEXT("player_account");

    TSharedPtr<UClientCache<FPlayerAccountType>> Data;
};
