// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/WorldEntityType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "WorldEntityTable.g.generated.h"

UCLASS(Blueprintable)
class NYX_API UWorldEntityIdUniqueIndex : public UObject
{
    GENERATED_BODY()

private:
    // Declare an instance of your templated helper.
    // It's private because the UObject wrapper will expose its functionality.
    FUniqueIndexHelper<FWorldEntityType, uint64, FTableCache<FWorldEntityType>> IdIndexHelper;

public:
    UWorldEntityIdUniqueIndex()
        // Initialize the helper with the specific unique index name
        : IdIndexHelper("id") {
    }

    /**
     * Finds a WorldEntity by their unique id.
     * @param Key The id to search for.
     * @return The found FWorldEntityType, or a default-constructed FWorldEntityType if not found.
     */
    // NOTE: Not exposed to Blueprint because uint64 types are not Blueprint-compatible
    FWorldEntityType Find(uint64 Key)
    {
        // Simply delegate the call to the internal helper
        return IdIndexHelper.FindUniqueIndex(Key);
    }

    // A public setter to provide the cache to the helper after construction
    // This is a common pattern when the cache might be created or provided by another system.
    void SetCache(TSharedPtr<const FTableCache<FWorldEntityType>> InWorldEntityCache)
    {
        IdIndexHelper.Cache = InWorldEntityCache;
    }
};
/***/

UCLASS(BlueprintType)
class NYX_API UWorldEntityTable : public URemoteTable
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly)
    UWorldEntityIdUniqueIndex* Id;

    void PostInitialize();

    /** Update function for world_entity table*/
    FTableAppliedDiff<FWorldEntityType> Update(TArray<FWithBsatn<FWorldEntityType>> InsertsRef, TArray<FWithBsatn<FWorldEntityType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FWorldEntityType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnWorldEntityInsert,
        const FEventContext&, Context,
        const FWorldEntityType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnWorldEntityUpdate,
        const FEventContext&, Context,
        const FWorldEntityType&, OldRow,
        const FWorldEntityType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnWorldEntityDelete,
        const FEventContext&, Context,
        const FWorldEntityType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnWorldEntityInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnWorldEntityUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnWorldEntityDelete OnDelete;

private:
    const FString TableName = TEXT("world_entity");

    TSharedPtr<UClientCache<FWorldEntityType>> Data;
};
