// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/ZoneServerType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "ZoneServerTable.g.generated.h"

UCLASS(Blueprintable)
class NYX_API UZoneServerServerIdUniqueIndex : public UObject
{
    GENERATED_BODY()

private:
    // Declare an instance of your templated helper.
    // It's private because the UObject wrapper will expose its functionality.
    FUniqueIndexHelper<FZoneServerType, FString, FTableCache<FZoneServerType>> ServerIdIndexHelper;

public:
    UZoneServerServerIdUniqueIndex()
        // Initialize the helper with the specific unique index name
        : ServerIdIndexHelper("server_id") {
    }

    /**
     * Finds a ZoneServer by their unique serverid.
     * @param Key The serverid to search for.
     * @return The found FZoneServerType, or a default-constructed FZoneServerType if not found.
     */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|ZoneServerIndex")
    FZoneServerType Find(FString Key)
    {
        // Simply delegate the call to the internal helper
        return ServerIdIndexHelper.FindUniqueIndex(Key);
    }

    // A public setter to provide the cache to the helper after construction
    // This is a common pattern when the cache might be created or provided by another system.
    void SetCache(TSharedPtr<const FTableCache<FZoneServerType>> InZoneServerCache)
    {
        ServerIdIndexHelper.Cache = InZoneServerCache;
    }
};
/***/

UCLASS(BlueprintType)
class NYX_API UZoneServerTable : public URemoteTable
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly)
    UZoneServerServerIdUniqueIndex* ServerId;

    void PostInitialize();

    /** Update function for zone_server table*/
    FTableAppliedDiff<FZoneServerType> Update(TArray<FWithBsatn<FZoneServerType>> InsertsRef, TArray<FWithBsatn<FZoneServerType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FZoneServerType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnZoneServerInsert,
        const FEventContext&, Context,
        const FZoneServerType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnZoneServerUpdate,
        const FEventContext&, Context,
        const FZoneServerType&, OldRow,
        const FZoneServerType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnZoneServerDelete,
        const FEventContext&, Context,
        const FZoneServerType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnZoneServerInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnZoneServerUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnZoneServerDelete OnDelete;

private:
    const FString TableName = TEXT("zone_server");

    TSharedPtr<UClientCache<FZoneServerType>> Data;
};
