// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/ZonePopulationType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "ZonePopulationTable.g.generated.h"

UCLASS(Blueprintable)
class NYX_API UZonePopulationZoneIdUniqueIndex : public UObject
{
    GENERATED_BODY()

private:
    // Declare an instance of your templated helper.
    // It's private because the UObject wrapper will expose its functionality.
    FUniqueIndexHelper<FZonePopulationType, FString, FTableCache<FZonePopulationType>> ZoneIdIndexHelper;

public:
    UZonePopulationZoneIdUniqueIndex()
        // Initialize the helper with the specific unique index name
        : ZoneIdIndexHelper("zone_id") {
    }

    /**
     * Finds a ZonePopulation by their unique zoneid.
     * @param Key The zoneid to search for.
     * @return The found FZonePopulationType, or a default-constructed FZonePopulationType if not found.
     */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|ZonePopulationIndex")
    FZonePopulationType Find(FString Key)
    {
        // Simply delegate the call to the internal helper
        return ZoneIdIndexHelper.FindUniqueIndex(Key);
    }

    // A public setter to provide the cache to the helper after construction
    // This is a common pattern when the cache might be created or provided by another system.
    void SetCache(TSharedPtr<const FTableCache<FZonePopulationType>> InZonePopulationCache)
    {
        ZoneIdIndexHelper.Cache = InZonePopulationCache;
    }
};
/***/

UCLASS(BlueprintType)
class NYX_API UZonePopulationTable : public URemoteTable
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly)
    UZonePopulationZoneIdUniqueIndex* ZoneId;

    void PostInitialize();

    /** Update function for zone_population table*/
    FTableAppliedDiff<FZonePopulationType> Update(TArray<FWithBsatn<FZonePopulationType>> InsertsRef, TArray<FWithBsatn<FZonePopulationType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FZonePopulationType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnZonePopulationInsert,
        const FEventContext&, Context,
        const FZonePopulationType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnZonePopulationUpdate,
        const FEventContext&, Context,
        const FZonePopulationType&, OldRow,
        const FZonePopulationType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnZonePopulationDelete,
        const FEventContext&, Context,
        const FZonePopulationType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnZonePopulationInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnZonePopulationUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnZonePopulationDelete OnDelete;

private:
    const FString TableName = TEXT("zone_population");

    TSharedPtr<UClientCache<FZonePopulationType>> Data;
};
