// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.2 (commit bc4fcec6f33f607fb46f61ae66c479eecf5a6e74).

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Connection/Callback.h"
#include "Connection/DbConnectionBase.h"
#include "Connection/DbConnectionBuilder.h"
#include "Connection/SetReducerFlags.h"
#include "Connection/Subscription.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "ModuleBindings/Reducers/AuthenticateWithEos.g.h"
#include "ModuleBindings/Reducers/BenchBurst.g.h"
#include "ModuleBindings/Reducers/BenchBurstUpdate.g.h"
#include "ModuleBindings/Reducers/BenchComplex.g.h"
#include "ModuleBindings/Reducers/BenchMedium.g.h"
#include "ModuleBindings/Reducers/BenchMemory.g.h"
#include "ModuleBindings/Reducers/BenchReset.g.h"
#include "ModuleBindings/Reducers/BenchSeed.g.h"
#include "ModuleBindings/Reducers/BenchSimple.g.h"
#include "ModuleBindings/Reducers/BenchStartTick.g.h"
#include "ModuleBindings/Reducers/BenchStopTick.g.h"
#include "ModuleBindings/Reducers/ClearEntities.g.h"
#include "ModuleBindings/Reducers/CreatePlayer.g.h"
#include "ModuleBindings/Reducers/MovePlayer.g.h"
#include "ModuleBindings/Reducers/SeedEntities.g.h"
#include "Types/Builtins.h"
#include "SpacetimeDBClient.g.generated.h"

// Forward declarations
class UDbConnection;
class URemoteTables;
class URemoteReducers;
class URemoteProcedures;
class USubscriptionBuilder;
class USubscriptionHandle;

/** Forward declaration for tables */
class UBenchCounterTable;
class UBenchEntityTable;
class UBenchTickLogTable;
class UPlayerTable;
class UPlayerAccountTable;
class UWorldEntityTable;
/***/

// Delegates using the generated connection type. These wrap the base
// delegates defined in the SDK so that projects can work directly with
// UDbConnection without manual casting in user code.
DECLARE_DYNAMIC_DELEGATE_ThreeParams(
	FOnConnectDelegate,
	UDbConnection*, Connection,
	FSpacetimeDBIdentity, Identity,
	const FString&, Token);

DECLARE_DYNAMIC_DELEGATE_TwoParams(
	FOnDisconnectDelegate,
	UDbConnection*, Connection,
	const FString&, Error);


// Context classes for event handling

USTRUCT(BlueprintType)
struct NYX_API FContextBase
{
	GENERATED_BODY()

	FContextBase() : Db(nullptr), Reducers(nullptr), SetReducerFlags(nullptr), Procedures(nullptr), Conn(nullptr) {};
	FContextBase(UDbConnection* InConn);

	UPROPERTY(BlueprintReadOnly, Category = "SpacetimeDB")
	URemoteTables* Db;

	UPROPERTY(BlueprintReadOnly, Category = "SpacetimeDB")
	URemoteReducers* Reducers;

	UPROPERTY(BlueprintReadOnly, Category = "SpacetimeDB")
	USetReducerFlags* SetReducerFlags;

	UPROPERTY(BlueprintReadOnly, Category = "SpacetimeDB")
	URemoteProcedures* Procedures;

	bool IsActive() const;
	void Disconnect();
	bool TryGetIdentity(FSpacetimeDBIdentity& OutIdentity) const;
	FSpacetimeDBConnectionId GetConnectionId() const;
	USubscriptionBuilder* SubscriptionBuilder();

protected:
	UPROPERTY()
	UDbConnection* Conn;

};

UCLASS()
class NYX_API UContextBaseBpLib : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

private:
	UFUNCTION(BlueprintPure, Category="SpacetimeDB")
	static URemoteTables* GetDb(const FContextBase& Ctx) { return Ctx.Db; }

	UFUNCTION(BlueprintPure, Category="SpacetimeDB")
	static URemoteReducers* GetReducers(const FContextBase& Ctx) { return Ctx.Reducers; }

	UFUNCTION(BlueprintPure, Category="SpacetimeDB")
	static USetReducerFlags* GetSetReducerFlags(const FContextBase& Ctx) { return Ctx.SetReducerFlags; }

	static URemoteProcedures* GetProcedures(const FContextBase& Ctx) { return Ctx.Procedures; }

	UFUNCTION(BlueprintPure, Category="SpacetimeDB")
	static bool IsActive(const FContextBase& Ctx) { return Ctx.IsActive(); }
};

UENUM(BlueprintType, Category = "SpacetimeDB")
enum class EReducerTag : uint8
{
    AuthenticateWithEos,
    BenchBurst,
    BenchBurstUpdate,
    BenchComplex,
    BenchMedium,
    BenchMemory,
    BenchReset,
    BenchSeed,
    BenchSimple,
    BenchStartTick,
    BenchStopTick,
    ClearEntities,
    CreatePlayer,
    MovePlayer,
    SeedEntities
};

USTRUCT(BlueprintType)
struct NYX_API FReducer
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category = "SpacetimeDB")
    EReducerTag Tag = static_cast<EReducerTag>(0);

    TVariant<FAuthenticateWithEosArgs, FBenchBurstArgs, FBenchBurstUpdateArgs, FBenchComplexArgs, FBenchMediumArgs, FBenchMemoryArgs, FBenchResetArgs, FBenchSeedArgs, FBenchSimpleArgs, FBenchStartTickArgs, FBenchStopTickArgs, FClearEntitiesArgs, FCreatePlayerArgs, FMovePlayerArgs, FSeedEntitiesArgs> Data;

    // Optional metadata
    UPROPERTY(BlueprintReadOnly, Category = "SpacetimeDB")
    FString ReducerName;
    uint32 ReducerId = 0;
    uint32 RequestId = 0;

    static FReducer AuthenticateWithEos(const FAuthenticateWithEosArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::AuthenticateWithEos;
        Out.Data.Set<FAuthenticateWithEosArgs>(Value);
        Out.ReducerName = TEXT("authenticate_with_eos");
        return Out;
    }

    FORCEINLINE bool IsAuthenticateWithEos() const { return Tag == EReducerTag::AuthenticateWithEos; }
    FORCEINLINE FAuthenticateWithEosArgs GetAsAuthenticateWithEos() const
    {
        ensureMsgf(IsAuthenticateWithEos(), TEXT("Reducer does not hold AuthenticateWithEos!"));
        return Data.Get<FAuthenticateWithEosArgs>();
    }

    static FReducer BenchBurst(const FBenchBurstArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::BenchBurst;
        Out.Data.Set<FBenchBurstArgs>(Value);
        Out.ReducerName = TEXT("bench_burst");
        return Out;
    }

    FORCEINLINE bool IsBenchBurst() const { return Tag == EReducerTag::BenchBurst; }
    FORCEINLINE FBenchBurstArgs GetAsBenchBurst() const
    {
        ensureMsgf(IsBenchBurst(), TEXT("Reducer does not hold BenchBurst!"));
        return Data.Get<FBenchBurstArgs>();
    }

    static FReducer BenchBurstUpdate(const FBenchBurstUpdateArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::BenchBurstUpdate;
        Out.Data.Set<FBenchBurstUpdateArgs>(Value);
        Out.ReducerName = TEXT("bench_burst_update");
        return Out;
    }

    FORCEINLINE bool IsBenchBurstUpdate() const { return Tag == EReducerTag::BenchBurstUpdate; }
    FORCEINLINE FBenchBurstUpdateArgs GetAsBenchBurstUpdate() const
    {
        ensureMsgf(IsBenchBurstUpdate(), TEXT("Reducer does not hold BenchBurstUpdate!"));
        return Data.Get<FBenchBurstUpdateArgs>();
    }

    static FReducer BenchComplex(const FBenchComplexArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::BenchComplex;
        Out.Data.Set<FBenchComplexArgs>(Value);
        Out.ReducerName = TEXT("bench_complex");
        return Out;
    }

    FORCEINLINE bool IsBenchComplex() const { return Tag == EReducerTag::BenchComplex; }
    FORCEINLINE FBenchComplexArgs GetAsBenchComplex() const
    {
        ensureMsgf(IsBenchComplex(), TEXT("Reducer does not hold BenchComplex!"));
        return Data.Get<FBenchComplexArgs>();
    }

    static FReducer BenchMedium(const FBenchMediumArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::BenchMedium;
        Out.Data.Set<FBenchMediumArgs>(Value);
        Out.ReducerName = TEXT("bench_medium");
        return Out;
    }

    FORCEINLINE bool IsBenchMedium() const { return Tag == EReducerTag::BenchMedium; }
    FORCEINLINE FBenchMediumArgs GetAsBenchMedium() const
    {
        ensureMsgf(IsBenchMedium(), TEXT("Reducer does not hold BenchMedium!"));
        return Data.Get<FBenchMediumArgs>();
    }

    static FReducer BenchMemory(const FBenchMemoryArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::BenchMemory;
        Out.Data.Set<FBenchMemoryArgs>(Value);
        Out.ReducerName = TEXT("bench_memory");
        return Out;
    }

    FORCEINLINE bool IsBenchMemory() const { return Tag == EReducerTag::BenchMemory; }
    FORCEINLINE FBenchMemoryArgs GetAsBenchMemory() const
    {
        ensureMsgf(IsBenchMemory(), TEXT("Reducer does not hold BenchMemory!"));
        return Data.Get<FBenchMemoryArgs>();
    }

    static FReducer BenchReset(const FBenchResetArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::BenchReset;
        Out.Data.Set<FBenchResetArgs>(Value);
        Out.ReducerName = TEXT("bench_reset");
        return Out;
    }

    FORCEINLINE bool IsBenchReset() const { return Tag == EReducerTag::BenchReset; }
    FORCEINLINE FBenchResetArgs GetAsBenchReset() const
    {
        ensureMsgf(IsBenchReset(), TEXT("Reducer does not hold BenchReset!"));
        return Data.Get<FBenchResetArgs>();
    }

    static FReducer BenchSeed(const FBenchSeedArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::BenchSeed;
        Out.Data.Set<FBenchSeedArgs>(Value);
        Out.ReducerName = TEXT("bench_seed");
        return Out;
    }

    FORCEINLINE bool IsBenchSeed() const { return Tag == EReducerTag::BenchSeed; }
    FORCEINLINE FBenchSeedArgs GetAsBenchSeed() const
    {
        ensureMsgf(IsBenchSeed(), TEXT("Reducer does not hold BenchSeed!"));
        return Data.Get<FBenchSeedArgs>();
    }

    static FReducer BenchSimple(const FBenchSimpleArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::BenchSimple;
        Out.Data.Set<FBenchSimpleArgs>(Value);
        Out.ReducerName = TEXT("bench_simple");
        return Out;
    }

    FORCEINLINE bool IsBenchSimple() const { return Tag == EReducerTag::BenchSimple; }
    FORCEINLINE FBenchSimpleArgs GetAsBenchSimple() const
    {
        ensureMsgf(IsBenchSimple(), TEXT("Reducer does not hold BenchSimple!"));
        return Data.Get<FBenchSimpleArgs>();
    }

    static FReducer BenchStartTick(const FBenchStartTickArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::BenchStartTick;
        Out.Data.Set<FBenchStartTickArgs>(Value);
        Out.ReducerName = TEXT("bench_start_tick");
        return Out;
    }

    FORCEINLINE bool IsBenchStartTick() const { return Tag == EReducerTag::BenchStartTick; }
    FORCEINLINE FBenchStartTickArgs GetAsBenchStartTick() const
    {
        ensureMsgf(IsBenchStartTick(), TEXT("Reducer does not hold BenchStartTick!"));
        return Data.Get<FBenchStartTickArgs>();
    }

    static FReducer BenchStopTick(const FBenchStopTickArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::BenchStopTick;
        Out.Data.Set<FBenchStopTickArgs>(Value);
        Out.ReducerName = TEXT("bench_stop_tick");
        return Out;
    }

    FORCEINLINE bool IsBenchStopTick() const { return Tag == EReducerTag::BenchStopTick; }
    FORCEINLINE FBenchStopTickArgs GetAsBenchStopTick() const
    {
        ensureMsgf(IsBenchStopTick(), TEXT("Reducer does not hold BenchStopTick!"));
        return Data.Get<FBenchStopTickArgs>();
    }

    static FReducer ClearEntities(const FClearEntitiesArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::ClearEntities;
        Out.Data.Set<FClearEntitiesArgs>(Value);
        Out.ReducerName = TEXT("clear_entities");
        return Out;
    }

    FORCEINLINE bool IsClearEntities() const { return Tag == EReducerTag::ClearEntities; }
    FORCEINLINE FClearEntitiesArgs GetAsClearEntities() const
    {
        ensureMsgf(IsClearEntities(), TEXT("Reducer does not hold ClearEntities!"));
        return Data.Get<FClearEntitiesArgs>();
    }

    static FReducer CreatePlayer(const FCreatePlayerArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::CreatePlayer;
        Out.Data.Set<FCreatePlayerArgs>(Value);
        Out.ReducerName = TEXT("create_player");
        return Out;
    }

    FORCEINLINE bool IsCreatePlayer() const { return Tag == EReducerTag::CreatePlayer; }
    FORCEINLINE FCreatePlayerArgs GetAsCreatePlayer() const
    {
        ensureMsgf(IsCreatePlayer(), TEXT("Reducer does not hold CreatePlayer!"));
        return Data.Get<FCreatePlayerArgs>();
    }

    static FReducer MovePlayer(const FMovePlayerArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::MovePlayer;
        Out.Data.Set<FMovePlayerArgs>(Value);
        Out.ReducerName = TEXT("move_player");
        return Out;
    }

    FORCEINLINE bool IsMovePlayer() const { return Tag == EReducerTag::MovePlayer; }
    FORCEINLINE FMovePlayerArgs GetAsMovePlayer() const
    {
        ensureMsgf(IsMovePlayer(), TEXT("Reducer does not hold MovePlayer!"));
        return Data.Get<FMovePlayerArgs>();
    }

    static FReducer SeedEntities(const FSeedEntitiesArgs& Value)
    {
        FReducer Out;
        Out.Tag = EReducerTag::SeedEntities;
        Out.Data.Set<FSeedEntitiesArgs>(Value);
        Out.ReducerName = TEXT("seed_entities");
        return Out;
    }

    FORCEINLINE bool IsSeedEntities() const { return Tag == EReducerTag::SeedEntities; }
    FORCEINLINE FSeedEntitiesArgs GetAsSeedEntities() const
    {
        ensureMsgf(IsSeedEntities(), TEXT("Reducer does not hold SeedEntities!"));
        return Data.Get<FSeedEntitiesArgs>();
    }

    FORCEINLINE bool operator==(const FReducer& Other) const
    {
        if (Tag != Other.Tag || ReducerId != Other.ReducerId || RequestId != Other.RequestId || ReducerName != Other.ReducerName) return false;
        switch (Tag)
        {
        case EReducerTag::AuthenticateWithEos:
            return GetAsAuthenticateWithEos() == Other.GetAsAuthenticateWithEos();
        case EReducerTag::BenchBurst:
            return GetAsBenchBurst() == Other.GetAsBenchBurst();
        case EReducerTag::BenchBurstUpdate:
            return GetAsBenchBurstUpdate() == Other.GetAsBenchBurstUpdate();
        case EReducerTag::BenchComplex:
            return GetAsBenchComplex() == Other.GetAsBenchComplex();
        case EReducerTag::BenchMedium:
            return GetAsBenchMedium() == Other.GetAsBenchMedium();
        case EReducerTag::BenchMemory:
            return GetAsBenchMemory() == Other.GetAsBenchMemory();
        case EReducerTag::BenchReset:
            return GetAsBenchReset() == Other.GetAsBenchReset();
        case EReducerTag::BenchSeed:
            return GetAsBenchSeed() == Other.GetAsBenchSeed();
        case EReducerTag::BenchSimple:
            return GetAsBenchSimple() == Other.GetAsBenchSimple();
        case EReducerTag::BenchStartTick:
            return GetAsBenchStartTick() == Other.GetAsBenchStartTick();
        case EReducerTag::BenchStopTick:
            return GetAsBenchStopTick() == Other.GetAsBenchStopTick();
        case EReducerTag::ClearEntities:
            return GetAsClearEntities() == Other.GetAsClearEntities();
        case EReducerTag::CreatePlayer:
            return GetAsCreatePlayer() == Other.GetAsCreatePlayer();
        case EReducerTag::MovePlayer:
            return GetAsMovePlayer() == Other.GetAsMovePlayer();
        case EReducerTag::SeedEntities:
            return GetAsSeedEntities() == Other.GetAsSeedEntities();
        default: return false;
        }
    }
    FORCEINLINE bool operator!=(const FReducer& Other) const { return !(*this == Other); }
};

UCLASS()
class NYX_API UReducerBpLib : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()

private:

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer AuthenticateWithEos(const FAuthenticateWithEosArgs& Value) {
        return FReducer::AuthenticateWithEos(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsAuthenticateWithEos(const FReducer& Reducer) { return Reducer.IsAuthenticateWithEos(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FAuthenticateWithEosArgs GetAsAuthenticateWithEos(const FReducer& Reducer) {
        return Reducer.GetAsAuthenticateWithEos();
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer BenchBurst(const FBenchBurstArgs& Value) {
        return FReducer::BenchBurst(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsBenchBurst(const FReducer& Reducer) { return Reducer.IsBenchBurst(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FBenchBurstArgs GetAsBenchBurst(const FReducer& Reducer) {
        return Reducer.GetAsBenchBurst();
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer BenchBurstUpdate(const FBenchBurstUpdateArgs& Value) {
        return FReducer::BenchBurstUpdate(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsBenchBurstUpdate(const FReducer& Reducer) { return Reducer.IsBenchBurstUpdate(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FBenchBurstUpdateArgs GetAsBenchBurstUpdate(const FReducer& Reducer) {
        return Reducer.GetAsBenchBurstUpdate();
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer BenchComplex(const FBenchComplexArgs& Value) {
        return FReducer::BenchComplex(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsBenchComplex(const FReducer& Reducer) { return Reducer.IsBenchComplex(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FBenchComplexArgs GetAsBenchComplex(const FReducer& Reducer) {
        return Reducer.GetAsBenchComplex();
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer BenchMedium(const FBenchMediumArgs& Value) {
        return FReducer::BenchMedium(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsBenchMedium(const FReducer& Reducer) { return Reducer.IsBenchMedium(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FBenchMediumArgs GetAsBenchMedium(const FReducer& Reducer) {
        return Reducer.GetAsBenchMedium();
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer BenchMemory(const FBenchMemoryArgs& Value) {
        return FReducer::BenchMemory(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsBenchMemory(const FReducer& Reducer) { return Reducer.IsBenchMemory(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FBenchMemoryArgs GetAsBenchMemory(const FReducer& Reducer) {
        return Reducer.GetAsBenchMemory();
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer BenchReset(const FBenchResetArgs& Value) {
        return FReducer::BenchReset(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsBenchReset(const FReducer& Reducer) { return Reducer.IsBenchReset(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FBenchResetArgs GetAsBenchReset(const FReducer& Reducer) {
        return Reducer.GetAsBenchReset();
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer BenchSeed(const FBenchSeedArgs& Value) {
        return FReducer::BenchSeed(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsBenchSeed(const FReducer& Reducer) { return Reducer.IsBenchSeed(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FBenchSeedArgs GetAsBenchSeed(const FReducer& Reducer) {
        return Reducer.GetAsBenchSeed();
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer BenchSimple(const FBenchSimpleArgs& Value) {
        return FReducer::BenchSimple(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsBenchSimple(const FReducer& Reducer) { return Reducer.IsBenchSimple(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FBenchSimpleArgs GetAsBenchSimple(const FReducer& Reducer) {
        return Reducer.GetAsBenchSimple();
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer BenchStartTick(const FBenchStartTickArgs& Value) {
        return FReducer::BenchStartTick(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsBenchStartTick(const FReducer& Reducer) { return Reducer.IsBenchStartTick(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FBenchStartTickArgs GetAsBenchStartTick(const FReducer& Reducer) {
        return Reducer.GetAsBenchStartTick();
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer BenchStopTick(const FBenchStopTickArgs& Value) {
        return FReducer::BenchStopTick(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsBenchStopTick(const FReducer& Reducer) { return Reducer.IsBenchStopTick(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FBenchStopTickArgs GetAsBenchStopTick(const FReducer& Reducer) {
        return Reducer.GetAsBenchStopTick();
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer ClearEntities(const FClearEntitiesArgs& Value) {
        return FReducer::ClearEntities(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsClearEntities(const FReducer& Reducer) { return Reducer.IsClearEntities(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FClearEntitiesArgs GetAsClearEntities(const FReducer& Reducer) {
        return Reducer.GetAsClearEntities();
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer CreatePlayer(const FCreatePlayerArgs& Value) {
        return FReducer::CreatePlayer(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsCreatePlayer(const FReducer& Reducer) { return Reducer.IsCreatePlayer(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FCreatePlayerArgs GetAsCreatePlayer(const FReducer& Reducer) {
        return Reducer.GetAsCreatePlayer();
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer MovePlayer(const FMovePlayerArgs& Value) {
        return FReducer::MovePlayer(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsMovePlayer(const FReducer& Reducer) { return Reducer.IsMovePlayer(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FMovePlayerArgs GetAsMovePlayer(const FReducer& Reducer) {
        return Reducer.GetAsMovePlayer();
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|Reducer")
    static FReducer SeedEntities(const FSeedEntitiesArgs& Value) {
        return FReducer::SeedEntities(Value);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static bool IsSeedEntities(const FReducer& Reducer) { return Reducer.IsSeedEntities(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|Reducer")
    static FSeedEntitiesArgs GetAsSeedEntities(const FReducer& Reducer) {
        return Reducer.GetAsSeedEntities();
    }
};

/** Metadata describing a reducer run. */
USTRUCT(BlueprintType)
struct NYX_API FNyxReducerEvent
{
	GENERATED_BODY()

	/** Timestamp for when the reducer executed */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FSpacetimeDBTimestamp Timestamp;

	/** Result status of the reducer */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FSpacetimeDBStatus Status;

	/** Identity that initiated the call */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FSpacetimeDBIdentity CallerIdentity;

	/** Connection ID for the caller */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FSpacetimeDBConnectionId CallerConnectionId;

	/** Energy consumed while executing */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FEnergyQuantaType EnergyConsumed;

	/** Detailed call information */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FReducer Reducer;

	FORCEINLINE bool operator==(const FNyxReducerEvent& Other) const
	{
		return Status == Other.Status && Timestamp == Other.Timestamp && CallerIdentity == Other.CallerIdentity &&
			CallerConnectionId == Other.CallerConnectionId && EnergyConsumed == Other.EnergyConsumed &&
			Reducer == Other.Reducer;
	}

	FORCEINLINE bool operator!=(const FNyxReducerEvent& Other) const
	{
		return !(*this == Other);
	}
};

// No procedures defined in this module.
/** Metadata describing a procedure run. */
USTRUCT(BlueprintType)
struct NYX_API FNyxProcedureEvent
{
	GENERATED_BODY()

	/** Timestamp for when the procedure executed */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FSpacetimeDBTimestamp Timestamp;

	/** Result status of the procedure */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FSpacetimeDBProcedureStatus Status;

	/** Identity that initiated the call */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category="SpacetimeDB")
	FSpacetimeDBTimeDuration TotalHostExecutionDuration;

	FNyxProcedureEvent() {
	}
	FNyxProcedureEvent(FProcedureEvent Event) {
		Timestamp = Event.Timestamp;
		Status = FSpacetimeDBProcedureStatus::FromStatus(Event.Status);
		TotalHostExecutionDuration = Event.TotalHostExecutionDuration;
	}
	FORCEINLINE bool operator==(const FNyxProcedureEvent& Other) const
	{
		return Status == Other.Status && Timestamp == Other.Timestamp &&
			TotalHostExecutionDuration == Other.TotalHostExecutionDuration;
	}

	FORCEINLINE bool operator!=(const FNyxProcedureEvent& Other) const
	{
		return !(*this == Other);
	}
};

/** Represents event with variant message data. */
USTRUCT(BlueprintType)
struct NYX_API FNyxEvent
{
	GENERATED_BODY()

	/** Tagged union holding reducer call, unit events, or error string */
	TVariant<FReducer, FSpacetimeDBUnit, FString> MessageData;

	/** Type tag indicating what this event represents */
	UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
	ESpacetimeDBEventTag Tag = ESpacetimeDBEventTag::UnknownTransaction;

	/** === Static factory methods ===*/
	static FNyxEvent Reducer(const FReducer& Value)
	{
		FNyxEvent Obj;
		Obj.Tag = ESpacetimeDBEventTag::Reducer;
		Obj.MessageData.Set<FReducer>(Value);
		return Obj;
	}

	static FNyxEvent SubscribeApplied(const FSpacetimeDBUnit& Value)
	{
		FNyxEvent Obj;
		Obj.Tag = ESpacetimeDBEventTag::SubscribeApplied;
		Obj.MessageData.Set<FSpacetimeDBUnit>(Value);
		return Obj;
	}

	static FNyxEvent UnsubscribeApplied(const FSpacetimeDBUnit& Value)
	{
		FNyxEvent Obj;
		Obj.Tag = ESpacetimeDBEventTag::UnsubscribeApplied;
		Obj.MessageData.Set<FSpacetimeDBUnit>(Value);
		return Obj;
	}

	static FNyxEvent Disconnected(const FSpacetimeDBUnit& Value)
	{
		FNyxEvent Obj;
		Obj.Tag = ESpacetimeDBEventTag::Disconnected;
		Obj.MessageData.Set<FSpacetimeDBUnit>(Value);
		return Obj;
	}

	static FNyxEvent SubscribeError(const FString& Value)
	{
		FNyxEvent Obj;
		Obj.Tag = ESpacetimeDBEventTag::SubscribeError;
		Obj.MessageData.Set<FString>(Value);
		return Obj;
	}

	static FNyxEvent UnknownTransaction(const FSpacetimeDBUnit& Value)
	{
		FNyxEvent Obj;
		Obj.Tag = ESpacetimeDBEventTag::UnknownTransaction;
		Obj.MessageData.Set<FSpacetimeDBUnit>(Value);
		return Obj;
	}

	FORCEINLINE bool IsReducer() const { return Tag == ESpacetimeDBEventTag::Reducer; }
	FORCEINLINE FReducer GetAsReducer() const
	{
		ensureMsgf(IsReducer(), TEXT("MessageData does not hold Reducer!"));
		return MessageData.Get<FReducer>();
	}

	FORCEINLINE bool IsSubscribeApplied() const { return Tag == ESpacetimeDBEventTag::SubscribeApplied; }
	FORCEINLINE FSpacetimeDBUnit GetAsSubscribeApplied() const
	{
		ensureMsgf(IsSubscribeApplied(), TEXT("MessageData does not hold SubscribeApplied!"));
		return MessageData.Get<FSpacetimeDBUnit>();
	}

	FORCEINLINE bool IsUnsubscribeApplied() const { return Tag == ESpacetimeDBEventTag::UnsubscribeApplied; }
	FORCEINLINE FSpacetimeDBUnit GetAsUnsubscribeApplied() const
	{
		ensureMsgf(IsUnsubscribeApplied(), TEXT("MessageData does not hold UnsubscribeApplied!"));
		return MessageData.Get<FSpacetimeDBUnit>();
	}

	FORCEINLINE bool IsDisconnected() const { return Tag == ESpacetimeDBEventTag::Disconnected; }
	FORCEINLINE FSpacetimeDBUnit GetAsDisconnected() const
	{
		ensureMsgf(IsDisconnected(), TEXT("MessageData does not hold Disconnected!"));
		return MessageData.Get<FSpacetimeDBUnit>();
	}

	FORCEINLINE bool IsSubscribeError() const { return Tag == ESpacetimeDBEventTag::SubscribeError; }
	FORCEINLINE FString GetAsSubscribeError() const
	{
		ensureMsgf(IsSubscribeError(), TEXT("MessageData does not hold SubscribeError!"));
		return MessageData.Get<FString>();
	}

	FORCEINLINE bool IsUnknownTransaction() const { return Tag == ESpacetimeDBEventTag::UnknownTransaction; }
	FORCEINLINE FSpacetimeDBUnit GetAsUnknownTransaction() const
	{
		ensureMsgf(IsUnknownTransaction(), TEXT("MessageData does not hold UnknownTransaction!"));
		return MessageData.Get<FSpacetimeDBUnit>();
	}

	FORCEINLINE bool operator==(const FNyxEvent& Other) const
	{
		if (Tag != Other.Tag) return false;
		switch (Tag)
		{
		case ESpacetimeDBEventTag::Reducer: return GetAsReducer() == Other.GetAsReducer();
		case ESpacetimeDBEventTag::SubscribeApplied: return GetAsSubscribeApplied() == Other.GetAsSubscribeApplied();
		case ESpacetimeDBEventTag::UnsubscribeApplied: return GetAsUnsubscribeApplied() == Other.GetAsUnsubscribeApplied();
		case ESpacetimeDBEventTag::Disconnected: return GetAsDisconnected() == Other.GetAsDisconnected();
		case ESpacetimeDBEventTag::SubscribeError: return GetAsSubscribeError() == Other.GetAsSubscribeError();
		case ESpacetimeDBEventTag::UnknownTransaction: return GetAsUnknownTransaction() == Other.GetAsUnknownTransaction();
		default: return false;
		}
	}

	FORCEINLINE bool operator!=(const FNyxEvent& Other) const
	{
		return !(*this == Other);
	}
};

UCLASS()
class NYX_API UNyxEventBpLib : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()

private:
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|NyxEvent")
    static FNyxEvent Reducer(const FReducer& InValue)
    {
        return FNyxEvent::Reducer(InValue);
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|NyxEvent")
    static FNyxEvent SubscribeApplied(const FSpacetimeDBUnit& InValue)
    {
        return FNyxEvent::SubscribeApplied(InValue);
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|NyxEvent")
    static FNyxEvent UnsubscribeApplied(const FSpacetimeDBUnit& InValue)
    {
        return FNyxEvent::UnsubscribeApplied(InValue);
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|NyxEvent")
    static FNyxEvent Disconnected(const FSpacetimeDBUnit& InValue)
    {
        return FNyxEvent::Disconnected(InValue);
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|NyxEvent")
    static FNyxEvent SubscribeError(const FString& InValue)
    {
        return FNyxEvent::SubscribeError(InValue);
    }

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|NyxEvent")
    static FNyxEvent UnknownTransaction(const FSpacetimeDBUnit& InValue)
    {
        return FNyxEvent::UnknownTransaction(InValue);
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|NyxEvent")
    static bool IsReducer(const FNyxEvent& Event) { return Event.IsReducer(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|NyxEvent")
    static bool IsSubscribeApplied(const FNyxEvent& Event) { return Event.IsSubscribeApplied(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|NyxEvent")
    static bool IsUnsubscribeApplied(const FNyxEvent& Event) { return Event.IsUnsubscribeApplied(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|NyxEvent")
    static bool IsDisconnected(const FNyxEvent& Event) { return Event.IsDisconnected(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|NyxEvent")
    static bool IsSubscribeError(const FNyxEvent& Event) { return Event.IsSubscribeError(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|NyxEvent")
    static bool IsUnknownTransaction(const FNyxEvent& Event) { return Event.IsUnknownTransaction(); }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|NyxEvent")
    static FReducer GetAsReducer(const FNyxEvent& Event)
    {
        return Event.GetAsReducer();
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|NyxEvent")
    static FSpacetimeDBUnit GetAsSubscribeApplied(const FNyxEvent& Event)
    {
        return Event.GetAsSubscribeApplied();
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|NyxEvent")
    static FSpacetimeDBUnit GetAsUnsubscribeApplied(const FNyxEvent& Event)
    {
        return Event.GetAsUnsubscribeApplied();
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|NyxEvent")
    static FSpacetimeDBUnit GetAsDisconnected(const FNyxEvent& Event)
    {
        return Event.GetAsDisconnected();
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|NyxEvent")
    static FString GetAsSubscribeError(const FNyxEvent& Event)
    {
        return Event.GetAsSubscribeError();
    }

    UFUNCTION(BlueprintPure, Category = "SpacetimeDB|NyxEvent")
    static FSpacetimeDBUnit GetAsUnknownTransaction(const FNyxEvent& Event)
    {
        return Event.GetAsUnknownTransaction();
    }

};


USTRUCT(BlueprintType)
struct NYX_API FEventContext : public FContextBase
{
	GENERATED_BODY()

	FEventContext() = default;
	FEventContext(UDbConnection* InConn, const FNyxEvent& InEvent) : FContextBase(InConn), Event(InEvent) {}

	UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
	FNyxEvent Event;
};

USTRUCT(BlueprintType)
struct NYX_API FReducerEventContext : public FContextBase
{
	GENERATED_BODY()

	FReducerEventContext() = default;
	FReducerEventContext(UDbConnection* InConn, FNyxReducerEvent InEvent) : FContextBase(InConn), Event(InEvent) {}
	
	UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB") 
	FNyxReducerEvent Event;
};

USTRUCT(BlueprintType)
struct NYX_API FProcedureEventContext : public FContextBase
{
	GENERATED_BODY()

	FProcedureEventContext() = default;
	FProcedureEventContext(UDbConnection* InConn, FNyxProcedureEvent InEvent) : FContextBase(InConn), Event(InEvent) {}
	
	UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB") 
	FNyxProcedureEvent Event;
};

USTRUCT(BlueprintType)
struct NYX_API FErrorContext : public FContextBase
{
	GENERATED_BODY()

	FErrorContext() = default;
	FErrorContext(UDbConnection* InConn, const FString& InError) : FContextBase(InConn), Error(InError) {}

	UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
	FString Error;

};

USTRUCT(BlueprintType)
struct NYX_API FSubscriptionEventContext : public FContextBase
{
	GENERATED_BODY()

	FSubscriptionEventContext() = default;
	FSubscriptionEventContext(UDbConnection* InConn) : FContextBase(InConn) {}

};

DECLARE_DYNAMIC_DELEGATE_OneParam(
	FOnSubscriptionApplied,
	FSubscriptionEventContext, Context);

DECLARE_DYNAMIC_DELEGATE_OneParam(
	FOnSubscriptionError,
	FErrorContext, Context);

UCLASS(BlueprintType)
class NYX_API USetReducerFlags : public USetReducerFlagsBase
{
	GENERATED_BODY()

public:
	UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
	void AuthenticateWithEos(ECallReducerFlags Flag);
	UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
	void BenchBurst(ECallReducerFlags Flag);
	UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
	void BenchBurstUpdate(ECallReducerFlags Flag);
	UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
	void BenchComplex(ECallReducerFlags Flag);
	UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
	void BenchMedium(ECallReducerFlags Flag);
	UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
	void BenchMemory(ECallReducerFlags Flag);
	UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
	void BenchReset(ECallReducerFlags Flag);
	UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
	void BenchSeed(ECallReducerFlags Flag);
	UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
	void BenchSimple(ECallReducerFlags Flag);
	UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
	void BenchStartTick(ECallReducerFlags Flag);
	UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
	void BenchStopTick(ECallReducerFlags Flag);
	UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
	void ClearEntities(ECallReducerFlags Flag);
	UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
	void CreatePlayer(ECallReducerFlags Flag);
	UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
	void MovePlayer(ECallReducerFlags Flag);
	UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
	void SeedEntities(ECallReducerFlags Flag);

};

// RemoteTables class
UCLASS(BlueprintType)
class NYX_API URemoteTables : public UObject
{
    GENERATED_BODY()

public:
    void Initialize();

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    UBenchCounterTable* BenchCounter;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    UBenchEntityTable* BenchEntity;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    UBenchTickLogTable* BenchTickLog;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    UPlayerTable* Player;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    UPlayerAccountTable* PlayerAccount;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    UWorldEntityTable* WorldEntity;

};

// RemoteReducers class
UCLASS(BlueprintType)
class NYX_API URemoteReducers : public UObject
{
    GENERATED_BODY()

public:

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_FourParams(
        FAuthenticateWithEosHandler,
        const FReducerEventContext&, Context,
        const FString&, EosProductUserId,
        const FString&, DisplayName,
        const FString&, Platform
    );
    UPROPERTY(BlueprintAssignable, Category="SpacetimeDB")
    FAuthenticateWithEosHandler OnAuthenticateWithEos;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    void AuthenticateWithEos(const FString& EosProductUserId, const FString& DisplayName, const FString& Platform);

    bool InvokeAuthenticateWithEos(const FReducerEventContext& Context, const UAuthenticateWithEosReducer* Args);
    bool InvokeAuthenticateWithEosWithArgs(const FReducerEventContext& Context, const FAuthenticateWithEosArgs& Args);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(
        FBenchBurstHandler,
        const FReducerEventContext&, Context,
        uint32, Count
    );
    // NOTE: Not exposed to Blueprint because uint32 types are not Blueprint-compatible
    FBenchBurstHandler OnBenchBurst;

    // NOTE: Not exposed to Blueprint because uint32 types are not Blueprint-compatible
    void BenchBurst(const uint32 Count);

    bool InvokeBenchBurst(const FReducerEventContext& Context, const UBenchBurstReducer* Args);
    bool InvokeBenchBurstWithArgs(const FReducerEventContext& Context, const FBenchBurstArgs& Args);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(
        FBenchBurstUpdateHandler,
        const FReducerEventContext&, Context,
        uint32, Count
    );
    // NOTE: Not exposed to Blueprint because uint32 types are not Blueprint-compatible
    FBenchBurstUpdateHandler OnBenchBurstUpdate;

    // NOTE: Not exposed to Blueprint because uint32 types are not Blueprint-compatible
    void BenchBurstUpdate(const uint32 Count);

    bool InvokeBenchBurstUpdate(const FReducerEventContext& Context, const UBenchBurstUpdateReducer* Args);
    bool InvokeBenchBurstUpdateWithArgs(const FReducerEventContext& Context, const FBenchBurstUpdateArgs& Args);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(
        FBenchComplexHandler,
        const FReducerEventContext&, Context
    );
    UPROPERTY(BlueprintAssignable, Category="SpacetimeDB")
    FBenchComplexHandler OnBenchComplex;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    void BenchComplex();

    bool InvokeBenchComplex(const FReducerEventContext& Context, const UBenchComplexReducer* Args);
    bool InvokeBenchComplexWithArgs(const FReducerEventContext& Context, const FBenchComplexArgs& Args);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(
        FBenchMediumHandler,
        const FReducerEventContext&, Context
    );
    UPROPERTY(BlueprintAssignable, Category="SpacetimeDB")
    FBenchMediumHandler OnBenchMedium;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    void BenchMedium();

    bool InvokeBenchMedium(const FReducerEventContext& Context, const UBenchMediumReducer* Args);
    bool InvokeBenchMediumWithArgs(const FReducerEventContext& Context, const FBenchMediumArgs& Args);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(
        FBenchMemoryHandler,
        const FReducerEventContext&, Context,
        uint32, Megabytes
    );
    // NOTE: Not exposed to Blueprint because uint32 types are not Blueprint-compatible
    FBenchMemoryHandler OnBenchMemory;

    // NOTE: Not exposed to Blueprint because uint32 types are not Blueprint-compatible
    void BenchMemory(const uint32 Megabytes);

    bool InvokeBenchMemory(const FReducerEventContext& Context, const UBenchMemoryReducer* Args);
    bool InvokeBenchMemoryWithArgs(const FReducerEventContext& Context, const FBenchMemoryArgs& Args);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(
        FBenchResetHandler,
        const FReducerEventContext&, Context
    );
    UPROPERTY(BlueprintAssignable, Category="SpacetimeDB")
    FBenchResetHandler OnBenchReset;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    void BenchReset();

    bool InvokeBenchReset(const FReducerEventContext& Context, const UBenchResetReducer* Args);
    bool InvokeBenchResetWithArgs(const FReducerEventContext& Context, const FBenchResetArgs& Args);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(
        FBenchSeedHandler,
        const FReducerEventContext&, Context,
        uint32, Count
    );
    // NOTE: Not exposed to Blueprint because uint32 types are not Blueprint-compatible
    FBenchSeedHandler OnBenchSeed;

    // NOTE: Not exposed to Blueprint because uint32 types are not Blueprint-compatible
    void BenchSeed(const uint32 Count);

    bool InvokeBenchSeed(const FReducerEventContext& Context, const UBenchSeedReducer* Args);
    bool InvokeBenchSeedWithArgs(const FReducerEventContext& Context, const FBenchSeedArgs& Args);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(
        FBenchSimpleHandler,
        const FReducerEventContext&, Context
    );
    UPROPERTY(BlueprintAssignable, Category="SpacetimeDB")
    FBenchSimpleHandler OnBenchSimple;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    void BenchSimple();

    bool InvokeBenchSimple(const FReducerEventContext& Context, const UBenchSimpleReducer* Args);
    bool InvokeBenchSimpleWithArgs(const FReducerEventContext& Context, const FBenchSimpleArgs& Args);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(
        FBenchStartTickHandler,
        const FReducerEventContext&, Context,
        uint64, IntervalMs
    );
    // NOTE: Not exposed to Blueprint because uint64 types are not Blueprint-compatible
    FBenchStartTickHandler OnBenchStartTick;

    // NOTE: Not exposed to Blueprint because uint64 types are not Blueprint-compatible
    void BenchStartTick(const uint64 IntervalMs);

    bool InvokeBenchStartTick(const FReducerEventContext& Context, const UBenchStartTickReducer* Args);
    bool InvokeBenchStartTickWithArgs(const FReducerEventContext& Context, const FBenchStartTickArgs& Args);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(
        FBenchStopTickHandler,
        const FReducerEventContext&, Context
    );
    UPROPERTY(BlueprintAssignable, Category="SpacetimeDB")
    FBenchStopTickHandler OnBenchStopTick;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    void BenchStopTick();

    bool InvokeBenchStopTick(const FReducerEventContext& Context, const UBenchStopTickReducer* Args);
    bool InvokeBenchStopTickWithArgs(const FReducerEventContext& Context, const FBenchStopTickArgs& Args);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(
        FClearEntitiesHandler,
        const FReducerEventContext&, Context
    );
    UPROPERTY(BlueprintAssignable, Category="SpacetimeDB")
    FClearEntitiesHandler OnClearEntities;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    void ClearEntities();

    bool InvokeClearEntities(const FReducerEventContext& Context, const UClearEntitiesReducer* Args);
    bool InvokeClearEntitiesWithArgs(const FReducerEventContext& Context, const FClearEntitiesArgs& Args);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(
        FCreatePlayerHandler,
        const FReducerEventContext&, Context,
        const FString&, DisplayName
    );
    UPROPERTY(BlueprintAssignable, Category="SpacetimeDB")
    FCreatePlayerHandler OnCreatePlayer;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    void CreatePlayer(const FString& DisplayName);

    bool InvokeCreatePlayer(const FReducerEventContext& Context, const UCreatePlayerReducer* Args);
    bool InvokeCreatePlayerWithArgs(const FReducerEventContext& Context, const FCreatePlayerArgs& Args);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_SixParams(
        FMovePlayerHandler,
        const FReducerEventContext&, Context,
        double, X,
        double, Y,
        double, Z,
        float, Yaw,
        uint32, Seq
    );
    // NOTE: Not exposed to Blueprint because uint32 types are not Blueprint-compatible
    FMovePlayerHandler OnMovePlayer;

    // NOTE: Not exposed to Blueprint because uint32 types are not Blueprint-compatible
    void MovePlayer(const double X, const double Y, const double Z, const float Yaw, const uint32 Seq);

    bool InvokeMovePlayer(const FReducerEventContext& Context, const UMovePlayerReducer* Args);
    bool InvokeMovePlayerWithArgs(const FReducerEventContext& Context, const FMovePlayerArgs& Args);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(
        FSeedEntitiesHandler,
        const FReducerEventContext&, Context,
        uint32, Count
    );
    // NOTE: Not exposed to Blueprint because uint32 types are not Blueprint-compatible
    FSeedEntitiesHandler OnSeedEntities;

    // NOTE: Not exposed to Blueprint because uint32 types are not Blueprint-compatible
    void SeedEntities(const uint32 Count);

    bool InvokeSeedEntities(const FReducerEventContext& Context, const USeedEntitiesReducer* Args);
    bool InvokeSeedEntitiesWithArgs(const FReducerEventContext& Context, const FSeedEntitiesArgs& Args);

    // Internal error handling
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FInternalOnUnhandledReducerError, const FReducerEventContext&, Context, const FString&, Error);
    FInternalOnUnhandledReducerError InternalOnUnhandledReducerError;

private:

    friend UDbConnection;

    UPROPERTY()
    class UDbConnection* Conn;

    UPROPERTY()
    USetReducerFlags* SetCallReducerFlags;
};

// RemoteProcedures class
UCLASS(BlueprintType)
class NYX_API URemoteProcedures : public UObject
{
    GENERATED_BODY()

public:

    // Internal error handling
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FInternalOnUnhandledProcedureError, const FProcedureEventContext&, Context, const FString&, Error);
    FInternalOnUnhandledProcedureError InternalOnUnhandledProcedureError;

private:

    friend UDbConnection;

    UPROPERTY()
    class UDbConnection* Conn;
};

// SubscriptionBuilder class
UCLASS(BlueprintType)
class NYX_API USubscriptionBuilder : public USubscriptionBuilderBase
{
    GENERATED_BODY()

public:

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    USubscriptionBuilder* OnApplied(FOnSubscriptionApplied Callback);

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    USubscriptionBuilder* OnError(FOnSubscriptionError Callback);

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    USubscriptionHandle* Subscribe(const TArray<FString>& SQL);

    /** Convenience for subscribing to all rows from all tables */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    USubscriptionHandle* SubscribeToAllTables();


    friend class UDbConnection;
    friend class UDbConnectionBase;

protected:
    UPROPERTY()
    class UDbConnection* Conn;

    // Delegates stored so Subscribe() can bind forwarding callbacks
    FOnSubscriptionApplied OnAppliedDelegateInternal;
    FOnSubscriptionError OnErrorDelegateInternal;
};

// SubscriptionHandle class
UCLASS(BlueprintType)
class NYX_API USubscriptionHandle : public USubscriptionHandleBase
{
    GENERATED_BODY()

public:

    USubscriptionHandle() {};

    explicit USubscriptionHandle(UDbConnection* InConn);

    friend class USubscriptionBuilder;

private:
    UPROPERTY()
    class UDbConnection* Conn;

    // Delegates that expose subscription events with connection aware contexts
    FOnSubscriptionApplied OnAppliedDelegate;
    FOnSubscriptionError OnErrorDelegate;

    UFUNCTION()
    void ForwardOnApplied(const FSubscriptionEventContextBase& BaseCtx);

    UFUNCTION()
    void ForwardOnError(const FErrorContextBase& BaseCtx);
};

/*
    @Note: Child class of UDbConnectionBuilderBase.
*/
UCLASS(BlueprintType)
class NYX_API UDbConnectionBuilder : public UDbConnectionBuilderBase
{
    GENERATED_BODY()
public:

    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnectionBuilder* WithUri(const FString& InUri);
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnectionBuilder* WithDatabaseName(const FString& InName);
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnectionBuilder* WithToken(const FString& InToken);
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnectionBuilder* WithCompression(const ESpacetimeDBCompression& InCompression);
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnectionBuilder* OnConnect(FOnConnectDelegate Callback);
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnectionBuilder* OnConnectError(FOnConnectErrorDelegate Callback);
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnectionBuilder* OnDisconnect(FOnDisconnectDelegate Callback);
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    UDbConnection* Build();

private:

    // Stored delegates which will be forwarded when the connection events occur.
    FOnConnectDelegate OnConnectDelegateInternal;
    FOnDisconnectDelegate OnDisconnectDelegateInternal;
};

// Main DbConnection class
UCLASS(BlueprintType)
class NYX_API UDbConnection : public UDbConnectionBase
{
    GENERATED_BODY()

public:
    explicit UDbConnection(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get());


    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    URemoteTables* Db;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    URemoteReducers* Reducers;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    USetReducerFlags* SetReducerFlags;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    URemoteProcedures* Procedures;

    // Delegates that allow users to bind with the concrete connection type.
    FOnConnectDelegate OnConnectDelegate;
    FOnDisconnectDelegate OnDisconnectDelegate;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    USubscriptionBuilder* SubscriptionBuilder();

    /** Static entry point for constructing a connection. */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB", DisplayName = "SpacetimeDB Builder")
    static UDbConnectionBuilder* Builder();

    // Error handling
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FOnUnhandledReducerError, const FReducerEventContext&, Context, const FString&, Error);
    UPROPERTY(BlueprintAssignable, Category="SpacetimeDB")
    FOnUnhandledReducerError OnUnhandledReducerError;

    // Error handling
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FOnUnhandledProcedureError, const FProcedureEventContext&, Context, const FString&, Error);
    UPROPERTY(BlueprintAssignable, Category="SpacetimeDB")
    FOnUnhandledProcedureError OnUnhandledProcedureError;


protected:

    // Hook up error handling to reducers and procedures
    virtual void PostInitProperties() override;

    UFUNCTION()
    void ForwardOnConnect(UDbConnectionBase* BaseConnection, FSpacetimeDBIdentity InIdentity, const FString& InToken);
    UFUNCTION()
    void ForwardOnDisconnect(UDbConnectionBase* BaseConnection, const FString& Error);

    UFUNCTION()
    void OnUnhandledReducerErrorHandler(const FReducerEventContext& Context, const FString& Error);

    UFUNCTION()
    void OnUnhandledProcedureErrorHandler(const FProcedureEventContext& Context, const FString& Error);

    // Override the DbConnectionBase methods to handle updates and events
    virtual void DbUpdate(const FDatabaseUpdateType& Update, const FSpacetimeDBEvent& Event) override;
    
    // Override the reducer event handler to dispatch events to the appropriate reducers
    virtual void ReducerEvent(const FReducerEvent& Event) override;
    
    // Override the reducer event failed handler
    virtual void ReducerEventFailed(const FReducerEvent& Event, const FString ErrorMessage) override;
    // Override the procedure event failed handler
    virtual void ProcedureEventFailed(const FProcedureEvent& Event, const FString ErrorMessage) override;
};

