// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "Types/Builtins.h"
#include "AssignPlayerToZone.g.generated.h"

// Reducer arguments struct for AssignPlayerToZone
USTRUCT(BlueprintType)
struct NYX_API FAssignPlayerToZoneArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FString ZoneId;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FSpacetimeDBIdentity PlayerIdentity;

    FAssignPlayerToZoneArgs() = default;

    FAssignPlayerToZoneArgs(const FString& InZoneId, const FSpacetimeDBIdentity& InPlayerIdentity)
        : ZoneId(InZoneId), PlayerIdentity(InPlayerIdentity)
    {}


    FORCEINLINE bool operator==(const FAssignPlayerToZoneArgs& Other) const
    {
        return ZoneId == Other.ZoneId && PlayerIdentity == Other.PlayerIdentity;
    }
    FORCEINLINE bool operator!=(const FAssignPlayerToZoneArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FAssignPlayerToZoneArgs, ZoneId, PlayerIdentity);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API UAssignPlayerToZoneReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FString ZoneId;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FSpacetimeDBIdentity PlayerIdentity;

};


