// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "AuthenticateWithEos.g.generated.h"

// Reducer arguments struct for AuthenticateWithEos
USTRUCT(BlueprintType)
struct NYX_API FAuthenticateWithEosArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FString EosProductUserId;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FString DisplayName;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FString Platform;

    FAuthenticateWithEosArgs() = default;

    FAuthenticateWithEosArgs(const FString& InEosProductUserId, const FString& InDisplayName, const FString& InPlatform)
        : EosProductUserId(InEosProductUserId), DisplayName(InDisplayName), Platform(InPlatform)
    {}


    FORCEINLINE bool operator==(const FAuthenticateWithEosArgs& Other) const
    {
        return EosProductUserId == Other.EosProductUserId && DisplayName == Other.DisplayName && Platform == Other.Platform;
    }
    FORCEINLINE bool operator!=(const FAuthenticateWithEosArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FAuthenticateWithEosArgs, EosProductUserId, DisplayName, Platform);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API UAuthenticateWithEosReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FString EosProductUserId;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FString DisplayName;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FString Platform;

};


