// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "ClearEntities.g.generated.h"

// Reducer arguments struct for ClearEntities
USTRUCT(BlueprintType)
struct NYX_API FClearEntitiesArgs
{
    GENERATED_BODY()

    FClearEntitiesArgs() = default;


    FORCEINLINE bool operator==(const FClearEntitiesArgs& Other) const
    {
        return true;
    }
    FORCEINLINE bool operator!=(const FClearEntitiesArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT_EMPTY(FClearEntitiesArgs);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API UClearEntitiesReducer : public UReducerBase
{
    GENERATED_BODY()

public:
};


