// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "CreatePlayer.g.generated.h"

// Reducer arguments struct for CreatePlayer
USTRUCT(BlueprintType)
struct NYX_API FCreatePlayerArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FString DisplayName;

    FCreatePlayerArgs() = default;

    FCreatePlayerArgs(const FString& InDisplayName)
        : DisplayName(InDisplayName)
    {}


    FORCEINLINE bool operator==(const FCreatePlayerArgs& Other) const
    {
        return DisplayName == Other.DisplayName;
    }
    FORCEINLINE bool operator!=(const FCreatePlayerArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FCreatePlayerArgs, DisplayName);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API UCreatePlayerReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FString DisplayName;

};


