// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "DeregisterZoneServer.g.generated.h"

// Reducer arguments struct for DeregisterZoneServer
USTRUCT(BlueprintType)
struct NYX_API FDeregisterZoneServerArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FString ServerId;

    FDeregisterZoneServerArgs() = default;

    FDeregisterZoneServerArgs(const FString& InServerId)
        : ServerId(InServerId)
    {}


    FORCEINLINE bool operator==(const FDeregisterZoneServerArgs& Other) const
    {
        return ServerId == Other.ServerId;
    }
    FORCEINLINE bool operator!=(const FDeregisterZoneServerArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FDeregisterZoneServerArgs, ServerId);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API UDeregisterZoneServerReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FString ServerId;

};


