// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "DrainZoneServer.g.generated.h"

// Reducer arguments struct for DrainZoneServer
USTRUCT(BlueprintType)
struct NYX_API FDrainZoneServerArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FString ServerId;

    FDrainZoneServerArgs() = default;

    FDrainZoneServerArgs(const FString& InServerId)
        : ServerId(InServerId)
    {}


    FORCEINLINE bool operator==(const FDrainZoneServerArgs& Other) const
    {
        return ServerId == Other.ServerId;
    }
    FORCEINLINE bool operator!=(const FDrainZoneServerArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FDrainZoneServerArgs, ServerId);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API UDrainZoneServerReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FString ServerId;

};


