// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "FanoutSeed.g.generated.h"

// Reducer arguments struct for FanoutSeed
USTRUCT(BlueprintType)
struct NYX_API FFanoutSeedArgs
{
    GENERATED_BODY()

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Count = 0;

    FFanoutSeedArgs() = default;

    FFanoutSeedArgs(const uint32& InCount)
        : Count(InCount)
    {}


    FORCEINLINE bool operator==(const FFanoutSeedArgs& Other) const
    {
        return Count == Other.Count;
    }
    FORCEINLINE bool operator!=(const FFanoutSeedArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FFanoutSeedArgs, Count);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API UFanoutSeedReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 Count = 0;

};


