// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "FanoutStop.g.generated.h"

// Reducer arguments struct for FanoutStop
USTRUCT(BlueprintType)
struct NYX_API FFanoutStopArgs
{
    GENERATED_BODY()

    FFanoutStopArgs() = default;


    FORCEINLINE bool operator==(const FFanoutStopArgs& Other) const
    {
        return true;
    }
    FORCEINLINE bool operator!=(const FFanoutStopArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT_EMPTY(FFanoutStopArgs);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API UFanoutStopReducer : public UReducerBase
{
    GENERATED_BODY()

public:
};


