// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "FanoutStart.g.generated.h"

// Reducer arguments struct for FanoutStart
USTRUCT(BlueprintType)
struct NYX_API FFanoutStartArgs
{
    GENERATED_BODY()

    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 IntervalMs = 0;

    FFanoutStartArgs() = default;

    FFanoutStartArgs(const uint64& InIntervalMs)
        : IntervalMs(InIntervalMs)
    {}


    FORCEINLINE bool operator==(const FFanoutStartArgs& Other) const
    {
        return IntervalMs == Other.IntervalMs;
    }
    FORCEINLINE bool operator!=(const FFanoutStartArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FFanoutStartArgs, IntervalMs);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API UFanoutStartReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 IntervalMs = 0;

};


