// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "Types/Builtins.h"
#include "LoadCharacter.g.generated.h"

// Reducer arguments struct for LoadCharacter
USTRUCT(BlueprintType)
struct NYX_API FLoadCharacterArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FSpacetimeDBIdentity Identity;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FString DisplayName;

    FLoadCharacterArgs() = default;

    FLoadCharacterArgs(const FSpacetimeDBIdentity& InIdentity, const FString& InDisplayName)
        : Identity(InIdentity), DisplayName(InDisplayName)
    {}


    FORCEINLINE bool operator==(const FLoadCharacterArgs& Other) const
    {
        return Identity == Other.Identity && DisplayName == Other.DisplayName;
    }
    FORCEINLINE bool operator!=(const FLoadCharacterArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FLoadCharacterArgs, Identity, DisplayName);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API ULoadCharacterReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FSpacetimeDBIdentity Identity;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FString DisplayName;

};


