// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "MovePlayer.g.generated.h"

// Reducer arguments struct for MovePlayer
USTRUCT(BlueprintType)
struct NYX_API FMovePlayerArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    double X = 0.0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    double Y = 0.0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    double Z = 0.0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    float Yaw = 0.0f;

    FMovePlayerArgs() = default;

    FMovePlayerArgs(const double& InX, const double& InY, const double& InZ, const float& InYaw)
        : X(InX), Y(InY), Z(InZ), Yaw(InYaw)
    {}


    FORCEINLINE bool operator==(const FMovePlayerArgs& Other) const
    {
        return X == Other.X && Y == Other.Y && Z == Other.Z && Yaw == Other.Yaw;
    }
    FORCEINLINE bool operator!=(const FMovePlayerArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FMovePlayerArgs, X, Y, Z, Yaw);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API UMovePlayerReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    double X = 0.0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    double Y = 0.0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    double Z = 0.0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    float Yaw = 0.0f;

};


