// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "PhysicsCleanup.g.generated.h"

// Reducer arguments struct for PhysicsCleanup
USTRUCT(BlueprintType)
struct NYX_API FPhysicsCleanupArgs
{
    GENERATED_BODY()

    FPhysicsCleanupArgs() = default;


    FORCEINLINE bool operator==(const FPhysicsCleanupArgs& Other) const
    {
        return true;
    }
    FORCEINLINE bool operator!=(const FPhysicsCleanupArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT_EMPTY(FPhysicsCleanupArgs);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API UPhysicsCleanupReducer : public UReducerBase
{
    GENERATED_BODY()

public:
};


