// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "PhysicsReset.g.generated.h"

// Reducer arguments struct for PhysicsReset
USTRUCT(BlueprintType)
struct NYX_API FPhysicsResetArgs
{
    GENERATED_BODY()

    FPhysicsResetArgs() = default;


    FORCEINLINE bool operator==(const FPhysicsResetArgs& Other) const
    {
        return true;
    }
    FORCEINLINE bool operator!=(const FPhysicsResetArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT_EMPTY(FPhysicsResetArgs);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API UPhysicsResetReducer : public UReducerBase
{
    GENERATED_BODY()

public:
};


