// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "PhysicsUpdate.g.generated.h"

// Reducer arguments struct for PhysicsUpdate
USTRUCT(BlueprintType)
struct NYX_API FPhysicsUpdateArgs
{
    GENERATED_BODY()

    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 EntityId = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    double PosX = 0.0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    double PosY = 0.0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    double PosZ = 0.0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    double VelX = 0.0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    double VelY = 0.0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    double VelZ = 0.0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    bool Active = false;

    FPhysicsUpdateArgs() = default;

    FPhysicsUpdateArgs(const uint64& InEntityId, const double& InPosX, const double& InPosY, const double& InPosZ, const double& InVelX, const double& InVelY, const double& InVelZ, const bool& InActive)
        : EntityId(InEntityId), PosX(InPosX), PosY(InPosY), PosZ(InPosZ), VelX(InVelX), VelY(InVelY), VelZ(InVelZ), Active(InActive)
    {}


    FORCEINLINE bool operator==(const FPhysicsUpdateArgs& Other) const
    {
        return EntityId == Other.EntityId && PosX == Other.PosX && PosY == Other.PosY && PosZ == Other.PosZ && VelX == Other.VelX && VelY == Other.VelY && VelZ == Other.VelZ && Active == Other.Active;
    }
    FORCEINLINE bool operator!=(const FPhysicsUpdateArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FPhysicsUpdateArgs, EntityId, PosX, PosY, PosZ, VelX, VelY, VelZ, Active);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API UPhysicsUpdateReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 EntityId = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    double PosX = 0.0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    double PosY = 0.0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    double PosZ = 0.0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    double VelX = 0.0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    double VelY = 0.0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    double VelZ = 0.0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    bool Active = false;

};


