// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "ModuleBindings/Types/BodyUpdateType.g.h"
#include "PhysicsUpdateBatch.g.generated.h"

// Reducer arguments struct for PhysicsUpdateBatch
USTRUCT(BlueprintType)
struct NYX_API FPhysicsUpdateBatchArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    TArray<FBodyUpdateType> Updates;

    FPhysicsUpdateBatchArgs() = default;

    FPhysicsUpdateBatchArgs(const TArray<FBodyUpdateType>& InUpdates)
        : Updates(InUpdates)
    {}


    FORCEINLINE bool operator==(const FPhysicsUpdateBatchArgs& Other) const
    {
        return Updates == Other.Updates;
    }
    FORCEINLINE bool operator!=(const FPhysicsUpdateBatchArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FPhysicsUpdateBatchArgs, Updates);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API UPhysicsUpdateBatchReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    TArray<FBodyUpdateType> Updates;

};


