// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "RegisterZoneServer.g.generated.h"

// Reducer arguments struct for RegisterZoneServer
USTRUCT(BlueprintType)
struct NYX_API FRegisterZoneServerArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FString ServerId;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FString ZoneId;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FString ContainerIp;

    // NOTE: uint16 field not exposed to Blueprint due to non-blueprintable elements
    uint16 Port = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 MaxEntities = 0;

    FRegisterZoneServerArgs() = default;

    FRegisterZoneServerArgs(const FString& InServerId, const FString& InZoneId, const FString& InContainerIp, const uint16& InPort, const uint32& InMaxEntities)
        : ServerId(InServerId), ZoneId(InZoneId), ContainerIp(InContainerIp), Port(InPort), MaxEntities(InMaxEntities)
    {}


    FORCEINLINE bool operator==(const FRegisterZoneServerArgs& Other) const
    {
        return ServerId == Other.ServerId && ZoneId == Other.ZoneId && ContainerIp == Other.ContainerIp && Port == Other.Port && MaxEntities == Other.MaxEntities;
    }
    FORCEINLINE bool operator!=(const FRegisterZoneServerArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FRegisterZoneServerArgs, ServerId, ZoneId, ContainerIp, Port, MaxEntities);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API URegisterZoneServerReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FString ServerId;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FString ZoneId;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FString ContainerIp;
    // NOTE: uint16 field not exposed to Blueprint due to non-blueprintable elements
    uint16 Port = 0;
    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 MaxEntities = 0;

};


