// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "Types/Builtins.h"
#include "ResolveHitBatch.g.generated.h"

// Reducer arguments struct for ResolveHitBatch
USTRUCT(BlueprintType)
struct NYX_API FResolveHitBatchArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FSpacetimeDBIdentity AttackerId;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    TArray<FSpacetimeDBIdentity> DefenderIds;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 SkillId = 0;

    FResolveHitBatchArgs() = default;

    FResolveHitBatchArgs(const FSpacetimeDBIdentity& InAttackerId, const TArray<FSpacetimeDBIdentity>& InDefenderIds, const uint32& InSkillId)
        : AttackerId(InAttackerId), DefenderIds(InDefenderIds), SkillId(InSkillId)
    {}


    FORCEINLINE bool operator==(const FResolveHitBatchArgs& Other) const
    {
        return AttackerId == Other.AttackerId && DefenderIds == Other.DefenderIds && SkillId == Other.SkillId;
    }
    FORCEINLINE bool operator!=(const FResolveHitBatchArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FResolveHitBatchArgs, AttackerId, DefenderIds, SkillId);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API UResolveHitBatchReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FSpacetimeDBIdentity AttackerId;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    TArray<FSpacetimeDBIdentity> DefenderIds;
    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 SkillId = 0;

};


