// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "Types/Builtins.h"
#include "ResolveHeal.g.generated.h"

// Reducer arguments struct for ResolveHeal
USTRUCT(BlueprintType)
struct NYX_API FResolveHealArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FSpacetimeDBIdentity HealerId;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FSpacetimeDBIdentity TargetId;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 SkillId = 0;

    FResolveHealArgs() = default;

    FResolveHealArgs(const FSpacetimeDBIdentity& InHealerId, const FSpacetimeDBIdentity& InTargetId, const uint32& InSkillId)
        : HealerId(InHealerId), TargetId(InTargetId), SkillId(InSkillId)
    {}


    FORCEINLINE bool operator==(const FResolveHealArgs& Other) const
    {
        return HealerId == Other.HealerId && TargetId == Other.TargetId && SkillId == Other.SkillId;
    }
    FORCEINLINE bool operator!=(const FResolveHealArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FResolveHealArgs, HealerId, TargetId, SkillId);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API UResolveHealReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FSpacetimeDBIdentity HealerId;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FSpacetimeDBIdentity TargetId;
    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 SkillId = 0;

};


