// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "Types/Builtins.h"
#include "ResolveHit.g.generated.h"

// Reducer arguments struct for ResolveHit
USTRUCT(BlueprintType)
struct NYX_API FResolveHitArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FSpacetimeDBIdentity AttackerId;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FSpacetimeDBIdentity DefenderId;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 SkillId = 0;

    FResolveHitArgs() = default;

    FResolveHitArgs(const FSpacetimeDBIdentity& InAttackerId, const FSpacetimeDBIdentity& InDefenderId, const uint32& InSkillId)
        : AttackerId(InAttackerId), DefenderId(InDefenderId), SkillId(InSkillId)
    {}


    FORCEINLINE bool operator==(const FResolveHitArgs& Other) const
    {
        return AttackerId == Other.AttackerId && DefenderId == Other.DefenderId && SkillId == Other.SkillId;
    }
    FORCEINLINE bool operator!=(const FResolveHitArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FResolveHitArgs, AttackerId, DefenderId, SkillId);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API UResolveHitReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FSpacetimeDBIdentity AttackerId;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FSpacetimeDBIdentity DefenderId;
    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 SkillId = 0;

};


