// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "Types/Builtins.h"
#include "SaveCharacter.g.generated.h"

// Reducer arguments struct for SaveCharacter
USTRUCT(BlueprintType)
struct NYX_API FSaveCharacterArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FSpacetimeDBIdentity Identity;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 CurrentHp = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 CurrentMp = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    double PosX = 0.0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    double PosY = 0.0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    double PosZ = 0.0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    float RotYaw = 0.0f;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FString ZoneId;

    FSaveCharacterArgs() = default;

    FSaveCharacterArgs(const FSpacetimeDBIdentity& InIdentity, const int32& InCurrentHp, const int32& InCurrentMp, const double& InPosX, const double& InPosY, const double& InPosZ, const float& InRotYaw, const FString& InZoneId)
        : Identity(InIdentity), CurrentHp(InCurrentHp), CurrentMp(InCurrentMp), PosX(InPosX), PosY(InPosY), PosZ(InPosZ), RotYaw(InRotYaw), ZoneId(InZoneId)
    {}


    FORCEINLINE bool operator==(const FSaveCharacterArgs& Other) const
    {
        return Identity == Other.Identity && CurrentHp == Other.CurrentHp && CurrentMp == Other.CurrentMp && PosX == Other.PosX && PosY == Other.PosY && PosZ == Other.PosZ && RotYaw == Other.RotYaw && ZoneId == Other.ZoneId;
    }
    FORCEINLINE bool operator!=(const FSaveCharacterArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FSaveCharacterArgs, Identity, CurrentHp, CurrentMp, PosX, PosY, PosZ, RotYaw, ZoneId);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API USaveCharacterReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FSpacetimeDBIdentity Identity;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 CurrentHp = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 CurrentMp = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    double PosX = 0.0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    double PosY = 0.0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    double PosZ = 0.0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    float RotYaw = 0.0f;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FString ZoneId;

};


