// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "SpawnProjectile.g.generated.h"

// Reducer arguments struct for SpawnProjectile
USTRUCT(BlueprintType)
struct NYX_API FSpawnProjectileArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    double PosX = 0.0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    double PosY = 0.0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    double PosZ = 0.0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    double VelX = 0.0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    double VelY = 0.0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    double VelZ = 0.0;

    FSpawnProjectileArgs() = default;

    FSpawnProjectileArgs(const double& InPosX, const double& InPosY, const double& InPosZ, const double& InVelX, const double& InVelY, const double& InVelZ)
        : PosX(InPosX), PosY(InPosY), PosZ(InPosZ), VelX(InVelX), VelY(InVelY), VelZ(InVelZ)
    {}


    FORCEINLINE bool operator==(const FSpawnProjectileArgs& Other) const
    {
        return PosX == Other.PosX && PosY == Other.PosY && PosZ == Other.PosZ && VelX == Other.VelX && VelY == Other.VelY && VelZ == Other.VelZ;
    }
    FORCEINLINE bool operator!=(const FSpawnProjectileArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FSpawnProjectileArgs, PosX, PosY, PosZ, VelX, VelY, VelZ);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API USpawnProjectileReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    double PosX = 0.0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    double PosY = 0.0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    double PosZ = 0.0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    double VelX = 0.0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    double VelY = 0.0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    double VelZ = 0.0;

};


