// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "StressMove.g.generated.h"

// Reducer arguments struct for StressMove
USTRUCT(BlueprintType)
struct NYX_API FStressMoveArgs
{
    GENERATED_BODY()

    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 EntityId = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    double Dx = 0.0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    double Dy = 0.0;

    FStressMoveArgs() = default;

    FStressMoveArgs(const uint64& InEntityId, const double& InDx, const double& InDy)
        : EntityId(InEntityId), Dx(InDx), Dy(InDy)
    {}


    FORCEINLINE bool operator==(const FStressMoveArgs& Other) const
    {
        return EntityId == Other.EntityId && Dx == Other.Dx && Dy == Other.Dy;
    }
    FORCEINLINE bool operator!=(const FStressMoveArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FStressMoveArgs, EntityId, Dx, Dy);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API UStressMoveReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 EntityId = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    double Dx = 0.0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    double Dy = 0.0;

};


