// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "StressRecord.g.generated.h"

// Reducer arguments struct for StressRecord
USTRUCT(BlueprintType)
struct NYX_API FStressRecordArgs
{
    GENERATED_BODY()

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 ClientCount = 0;

    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 WindowMs = 0;

    FStressRecordArgs() = default;

    FStressRecordArgs(const uint32& InClientCount, const uint64& InWindowMs)
        : ClientCount(InClientCount), WindowMs(InWindowMs)
    {}


    FORCEINLINE bool operator==(const FStressRecordArgs& Other) const
    {
        return ClientCount == Other.ClientCount && WindowMs == Other.WindowMs;
    }
    FORCEINLINE bool operator!=(const FStressRecordArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FStressRecordArgs, ClientCount, WindowMs);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API UStressRecordReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 ClientCount = 0;
    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 WindowMs = 0;

};


