// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "StressReset.g.generated.h"

// Reducer arguments struct for StressReset
USTRUCT(BlueprintType)
struct NYX_API FStressResetArgs
{
    GENERATED_BODY()

    FStressResetArgs() = default;


    FORCEINLINE bool operator==(const FStressResetArgs& Other) const
    {
        return true;
    }
    FORCEINLINE bool operator!=(const FStressResetArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT_EMPTY(FStressResetArgs);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API UStressResetReducer : public UReducerBase
{
    GENERATED_BODY()

public:
};


