// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "TestCombatPipeline.g.generated.h"

// Reducer arguments struct for TestCombatPipeline
USTRUCT(BlueprintType)
struct NYX_API FTestCombatPipelineArgs
{
    GENERATED_BODY()

    FTestCombatPipelineArgs() = default;


    FORCEINLINE bool operator==(const FTestCombatPipelineArgs& Other) const
    {
        return true;
    }
    FORCEINLINE bool operator!=(const FTestCombatPipelineArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT_EMPTY(FTestCombatPipelineArgs);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API UTestCombatPipelineReducer : public UReducerBase
{
    GENERATED_BODY()

public:
};


