// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "Types/Builtins.h"
#include "UpdateProgression.g.generated.h"

// Reducer arguments struct for UpdateProgression
USTRUCT(BlueprintType)
struct NYX_API FUpdateProgressionArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FSpacetimeDBIdentity Identity;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 NewLevel = 0;

    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 NewExperience = 0;

    FUpdateProgressionArgs() = default;

    FUpdateProgressionArgs(const FSpacetimeDBIdentity& InIdentity, const uint32& InNewLevel, const uint64& InNewExperience)
        : Identity(InIdentity), NewLevel(InNewLevel), NewExperience(InNewExperience)
    {}


    FORCEINLINE bool operator==(const FUpdateProgressionArgs& Other) const
    {
        return Identity == Other.Identity && NewLevel == Other.NewLevel && NewExperience == Other.NewExperience;
    }
    FORCEINLINE bool operator!=(const FUpdateProgressionArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FUpdateProgressionArgs, Identity, NewLevel, NewExperience);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class NYX_API UUpdateProgressionReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FSpacetimeDBIdentity Identity;
    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 NewLevel = 0;
    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 NewExperience = 0;

};


